<?php // All values come from the article-scoped, paginated read service. ?>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>OF / Cliente</th><th>Data</th><th>Planeada</th><th>Produzida</th><th>Estado / Origem</th><?php if($tab==='costs'): ?><th>Tempo previsto / real</th><th>Custo previsto / real</th><th>Custo real por unidade</th><?php endif; ?></tr></thead><tbody>
<?php foreach($data['rows'] as $r): $customer=$data['customers'][$r['id']]??[]; ?>
<tr><td><a class="fw-semibold" href="production_dossier.php?id=<?= (int)$r['id'] ?>"><?= h($r['order_number']) ?></a><div class="small text-secondary"><?php if(!empty($customer['customer_id'])): ?><a href="erp.php?page=customer_profile&amp;id=<?= (int)$customer['customer_id'] ?>"><?= h(ap_value($customer['customer_name'])) ?></a><?php else: ?>Sem cliente associado<?php endif; ?></div><?php if(isset($data['sheets'][$r['id']])): ?><a class="small" href="erp_technical_sheet.php?id=<?= (int)$data['sheets'][$r['id']] ?>" target="_blank" rel="noopener">Ficha técnica utilizada</a><?php endif; ?></td><td><?= h(ap_date($r['created_at'])) ?></td><td><?= h(ap_quantity($r['planned_quantity'],$r['unit'])) ?></td><td><?= h(ap_quantity($r['produced_quantity'],$r['unit'])) ?></td><td><?= h($r['status']) ?><div class="small text-secondary"><?= $r['legacy_id']!==null?'Histórico Bobinas · '.h($r['legacy_id']):'GesTISSER' ?></div></td>
<?php if($tab==='costs'): $closure=$data['closures'][$r['id']]??null;$real=$data['times'][$r['id']]??null;$planned=$data['planned'][$r['id']]??null;$metrics=$closure?(json_decode($closure['metrics_json'],true)?:[]):[];if(isset($metrics['planned_minutes']))$planned=(float)$metrics['planned_minutes']/60;if(isset($metrics['actual_minutes']))$real=(float)$metrics['actual_minutes']/60; ?>
<td><?= h(ap_value($planned===null?null:ap_number($planned),'h').' / '.ap_value($real===null?null:ap_number($real),'h')) ?><?php if($planned!==null&&$real!==null): ?><div class="small text-secondary">Desvio: <?= h(ap_number($real-$planned).' h') ?></div><?php endif; ?></td><td><?= $closure?h(ap_number($closure['total_planned_cost']).' € / '.ap_number($closure['total_actual_cost']).' €'):'Sem fecho de custeio registado' ?><?php if($closure): ?><div class="small text-secondary">Desvio: <?= h(ap_number((float)$closure['total_actual_cost']-(float)$closure['total_planned_cost']).' €') ?></div><?php endif; ?></td><td><?php $good=isset($metrics['good'])?(float)$metrics['good']:(float)$r['produced_quantity']; ?><?= $closure&&$good>0?h(ap_number((float)$closure['total_actual_cost']/$good,4).' € / '.($r['unit']?:'unidade não registada')):'Sem dados' ?></td>
<?php endif; ?></tr>
<?php if($tab!=='overview'): ?><tr><td colspan="<?= $tab==='costs'?8:5 ?>"><details <?= $tab==='trace'?'open':'' ?>><summary class="small"><?= $tab==='trace'?'Consumos e lotes de origem':'Operações realizadas / snapshots históricos' ?></summary>
<ul class="small mt-2"><?php foreach($data['operations'][$r['id']]??[] as $op): ?><li><?= h($op['name'].' · '.ap_value($op['status'])) ?><?php if($tab==='costs'&&isset($op['planned_minutes'])): ?> · Previsto: <?= h(ap_number($op['planned_minutes']).' min') ?> · Real encerrado: <?= h(ap_value(isset($data['operation_hours'][$op['id']])?ap_number($data['operation_hours'][$op['id']]):null,'h')) ?><?php endif; ?></li><?php endforeach; ?></ul><?php if(empty($data['operations'][$r['id']])): ?><p class="small text-secondary">Sem operações registadas nesta OF.</p><?php endif; ?>
<?php if($tab==='costs'): ?><h4 class="h6">Custos registados por categoria</h4><ul class="small"><?php foreach($data['costs'][$r['id']]??[] as $c): ?><li><?= h($c['category'].' · Previsto: '.ap_number($c['planned']).' € · Real: '.ap_number($c['actual']).' €') ?></li><?php endforeach; ?></ul><?php if(empty($data['costs'][$r['id']])): ?><p class="small text-secondary">Sem custos detalhados por categoria. O total do fecho, quando disponível, permanece acessível.</p><?php endif; ?><h4 class="h6">Consumos de matérias-primas registados</h4><ul class="small"><?php foreach($data['cost_consumptions'][$r['id']]??[] as $c): ?><li><?= h(ap_value($c['code']).' · '.ap_quantity($c['quantity'],$c['unit_code']).' · lote: '.($c['lot']?:'não registado').' · custo unitário registado: '.ap_value($c['unit_cost']===null?null:ap_number($c['unit_cost'],4),'€')) ?></li><?php endforeach; ?></ul><?php if(empty($data['cost_consumptions'][$r['id']])): ?><p class="small text-secondary">Sem consumos neste resumo.</p><?php endif; ?><a class="small" href="<?= h(ap_url($id,'trace',$filters)) ?>">Consultar consumos de matérias-primas e lotes</a><?php endif; ?>
<?php if($tab==='trace'): ?>
<h4 class="h6">Consumos efetivos</h4><ul class="small"><?php foreach($data['consumptions'][$r['id']]??[] as $c): ?><li><?= h(ap_value($c['material_code']).' · '.ap_quantity($c['quantity'],$c['unit_code']).' · lote: '.($c['lot']?:'não registado').' · '.ap_date($c['created_at'])) ?><?php if($c['stock_unit_id']): ?> · <?= h($c['stock_unit_type']) ?> #<?= (int)$c['stock_unit_id'] ?><?php endif; ?><?php if($c['stock_unit_type']==='INK'&&$c['stock_unit_id']): ?> · <a href="<?= h(ap_url($id,'trace',['unit_type'=>'INK','stock_unit'=>(int)$c['stock_unit_id']])) ?>">OF / artigos deste recipiente</a><?php endif; ?><?php if($c['ink_barcode']): ?> · recipiente <?= h($c['ink_barcode'].' · lote '.$c['ink_lot']) ?><?php endif; ?><?php if($c['movement_number']): ?> · movimento <?= h($c['movement_number']) ?><?php endif; ?></li><?php endforeach; ?><?php foreach($data['rolls'][$r['id']]??[] as $roll): ?><li>Rolo <?= h($roll['barcode'].' · lote '.$roll['supplier_lot'].' · '.ap_number($roll['consumed_metres']).' m / '.ap_number($roll['consumed_weight_kg']).' kg · '.ap_date($roll['created_at'])) ?> · <a href="<?= h(ap_url($id,'trace',['unit_type'=>'ROLL','stock_unit'=>(int)$roll['source_label_id']])) ?>">OF / artigos deste rolo</a></li><?php endforeach; ?></ul>
<?php if(empty($data['consumptions'][$r['id']])&&empty($data['rolls'][$r['id']])): ?><p class="small text-secondary">Sem ligações comprovadas a consumos, rolos ou lotes neste resumo. Consulte a OF para os detalhes completos.</p><?php endif; ?>
<h4 class="h6">Reservas previstas</h4><ul class="small"><?php foreach($data['reservations'][$r['id']]??[] as $reserve): ?><li><?= h(ap_value($reserve['code']).' · '.ap_quantity($reserve['reserved_qty'],$reserve['unit']).' · lote: '.($reserve['lot']?:'não registado')) ?></li><?php endforeach; ?></ul><?php if(empty($data['reservations'][$r['id']])): ?><p class="small text-secondary">Sem reservas registadas neste resumo.</p><?php endif; ?>
<?php endif; ?></details></td></tr><?php endif; ?>
<?php endforeach; ?><?php if(!$data['rows']): ?><tr><td colspan="<?= $tab==='costs'?8:5 ?>" class="text-secondary py-4">Sem ordens de fabrico associadas<?= $tab==='overview'?'':' para os filtros selecionados' ?>.</td></tr><?php endif; ?></tbody></table></div>
<?php if($tab==='overview'): ?><a class="btn btn-sm btn-outline-primary" href="<?= h(ap_url($id,'history')) ?>"><i class="bi bi-arrow-right me-1" aria-hidden="true"></i>Ver todas as OF</a><?php else: ?>
<nav aria-label="Paginação" class="d-flex flex-wrap justify-content-between align-items-center gap-2 mt-3"><span class="small text-secondary"><?= (int)$data['total'] ?> registos · página <?= (int)$data['page'] ?> / <?= (int)$data['pages'] ?></span><div class="d-flex gap-2"><?php if($data['page']>1): ?><a class="btn btn-sm btn-outline-secondary" href="<?= h(ap_url($id,$tab,array_merge($filters,['p'=>$data['page']-1]))) ?>"><i class="bi bi-chevron-left me-1" aria-hidden="true"></i>Anterior</a><?php endif; ?><?php if($data['page']<$data['pages']): ?><a class="btn btn-sm btn-outline-secondary" href="<?= h(ap_url($id,$tab,array_merge($filters,['p'=>$data['page']+1]))) ?>"><i class="bi bi-chevron-right me-1" aria-hidden="true"></i>Seguinte</a><?php endif; ?></div></nav>
<?php endif; ?>
<?php if($tab==='trace'): ?><h3 class="h6 mt-4">Movimentos de produto acabado</h3><p class="small text-secondary">Movimentos associados diretamente ao artigo. Sem referência comprovada à OF, não se infere a produção de origem.</p><div class="table-responsive"><table class="table"><thead><tr><th>Movimento</th><th>Data</th><th>Tipo</th><th>Lote</th><th>Quantidade</th></tr></thead><tbody><?php foreach($movements['rows']??[] as $m): ?><tr><td><?= h($m['movement_number']) ?></td><td><?= h(ap_date($m['movement_date'])) ?></td><td><?= h($m['movement_type']) ?></td><td><?= h($m['lot']?:'Não registado') ?></td><td><?= h(ap_quantity($m['quantity'],$article['unit'])) ?></td></tr><?php endforeach; ?><?php if(empty($movements['rows'])): ?><tr><td colspan="5">Sem movimentos de produto acabado registados.</td></tr><?php endif; ?></tbody></table></div><nav aria-label="Paginação dos movimentos" class="d-flex flex-wrap gap-2"><span class="small text-secondary"><?= (int)$movements['total'] ?> movimentos · página <?= (int)$movements['page'] ?> / <?= (int)$movements['pages'] ?></span><?php foreach(['Anterior'=>-1,'Seguinte'=>1] as $label=>$delta): $page=$movements['page']+$delta;if($page<1||$page>$movements['pages'])continue; ?><a class="btn btn-sm btn-outline-secondary" href="<?= h(ap_url($id,'trace',array_merge($filters,['mp'=>$page]))) ?>"><i class="bi <?= $delta<0?'bi-chevron-left':'bi-chevron-right' ?> me-1" aria-hidden="true"></i><?= h($label) ?></a><?php endforeach; ?></nav><p class="text-secondary">As unidades logísticas só podem ser relacionadas quando existir um identificador de palete ou unidade registado.</p><?php endif; ?>

<?php if($tab==='trace'&&$reverse): ?><h3 class="h6 mt-4">Rastreabilidade inversa da unidade de matéria-prima</h3><p class="small text-secondary">Produções ligadas ao mesmo identificador de rolo ou recipiente. Nomes de lotes iguais não são usados como chave.</p><ul><?php foreach(array_slice($reverse,0,200) as $record): ?><li><a href="production_dossier.php?id=<?= (int)$record['id'] ?>"><?= h($record['order_number']) ?></a> · <?php if($record['article_id']): ?><a href="<?= h(ap_url((int)$record['article_id'])) ?>"><?= h($record['code'].' — '.$record['description']) ?></a><?php else: ?>Artigo atual não associado<?php endif; ?></li><?php endforeach; ?></ul><?php if(count($reverse)>200): ?><p class="text-secondary">Resumo limitado a 200 OF.</p><?php endif; ?><?php endif; ?>
<?php if($tab==='trace'&&!empty($data['reservations_truncated'])): ?><p class="text-secondary">Resumo limitado a 200 reservas; consulte cada OF para os detalhes completos.</p><?php endif; ?>

<?php if($tab==='costs'&&!empty($data['cost_consumptions_truncated'])): ?><p class="text-secondary">Resumo limitado a 200 consumos. Abra cada OF para consultar todos os registos.</p><?php endif; ?>
