<?php
require_once __DIR__.'/IntegrationClient.php';require_once __DIR__.'/ResponseParser.php';require_once __DIR__.'/IntegrationSecurity.php';
class IntegrationRunner
{
 private $pdo; private $client; public function __construct(PDO $pdo){$this->pdo=$pdo;$this->client=new IntegrationClient($pdo);}
 public function run(int $flowId,bool $dryRun,int $user=0):array{
  $s=$this->pdo->prepare('SELECT f.*,i.base_url,i.auth_type,i.timeout,i.retries,i.retry_delay,i.verify_ssl,i.id AS integration_pk FROM integration_flows f JOIN integrations i ON i.id=f.integration_id WHERE f.id=?');$s->execute([$flowId]);$f=$s->fetch();if(!$f)throw new RuntimeException('Fluxo não encontrado.');
  $this->pdo->prepare('INSERT INTO integration_runs(integration_id,flow_id,operation,status,dry_run,executed_by)VALUES(?,?,?,?,?,?)')->execute([$f['integration_id'],$flowId,$f['http_method'],'running',$dryRun?1:0,$user?:null]);$run=(int)$this->pdo->lastInsertId();$start=microtime(true);
  try{$method=$dryRun&&$f['http_method']!=='GET'?'GET':$f['http_method'];$endpoint=$f['endpoint'];$i=$f;$i['id']=$f['integration_pk'];$res=$this->client->request($i,$method,$endpoint,null);$decoded=json_decode($res['body'],true);$items=is_array($decoded)?ResponseParser::path($decoded,(string)$f['response_items_path']):[];$count=is_array($items)?count($items):0;$ok=$res['ok']&&($decoded!==null||trim($res['body'])==='');$status=$ok?'success':'error';$error=$res['error']?:(!$res['ok']?'HTTP '.$res['status']:(json_last_error()?'JSON inválido':''));$duration=(int)((microtime(true)-$start)*1000);
   $this->pdo->prepare('UPDATE integration_runs SET status=?,records_read=?,records_sent=?,duration_ms=?,request_url=?,http_method=?,http_status=?,response=?,error_message=?,finished_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$status,$count,$dryRun?0:$count,$duration,IntegrationSecurity::redact($res['url']),$method,$res['status'],IntegrationSecurity::redact(substr($res['body'],0,20000)),IntegrationSecurity::redact($error),$run]);
   $next=self::nextDate($f['schedule']);$this->pdo->prepare('UPDATE integration_flows SET last_run_at=CURRENT_TIMESTAMP,last_success_at=CASE WHEN ?="success" THEN CURRENT_TIMESTAMP ELSE last_success_at END,next_run_at=?,last_duration_ms=?,last_result=?,dry_run_passed_at=CASE WHEN ?=1 AND ?="success" THEN CURRENT_TIMESTAMP ELSE dry_run_passed_at END WHERE id=?')->execute([$status,$next,$duration,$status,$dryRun?1:0,$status,$flowId]);return ['run_id'=>$run,'status'=>$status,'read'=>$count,'sent'=>$dryRun?0:$count,'errors'=>$ok?0:1,'duration'=>$duration,'message'=>$error];
  }catch(Throwable $e){$this->pdo->prepare('UPDATE integration_runs SET status="error",error_count=1,error_message=?,finished_at=CURRENT_TIMESTAMP WHERE id=?')->execute([IntegrationSecurity::redact($e->getMessage()),$run]);throw $e;}
 }
 public static function nextDate(string $s){$map=['5m'=>300,'15m'=>900,'30m'=>1800,'1h'=>3600,'2h'=>7200,'6h'=>21600,'daily'=>86400,'weekly'=>604800];return isset($map[$s])?date('Y-m-d H:i:s',time()+$map[$s]):null;}
 public function due():array{$q=$this->pdo->query('SELECT f.id FROM integration_flows f JOIN integrations i ON i.id=f.integration_id WHERE f.is_active=1 AND i.is_active=1 AND f.schedule<>"manual" AND (f.next_run_at IS NULL OR f.next_run_at<=CURRENT_TIMESTAMP)');$out=[];foreach($q as $r)$out[]=$this->run((int)$r['id'],false,0);return$out;}
}
