<?php
require_once dirname(__DIR__,2).'/integrations_migrations.php'; require_once __DIR__.'/IntegrationSecurity.php';
class IntegrationManager
{
 private $pdo; public function __construct(PDO $pdo){$this->pdo=$pdo;integrations_migrate($pdo);}
 public function saveIntegration(array $p,int $user): int {
  $url=trim((string)($p['base_url']??'')); if(!IntegrationSecurity::safeUrl($url))throw new InvalidArgumentException('URL inválido ou destino interno bloqueado.');
  $id=(int)($p['id']??0);$v=[trim($p['name']),preg_replace('/[^a-z0-9_-]/','',strtolower($p['slug'])),in_array($p['provider'],['generic','toconline'],true)?$p['provider']:'generic',$p['description']??'',isset($p['is_active'])?1:0,$p['environment']==='production'?'production':'sandbox',$url,max(1,(int)$p['timeout']),min(5,max(0,(int)$p['retries'])),max(0,(int)$p['retry_delay']),isset($p['verify_ssl'])?1:0,in_array($p['auth_type'],['none','api_key','bearer','basic','oauth2'],true)?$p['auth_type']:'none'];
  if($id){$this->pdo->prepare('UPDATE integrations SET name=?,slug=?,provider=?,description=?,is_active=?,environment=?,base_url=?,timeout=?,retries=?,retry_delay=?,verify_ssl=?,auth_type=?,status=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute(array_merge($v,[$v[4]?'on':'off',$user,$id]));}
  else {$this->pdo->prepare('INSERT INTO integrations(name,slug,provider,description,is_active,environment,base_url,timeout,retries,retry_delay,verify_ssl,auth_type,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute(array_merge($v,[$v[4]?'on':'off',$user,$user]));$id=(int)$this->pdo->lastInsertId();}
  $fields=['api_key_name','api_key_value','token','username','password','client_id','client_secret','authorization_url','token_url','refresh_url','redirect_uri','scope','access_token','refresh_token'];$q=$this->pdo->prepare('INSERT INTO integration_credentials(integration_id,key_name,value_encrypted) VALUES(?,?,?) ON CONFLICT(integration_id,key_name) DO UPDATE SET value_encrypted=excluded.value_encrypted'); foreach($fields as $f)if(trim((string)($p[$f]??''))!=='')$q->execute([$id,$f,IntegrationSecurity::encrypt(trim($p[$f]))]);
  $this->audit($user,$id?'integration.updated':'integration.created',['integration_id'=>$id]); return $id;
 }
 public function saveFlow(array $p,int $user): int {
  $method=in_array($p['http_method'],['GET','POST','PUT','PATCH','DELETE'],true)?$p['http_method']:'GET';$active=isset($p['is_active'])?1:0;$id=(int)($p['id']??0);if($active&&$method!=='GET'&&empty($p['dry_run_passed_at'])&&$id){$s=$this->pdo->prepare('SELECT dry_run_passed_at FROM integration_flows WHERE id=?');$s->execute([$id]);if(!$s->fetchColumn())throw new RuntimeException('Execute primeiro uma simulação com sucesso antes de ativar operações destrutivas.');}
  if(($p['payload_type']??'json')==='json'&&trim($p['payload_template']??'')!==''){json_decode($p['payload_template'],true);if(json_last_error())throw new InvalidArgumentException('Payload JSON inválido.');}
  $vals=[(int)$p['integration_id'],trim($p['name']),$p['description']??'',$active,trim($p['entity']),in_array($p['direction'],['import','export','read'],true)?$p['direction']:'read',$method,'/'.ltrim(trim($p['endpoint']),'/'),$p['schedule'],$p['payload_type'],$p['payload_template']??'',$p['response_items_path']??'',$p['remote_id_path']??'',$p['remote_code_path']??'',$p['pagination_type']??'none',$p['page_parameter']??'page',$p['limit_parameter']??'per_page',$p['next_path']??'',min(100,max(1,(int)($p['max_pages']??10))),min(1000,max(1,(int)($p['items_per_page']??100))),$p['unmatched_action']??'ignore',$user];
  if($id){$this->pdo->prepare('UPDATE integration_flows SET integration_id=?,name=?,description=?,is_active=?,entity=?,direction=?,http_method=?,endpoint=?,schedule=?,payload_type=?,payload_template=?,response_items_path=?,remote_id_path=?,remote_code_path=?,pagination_type=?,page_parameter=?,limit_parameter=?,next_path=?,max_pages=?,items_per_page=?,unmatched_action=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute(array_merge($vals,[$id]));}else{$this->pdo->prepare('INSERT INTO integration_flows(integration_id,name,description,is_active,entity,direction,http_method,endpoint,schedule,payload_type,payload_template,response_items_path,remote_id_path,remote_code_path,pagination_type,page_parameter,limit_parameter,next_path,max_pages,items_per_page,unmatched_action,created_by,updated_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute(array_merge($vals,[$user]));$id=(int)$this->pdo->lastInsertId();}return $id;
 }
 public function replaceMappings(int $flow,array $p):void{$this->pdo->prepare('DELETE FROM integration_field_mappings WHERE flow_id=?')->execute([$flow]);$q=$this->pdo->prepare('INSERT INTO integration_field_mappings(flow_id,local_field,remote_field,is_required,default_value,data_type,transformation)VALUES(?,?,?,?,?,?,?)');foreach(($p['local_field']??[])as $i=>$local)if(trim($local)!=='')$q->execute([$flow,trim($local),trim($p['remote_field'][$i]??''),isset($p['required'][$i])?1:0,$p['default_value'][$i]??'', $p['data_type'][$i]??'string',$p['transformation'][$i]??'none']);}
 public function audit(int $user,string $action,array $details):void{$this->pdo->prepare('INSERT INTO audit_logs(user_id,action,details_json)VALUES(?,?,?)')->execute([$user,$action,json_encode($details)]);}
}
