<?php
declare(strict_types=1);

final class RoutingService
{
    private PDO $pdo;
    public function __construct(PDO $pdo) { $this->pdo = $pdo; }

    public function saveOperation(array $data, array $machineIds, int $userId): int
    {
        $code=trim((string)($data['code']??'')); $name=trim((string)($data['name']??''));
        if($code===''||$name==='') throw new InvalidArgumentException('O código e o nome são obrigatórios.');
        $types=['production','control','transport','wait','subcontract','other'];
        $type=(string)($data['operation_type']??'production');
        if(!in_array($type,$types,true)) throw new InvalidArgumentException('Tipo de operação inválido.');
        $machineIds=array_values(array_unique(array_filter(array_map('intval',$machineIds))));
        $default=(int)($data['default_machine_id']??0);
        if($default && !in_array($default,$machineIds,true)) throw new InvalidArgumentException('A máquina predefinida tem de ser compatível.');
        $id=(int)($data['id']??0); $own=$id; $this->transaction(function() use(&$id,$own,$data,$code,$name,$type,$machineIds,$default,$userId){
            $values=[$code,$name,trim((string)($data['description']??'')),(int)($data['work_center_id']??0)?:null,$type,trim((string)($data['default_instructions']??'')),max(0,(float)($data['setup_minutes']??0)),max(0,(float)($data['time_per_unit']??0)),trim((string)($data['time_unit']??'minutes')),trim((string)($data['production_unit']??'unit')),max(1,(int)($data['min_operators']??1)),!empty($data['requires_good_quantity'])?1:0,!empty($data['requires_waste'])?1:0,!empty($data['requires_waste_reason'])?1:0,!empty($data['requires_quality'])?1:0,!empty($data['is_active'])?1:0,trim((string)($data['notes']??''))];
            if($own){$old=$this->one('SELECT * FROM erp_operations WHERE id=?',[$own]); if(!$old)throw new InvalidArgumentException('Operação inexistente.');$this->pdo->prepare('UPDATE erp_operations SET code=?,name=?,description=?,default_work_center_id=?,operation_type=?,default_instructions=?,setup_minutes=?,time_per_unit=?,time_unit=?,production_unit=?,min_operators=?,requires_good_quantity=?,requires_waste=?,requires_waste_reason=?,requires_quality=?,is_active=?,notes=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute(array_merge($values,[$userId,$own]));$id=$own;$this->audit($userId,'update','operation',$id,$old,$data);}
            else{$this->pdo->prepare('INSERT INTO erp_operations(code,name,description,default_work_center_id,operation_type,default_instructions,setup_minutes,time_per_unit,time_unit,production_unit,min_operators,requires_good_quantity,requires_waste,requires_waste_reason,requires_quality,is_active,notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute(array_merge($values,[$userId,$userId]));$id=(int)$this->pdo->lastInsertId();$this->audit($userId,'create','operation',$id,[],$data);}
            $this->pdo->prepare('DELETE FROM erp_operation_machines WHERE operation_id=?')->execute([$id]);$ins=$this->pdo->prepare('INSERT INTO erp_operation_machines(operation_id,machine_id,is_default) VALUES (?,?,?)');foreach($machineIds as $mid)$ins->execute([$id,$mid,$mid===$default?1:0]);
        }); return $id;
    }

    public function createVersion(int $articleId, int $userId, ?int $sourceVersionId=null): int
    {
        return $this->transaction(function() use($articleId,$userId,$sourceVersionId){
            $routing=$this->one('SELECT * FROM erp_article_routings WHERE finished_product_id=? ORDER BY id LIMIT 1',[$articleId]);
            if(!$routing){$this->pdo->prepare('INSERT INTO erp_article_routings(finished_product_id,created_by) VALUES (?,?)')->execute([$articleId,$userId]);$routing=['id'=>(int)$this->pdo->lastInsertId()];}
            $next=(int)$this->scalar('SELECT COALESCE(MAX(version_no),0)+1 FROM erp_article_routing_versions WHERE routing_id=?',[(int)$routing['id']]);
            $this->pdo->prepare('INSERT INTO erp_article_routing_versions(routing_id,version_no,based_on_version_id,created_by) VALUES (?,?,?,?)')->execute([(int)$routing['id'],$next,$sourceVersionId,$userId]);$id=(int)$this->pdo->lastInsertId();
            if($sourceVersionId){$steps=$this->all('SELECT * FROM erp_article_routing_steps WHERE routing_version_id=? ORDER BY sort_order',[$sourceVersionId]);$map=[];foreach($steps as $s){$old=(int)$s['id'];unset($s['id']);$s['routing_version_id']=$id;$cols=array_keys($s);$this->pdo->prepare('INSERT INTO erp_article_routing_steps('.implode(',',$cols).') VALUES('.implode(',',array_fill(0,count($cols),'?')).')')->execute(array_values($s));$map[$old]=(int)$this->pdo->lastInsertId();}$copy=$this->pdo->prepare('INSERT INTO erp_routing_step_machines(routing_step_id,machine_id) SELECT ?,machine_id FROM erp_routing_step_machines WHERE routing_step_id=?');foreach($map as $old=>$new)$copy->execute([$new,$old]);$dep=$this->pdo->prepare('SELECT routing_step_id,predecessor_step_id FROM erp_routing_step_dependencies WHERE routing_step_id=?');$ins=$this->pdo->prepare('INSERT INTO erp_routing_step_dependencies VALUES (?,?)');foreach($map as $old=>$new){$dep->execute([$old]);foreach($dep->fetchAll(PDO::FETCH_ASSOC) as $d)if(isset($map[(int)$d['predecessor_step_id']]))$ins->execute([$new,$map[(int)$d['predecessor_step_id']]]);}}
            $this->audit($userId,'create_version','routing_version',$id,[],['source'=>$sourceVersionId,'version'=>$next]);return $id;
        });
    }

    public function addStep(int $versionId,int $operationId,array $data,int $userId): int
    {
        $version=$this->editableVersion($versionId);$op=$this->one('SELECT * FROM erp_operations WHERE id=? AND is_active=1',[$operationId]);if(!$op)throw new InvalidArgumentException('Selecione uma operação ativa.');
        if($this->scalar('SELECT COUNT(*) FROM erp_article_routing_steps WHERE routing_version_id=? AND operation_id=?',[$versionId,$operationId])&&!isset($data['confirm_duplicate']))throw new InvalidArgumentException('A operação já existe. Confirme explicitamente a duplicação.');
        $compatible=array_map('intval',array_column($this->all('SELECT machine_id FROM erp_operation_machines WHERE operation_id=?',[$operationId]),'machine_id'));$primary=(int)($data['primary_machine_id']??0);if($primary&&!in_array($primary,$compatible,true))throw new InvalidArgumentException('A máquina não é compatível com a operação.');
        $sort=(int)$this->scalar('SELECT COALESCE(MAX(sort_order),0)+10 FROM erp_article_routing_steps WHERE routing_version_id=?',[$versionId]);$snapshot=json_encode($op,JSON_UNESCAPED_UNICODE);
        $this->pdo->prepare('INSERT INTO erp_article_routing_steps(routing_version_id,operation_id,operation_no,sort_order,work_center_id,primary_machine_id,operators_count,setup_time,run_value,calculation_unit,base_quantity,waste_percent,wait_minutes,transfer_minutes,parallel_allowed,specific_instructions,quality_points,confirmation_required,is_active,operation_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)')->execute([$versionId,$operationId,(int)($data['operation_no']??$sort),$sort,(int)($data['work_center_id']??$op['default_work_center_id'])?:null,$primary?:$this->scalar('SELECT machine_id FROM erp_operation_machines WHERE operation_id=? AND is_default=1',[$operationId])?:null,max(1,(int)($data['operators_count']??$op['min_operators'])),max(0,(float)($data['setup_time']??$op['setup_minutes'])),max(0,(float)($data['run_value']??$op['time_per_unit'])),(string)($data['calculation_unit']??'minutes_per_unit'),max(.000001,(float)($data['base_quantity']??1)),max(0,(float)($data['waste_percent']??0)),max(0,(float)($data['wait_minutes']??0)),max(0,(float)($data['transfer_minutes']??0)),!empty($data['parallel_allowed'])?1:0,trim((string)($data['specific_instructions']??$op['default_instructions'])),trim((string)($data['quality_points']??'')),isset($data['confirmation_required'])?(int)!empty($data['confirmation_required']):1,$snapshot]);$id=(int)$this->pdo->lastInsertId();$ins=$this->pdo->prepare('INSERT INTO erp_routing_step_machines VALUES (?,?)');foreach($compatible as $mid)$ins->execute([$id,$mid]);$this->audit($userId,'add_step','routing_step',$id,[],['version_id'=>$versionId,'operation_id'=>$operationId]);return $id;
    }

    public function moveStep(int $stepId,string $direction,int $userId): void { $s=$this->one('SELECT * FROM erp_article_routing_steps WHERE id=?',[$stepId]);if(!$s)throw new InvalidArgumentException('Etapa inválida.');$this->editableVersion((int)$s['routing_version_id']);$cmp=$direction==='up'?'<':'>';$ord=$direction==='up'?'DESC':'ASC';$other=$this->one("SELECT * FROM erp_article_routing_steps WHERE routing_version_id=? AND sort_order $cmp ? ORDER BY sort_order $ord LIMIT 1",[(int)$s['routing_version_id'],(int)$s['sort_order']]);if($other){$this->transaction(function()use($s,$other){$this->pdo->prepare('UPDATE erp_article_routing_steps SET sort_order=-1 WHERE id=?')->execute([(int)$s['id']]);$this->pdo->prepare('UPDATE erp_article_routing_steps SET sort_order=? WHERE id=?')->execute([(int)$s['sort_order'],(int)$other['id']]);$this->pdo->prepare('UPDATE erp_article_routing_steps SET sort_order=? WHERE id=?')->execute([(int)$other['sort_order'],(int)$s['id']]);});$this->audit($userId,'reorder','routing_step',$stepId,[],['direction'=>$direction]);}}

    public function activateVersion(int $versionId,string $effectiveFrom,int $userId): void
    { $v=$this->editableVersion($versionId);$steps=$this->all('SELECT s.*,o.is_active operation_active FROM erp_article_routing_steps s JOIN erp_operations o ON o.id=s.operation_id WHERE s.routing_version_id=? ORDER BY s.sort_order',[$versionId]);if(!$steps)throw new InvalidArgumentException('Não é possível ativar um routing vazio.');foreach($steps as $s){if(!(int)$s['operation_active'])throw new InvalidArgumentException('O routing contém operações inativas.');if((int)$s['primary_machine_id']&&!$this->scalar('SELECT 1 FROM erp_routing_step_machines WHERE routing_step_id=? AND machine_id=?',[(int)$s['id'],(int)$s['primary_machine_id']]))throw new InvalidArgumentException('Existe uma máquina principal incompatível.');}$this->assertAcyclic($versionId);$this->transaction(function()use($v,$versionId,$effectiveFrom,$userId){$this->pdo->prepare('UPDATE erp_article_routing_versions SET status="archived" WHERE routing_id=? AND status="active"')->execute([(int)$v['routing_id']]);$this->pdo->prepare('UPDATE erp_article_routing_versions SET status="active",effective_from=?,activated_by=?,activated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$effectiveFrom?:date('Y-m-d'),$userId,$versionId]);$this->audit($userId,'activate','routing_version',$versionId,$v,['effective_from'=>$effectiveFrom]);}); }

    public function snapshotForOrder(int $orderId,int $articleId,float $quantity,int $userId,bool $override=false,string $reason=''): int
    { $v=$this->one('SELECT v.* FROM erp_article_routing_versions v JOIN erp_article_routings r ON r.id=v.routing_id WHERE r.finished_product_id=? AND v.status="active" AND (v.effective_from IS NULL OR v.effective_from<=date("now")) ORDER BY v.effective_from DESC,v.version_no DESC LIMIT 1',[$articleId]);if(!$v){if(!$override)throw new DomainException('O artigo não tem um routing ativo; a OF não pode ser libertada.');if(trim($reason)==='')throw new DomainException('A libertação administrativa sem routing exige um motivo.');$this->audit($userId,'release_without_routing','production_order',$orderId,[],[],$reason);return 0;}$steps=$this->all('SELECT s.*,o.code operation_code,o.name operation_name FROM erp_article_routing_steps s JOIN erp_operations o ON o.id=s.operation_id WHERE s.routing_version_id=? AND s.is_active=1 ORDER BY s.sort_order',[(int)$v['id']]);$total=0;foreach($steps as &$s){$s['planned_minutes']=$this->plannedMinutes($s,$quantity);$total+=$s['planned_minutes'];}$json=json_encode(['version'=>$v,'steps'=>$steps],JSON_UNESCAPED_UNICODE);return $this->transaction(function()use($orderId,$v,$steps,$total,$json,$userId){$this->pdo->prepare('INSERT INTO erp_production_order_routing_snapshots(production_order_id,source_routing_version_id,version_no,effective_from,snapshot_json,total_planned_minutes,created_by) VALUES (?,?,?,?,?,?,?)')->execute([$orderId,(int)$v['id'],(int)$v['version_no'],$v['effective_from'],$json,$total,$userId]);$snapshotId=(int)$this->pdo->lastInsertId();$insert=$this->pdo->prepare('INSERT INTO erp_production_order_operations(production_order_id,operation_id,sequence_no,planned_minutes,routing_step_id,operation_code,operation_name,work_center_id,primary_machine_id,allowed_machine_ids_json,operators_count,setup_minutes,run_value,calculation_unit,base_quantity,waste_percent,wait_minutes,transfer_minutes,parallel_allowed,instructions,quality_points,confirmation_required,snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');foreach($steps as $s){$machines=array_column($this->all('SELECT machine_id FROM erp_routing_step_machines WHERE routing_step_id=?',[(int)$s['id']]),'machine_id');$insert->execute([$orderId,(int)$s['operation_id'],(int)$s['sort_order'],$s['planned_minutes'],(int)$s['id'],$s['operation_code'],$s['operation_name'],$s['work_center_id'],$s['primary_machine_id'],json_encode($machines),$s['operators_count'],$s['setup_time'],$s['run_value'],$s['calculation_unit'],$s['base_quantity'],$s['waste_percent'],$s['wait_minutes'],$s['transfer_minutes'],$s['parallel_allowed'],$s['specific_instructions'],$s['quality_points'],$s['confirmation_required'],json_encode($s,JSON_UNESCAPED_UNICODE)]);} $this->audit($userId,'snapshot','production_order',$orderId,[],['routing_version_id'=>$v['id'],'planned_minutes'=>$total]);return $snapshotId;}); }

    public function plannedMinutes(array $s,float $qty): float { $qty*=(1+(float)$s['waste_percent']/100);$run=(float)$s['run_value'];$base=max(.000001,(float)$s['base_quantity']);switch($s['calculation_unit']){case'seconds_per_unit':$minutes=$qty*$run/$base/60;break;case'units_per_hour':$minutes=$run>0?$qty/$run*60:0;break;case'meters_per_minute':$minutes=$run>0?$qty/$run:0;break;default:$minutes=$qty*$run/$base;}return round((float)$s['setup_time']+$minutes+(float)$s['wait_minutes']+(float)$s['transfer_minutes'],3);}
    private function assertAcyclic(int $versionId):void{$rows=$this->all('SELECT d.routing_step_id,d.predecessor_step_id FROM erp_routing_step_dependencies d JOIN erp_article_routing_steps s ON s.id=d.routing_step_id WHERE s.routing_version_id=?',[$versionId]);$g=[];foreach($rows as$r)$g[(int)$r['routing_step_id']][]=(int)$r['predecessor_step_id'];$visit=function($n,$trail=[])use(&$visit,$g){if(isset($trail[$n]))throw new InvalidArgumentException('O routing contém dependências circulares.');$trail[$n]=1;foreach($g[$n]??[]as$p)$visit($p,$trail);};foreach(array_keys($g)as$n)$visit($n);}
    private function editableVersion(int$id):array{$v=$this->one('SELECT * FROM erp_article_routing_versions WHERE id=?',[$id]);if(!$v)throw new InvalidArgumentException('Versão inválida.');if($v['status']!=='draft')throw new DomainException('Apenas versões em rascunho podem ser alteradas.');return$v;}
    private function audit(int$u,string$a,string$e,int$id,array$b,array$n,string$r=''):void{$this->pdo->prepare('INSERT INTO erp_routing_audit(user_id,action,entity_type,entity_id,before_json,after_json,reason) VALUES (?,?,?,?,?,?,?)')->execute([$u,$a,$e,$id,json_encode($b,JSON_UNESCAPED_UNICODE),json_encode($n,JSON_UNESCAPED_UNICODE),$r]);}
    private function transaction(callable$f){$own=!$this->pdo->inTransaction();if($own)$this->pdo->beginTransaction();try{$r=$f();if($own)$this->pdo->commit();return$r;}catch(Throwable$e){if($own&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    private function one(string$q,array$p=[]):?array{$s=$this->pdo->prepare($q);$s->execute($p);$r=$s->fetch(PDO::FETCH_ASSOC);return$r?:null;}private function all(string$q,array$p=[]):array{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC);}private function scalar(string$q,array$p=[]){$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchColumn();}
}
