<?php
if (defined('GESTISSER_COMPANY_MAPPER_MIGRATIONS_LOADED')) { return; }
define('GESTISSER_COMPANY_MAPPER_MIGRATIONS_LOADED', true);
define('COMPANY_MAPPER_SCHEMA_VERSION', 1);

function company_mapper_table_exists(PDO $pdo, $table) { $s=$pdo->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1"); $s->execute(array($table)); return (bool)$s->fetchColumn(); }
function company_mapper_column_exists(PDO $pdo, $table, $column) { foreach ($pdo->query('PRAGMA table_info(' . $table . ')')->fetchAll(PDO::FETCH_ASSOC) as $r) { if ($r['name']===$column) return true; } return false; }
function company_mapper_index_exists(PDO $pdo, $table, $index) { foreach ($pdo->query('PRAGMA index_list(' . $table . ')')->fetchAll(PDO::FETCH_ASSOC) as $r) { if ($r['name']===$index) return true; } return false; }
function company_mapper_exec(PDO $pdo, $sql) { $pdo->exec($sql); }
function company_mapper_add_column(PDO $pdo, $table, $column, $definition) { if (!company_mapper_column_exists($pdo,$table,$column)) { company_mapper_exec($pdo, 'ALTER TABLE '.$table.' ADD COLUMN '.$column.' '.$definition); } }
function company_mapper_backup_database_once(PDO $pdo) { static $p=null; if ($p!==null) return $p; $db=__DIR__.'/database.sqlite'; foreach ($pdo->query('PRAGMA database_list')->fetchAll(PDO::FETCH_ASSOC) as $row) { if ($row['name']==='main' && !empty($row['file'])) { $db=$row['file']; } } if (!is_file($db)) return null; $dir=dirname($db).'/backups'; if (!is_dir($dir)) { @mkdir($dir,0775,true); } $p=$dir.'/company_mapper_'.date('Ymd_His').'.sqlite'; if (!@copy($db,$p)) { throw new RuntimeException('Falha ao criar backup Company Mapper.'); } return $p; }
function company_mapper_get_version(PDO $pdo) { if (!company_mapper_table_exists($pdo,'app_settings')) return 0; $s=$pdo->prepare('SELECT setting_value FROM app_settings WHERE setting_key=? LIMIT 1'); $s->execute(array('company_mapper_schema_version')); $v=$s->fetchColumn(); return $v===false?0:(int)$v; }
function company_mapper_set_version(PDO $pdo, $version) { $u=$pdo->prepare('UPDATE app_settings SET setting_value=? WHERE setting_key=?'); $u->execute(array((string)$version,'company_mapper_schema_version')); if ($u->rowCount()===0) { $i=$pdo->prepare('INSERT INTO app_settings(setting_key,setting_value) VALUES (?,?)'); $i->execute(array('company_mapper_schema_version',(string)$version)); } }

function company_mapper_run_migrations(PDO $pdo) {
    $pdo->exec('PRAGMA foreign_keys = ON');
    if (company_mapper_get_version($pdo) >= COMPANY_MAPPER_SCHEMA_VERSION) return;
    company_mapper_backup_database_once($pdo);
    $pdo->beginTransaction();
    try {
        $pdo->exec('CREATE TABLE IF NOT EXISTS app_settings (setting_key TEXT PRIMARY KEY, setting_value TEXT, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)');
        company_mapper_add_column($pdo,'users','manager_user_id','INTEGER NULL'); company_mapper_add_column($pdo,'users','capacity_percent','INTEGER NOT NULL DEFAULT 100'); company_mapper_add_column($pdo,'users','org_sort_order','INTEGER NOT NULL DEFAULT 0');
        foreach (array('idx_users_manager_user_id'=>'users(manager_user_id)','idx_users_department_schedule'=>'users(department, schedule_id)','idx_users_org_sort'=>'users(org_sort_order, name)') as $n=>$cols) if (!company_mapper_index_exists($pdo,'users',$n)) $pdo->exec('CREATE INDEX IF NOT EXISTS '.$n.' ON '.$cols);
        foreach (array('code'=>'TEXT NULL','color'=>'TEXT NOT NULL DEFAULT "#2D69A1"','description'=>'TEXT NULL','manager_user_id'=>'INTEGER NULL','is_active'=>'INTEGER NOT NULL DEFAULT 1','sort_order'=>'INTEGER NOT NULL DEFAULT 0','updated_at'=>'DATETIME NULL') as $c=>$d) company_mapper_add_column($pdo,'hr_departments',$c,$d);
        $pdo->exec('CREATE INDEX IF NOT EXISTS idx_hr_departments_mapper ON hr_departments(is_active, sort_order, name)');
        foreach (array('code'=>'TEXT NULL','color'=>'TEXT NOT NULL DEFAULT "#2D69A1"','is_active'=>'INTEGER NOT NULL DEFAULT 1','notes'=>'TEXT NULL','updated_at'=>'DATETIME NULL') as $c=>$d) company_mapper_add_column($pdo,'hr_schedules',$c,$d);
        $pdo->exec('CREATE INDEX IF NOT EXISTS idx_hr_schedules_mapper ON hr_schedules(is_active, name)');
        foreach (array('description'=>'TEXT NULL','owner_user_id'=>'INTEGER NULL','department_id'=>'INTEGER NULL','all_day'=>'INTEGER NOT NULL DEFAULT 1','status'=>'TEXT NOT NULL DEFAULT "active"','updated_at'=>'DATETIME NULL') as $c=>$d) company_mapper_add_column($pdo,'hr_calendar_events',$c,$d);
        $pdo->exec('CREATE INDEX IF NOT EXISTS idx_hr_calendar_events_mapper ON hr_calendar_events(start_date, end_date, status, department_id)');
        foreach (array('department_id'=>'INTEGER NULL','location'=>'TEXT NULL','description'=>'TEXT NULL','sort_order'=>'INTEGER NOT NULL DEFAULT 0','updated_at'=>'DATETIME NULL') as $c=>$d) company_mapper_add_column($pdo,'erp_work_centers',$c,$d);
        $pdo->exec('CREATE INDEX IF NOT EXISTS idx_erp_work_centers_mapper ON erp_work_centers(department_id, sort_order, name)');
        $tables = array(
"CREATE TABLE IF NOT EXISTS erp_machines (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, brand TEXT NULL, model TEXT NULL, serial_number TEXT NULL, manufacturing_year INTEGER NULL, department_id INTEGER NULL, work_center_id INTEGER NULL, location TEXT NULL, owner_user_id INTEGER NULL, status TEXT NOT NULL DEFAULT 'operational' CHECK(status IN ('operational','limited','maintenance','stopped','inactive')), criticality TEXT NOT NULL DEFAULT 'medium' CHECK(criticality IN ('high','medium','low')), nominal_capacity TEXT NULL, cycle_time TEXT NULL, operators_required INTEGER NOT NULL DEFAULT 1, supplier_id INTEGER NULL, service_provider TEXT NULL, purchase_date TEXT NULL, next_maintenance_date TEXT NULL, manual_url TEXT NULL, notes TEXT NULL, is_active INTEGER NOT NULL DEFAULT 1, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(department_id) REFERENCES hr_departments(id) ON DELETE SET NULL, FOREIGN KEY(work_center_id) REFERENCES erp_work_centers(id) ON DELETE SET NULL, FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(supplier_id) REFERENCES erp_suppliers(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS hr_machine_competencies (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, machine_id INTEGER NOT NULL, level INTEGER NOT NULL DEFAULT 0 CHECK(level BETWEEN 0 AND 4), assessed_at TEXT NULL, expiry_date TEXT NULL, assessed_by_user_id INTEGER NULL, notes TEXT NULL, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, machine_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(machine_id) REFERENCES erp_machines(id) ON DELETE CASCADE, FOREIGN KEY(assessed_by_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_duty_sheets (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, department_id INTEGER NULL, responsible_user_id INTEGER NULL, backup_user_id INTEGER NULL, secondary_backup_user_id INTEGER NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','validated','review','inactive')), review_date TEXT NULL, purpose TEXT NULL, responsibilities TEXT NULL, daily_tasks TEXT NULL, periodic_tasks TEXT NULL, authority_text TEXT NULL, kpis TEXT NULL, systems_text TEXT NULL, absence_instructions TEXT NULL, documents_text TEXT NULL, notes TEXT NULL, version_no INTEGER NOT NULL DEFAULT 1, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(department_id) REFERENCES hr_departments(id) ON DELETE SET NULL, FOREIGN KEY(responsible_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(backup_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(secondary_backup_user_id) REFERENCES users(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_duty_sheet_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, duty_sheet_id INTEGER NOT NULL, version_no INTEGER NOT NULL, snapshot_json TEXT NOT NULL, change_reason TEXT NULL, changed_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(duty_sheet_id, version_no), FOREIGN KEY(duty_sheet_id) REFERENCES company_duty_sheets(id) ON DELETE CASCADE, FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_systems (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, category TEXT, supplier_id INTEGER NULL, supplier_name TEXT, owner_user_id INTEGER NULL, user_count INTEGER NOT NULL DEFAULT 0, billing_period TEXT NOT NULL DEFAULT 'none' CHECK(billing_period IN ('monthly','annual','one_time','none')), cost_ex_vat REAL NOT NULL DEFAULT 0, renewal_date TEXT, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','review','risk','inactive')), url TEXT, notes TEXT, is_active INTEGER NOT NULL DEFAULT 1, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(supplier_id) REFERENCES erp_suppliers(id) ON DELETE SET NULL, FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_process_flows (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE, name TEXT NOT NULL, description TEXT, owner_user_id INTEGER NULL, department_id INTEGER NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','hypothesis','validated','archived')), version_label TEXT, is_active INTEGER NOT NULL DEFAULT 1, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(department_id) REFERENCES hr_departments(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_process_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, flow_id INTEGER NOT NULL, node_key TEXT NOT NULL, label TEXT NOT NULL, node_type TEXT NOT NULL DEFAULT 'operation' CHECK(node_type IN ('operation','decision','control','external')), owner_user_id INTEGER NULL, department_id INTEGER NULL, x_position REAL NOT NULL DEFAULT 0, y_position REAL NOT NULL DEFAULT 0, duration_text TEXT, system_id INTEGER NULL, system_label TEXT, kpi TEXT, notes TEXT, sort_order INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(flow_id, node_key), FOREIGN KEY(flow_id) REFERENCES company_process_flows(id) ON DELETE CASCADE, FOREIGN KEY(system_id) REFERENCES company_systems(id) ON DELETE SET NULL)",
"CREATE TABLE IF NOT EXISTS company_process_edges (id INTEGER PRIMARY KEY AUTOINCREMENT, flow_id INTEGER NOT NULL, edge_key TEXT NOT NULL, from_node_id INTEGER NOT NULL, to_node_id INTEGER NOT NULL, label TEXT, sort_order INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(flow_id, edge_key), CHECK(from_node_id <> to_node_id), FOREIGN KEY(flow_id) REFERENCES company_process_flows(id) ON DELETE CASCADE, FOREIGN KEY(from_node_id) REFERENCES company_process_nodes(id) ON DELETE CASCADE, FOREIGN KEY(to_node_id) REFERENCES company_process_nodes(id) ON DELETE CASCADE)",
"CREATE TABLE IF NOT EXISTS company_improvements (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, area TEXT NOT NULL DEFAULT 'other' CHECK(area IN ('production','process','supplier','technology','people','quality','other')), description TEXT, priority TEXT NOT NULL DEFAULT 'medium' CHECK(priority IN ('critical','high','medium','low')), impact TEXT, effort TEXT, status TEXT NOT NULL DEFAULT 'identified' CHECK(status IN ('identified','analysis','planned','in_progress','blocked','implemented','measured','cancelled')), owner_user_id INTEGER NULL, supplier_id INTEGER NULL, supplier_name TEXT, process_flow_id INTEGER NULL, machine_id INTEGER NULL, system_id INTEGER NULL, project_id INTEGER NULL, task_id INTEGER NULL, due_date TEXT, expected_benefit TEXT, evidence TEXT, created_by INTEGER NULL, updated_by INTEGER NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(supplier_id) REFERENCES erp_suppliers(id) ON DELETE SET NULL, FOREIGN KEY(process_flow_id) REFERENCES company_process_flows(id) ON DELETE SET NULL, FOREIGN KEY(machine_id) REFERENCES erp_machines(id) ON DELETE SET NULL, FOREIGN KEY(system_id) REFERENCES company_systems(id) ON DELETE SET NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE SET NULL)"
        ); foreach($tables as $sql) $pdo->exec($sql);
        foreach (array('idx_erp_machines_code ON erp_machines(code)','idx_erp_machines_status ON erp_machines(status)','idx_erp_machines_department ON erp_machines(department_id)','idx_erp_machines_work_center ON erp_machines(work_center_id)','idx_erp_machines_owner ON erp_machines(owner_user_id)','idx_erp_machines_supplier ON erp_machines(supplier_id)','idx_erp_machines_criticality ON erp_machines(criticality)','idx_erp_machines_next_maintenance ON erp_machines(next_maintenance_date)','idx_hr_machine_competencies_user ON hr_machine_competencies(user_id)','idx_company_duty_sheets_status ON company_duty_sheets(status)','idx_company_systems_status ON company_systems(status)','idx_company_process_flows_status ON company_process_flows(status)','idx_company_process_nodes_flow ON company_process_nodes(flow_id, sort_order)','idx_company_process_edges_flow ON company_process_edges(flow_id, sort_order)','idx_company_improvements_status ON company_improvements(status)','idx_company_improvements_links ON company_improvements(process_flow_id, machine_id, system_id)') as $idx) $pdo->exec('CREATE INDEX IF NOT EXISTS '.$idx);
        $p=$pdo->prepare('INSERT OR IGNORE INTO erp_permissions(code,label,description) VALUES (?,?,?)'); foreach (array('mapper.view'=>'Ver Mapper','mapper.org.manage'=>'Gerir organograma','mapper.duties.manage'=>'Gerir cadernos de funções','mapper.flows.manage'=>'Gerir fluxos','mapper.calendar.manage'=>'Gerir calendário Mapper','mapper.systems.manage'=>'Gerir sistemas','mapper.machines.manage'=>'Gerir máquinas','mapper.competencies.manage'=>'Gerir competências','mapper.improvements.manage'=>'Gerir melhorias') as $c=>$l) $p->execute(array($c,$l,$l));
        company_mapper_set_version($pdo, COMPANY_MAPPER_SCHEMA_VERSION); $pdo->commit();
    } catch (Exception $e) { if ($pdo->inTransaction()) $pdo->rollBack(); throw $e; }
}
