<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/crm_migrations.php';
require_once __DIR__.'/app/Services/CrmService.php';
require_login();
erp_run_phase1_migrations($pdo); crm_run_migrations($pdo);
$user=current_user($pdo)?:[];$crm=new CrmService($pdo,$user);
if((int)($user['crm_enabled']??1)!==1||(int)($user['pin_only_login']??0)===1||!$crm->canView()){http_response_code(403);exit('O módulo de CRM não está ativo para este utilizador.');}
$view=(string)($_GET['view']??'dashboard');$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&validate_csrf_or_abort(false)){
 try{$action=(string)($_POST['action']??'');if($action==='save_lead'){$id=$crm->saveLead($_POST);header('Location: crm.php?view=leads&created='.$id);exit;}if($action==='save_activity'){$crm->saveActivity($_POST);$notice='Atividade criada.';}if($action==='complete_activity'){$pdo->prepare('UPDATE crm_activities SET status="COMPLETED",completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND (assigned_to=? OR ?=1)')->execute([(int)$_POST['id'],(int)$user['id'],$crm->isAdmin()?1:0]);$notice='Atividade concluída.';}if($action==='move_opportunity'){$crm->moveOpportunity((int)$_POST['id'],(string)$_POST['stage']);if(($_SERVER['HTTP_ACCEPT']??'')==='application/json'){header('Content-Type: application/json');echo json_encode(['ok'=>true]);exit;}$notice='Pipeline atualizado.';}}
 catch(Throwable $e){$error=$e->getMessage();if(($_SERVER['HTTP_ACCEPT']??'')==='application/json'){http_response_code(422);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>$error]);exit;}}
}
$dashboard=$crm->dashboard();$leads=$crm->leads();$activities=$crm->activities();
$opportunities=$pdo->query('SELECT o.*,COALESCE(c.name,o.company) company_name,u.name assigned_name,(SELECT MIN(due_datetime) FROM crm_activities a WHERE a.related_type="opportunity" AND a.related_id=o.id AND a.status="PENDING") next_activity FROM crm_opportunities o LEFT JOIN erp_customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.assigned_to ORDER BY o.updated_at DESC')->fetchAll();
$customers=$pdo->query('SELECT c.*,COUNT(DISTINCT po.id) order_count,MAX(po.created_at) last_order,COALESCE(SUM(po.planned_quantity*COALESCE(fp.sale_price,0)),0) commercial_value FROM erp_customers c LEFT JOIN erp_production_orders po ON po.customer_id=c.id LEFT JOIN erp_finished_products fp ON fp.id=po.finished_product_id GROUP BY c.id ORDER BY c.name')->fetchAll();
$users=$pdo->query('SELECT id,name FROM users WHERE is_active=1 ORDER BY name')->fetchAll();
$pageTitle='CRM · '.(['dashboard'=>'Dashboard','day'=>'Meu Dia','leads'=>'Leads','pipeline'=>'Pipeline','customers'=>'Clientes 360º','contacts'=>'Contactos','projects'=>'Projetos','activities'=>'Atividades','agenda'=>'Agenda','tasks'=>'Tarefas','reports'=>'Relatórios','settings'=>'Configurações'][$view]??'Comercial');$bodyClass='bg-light crm-page';require __DIR__.'/partials/header.php';
$money=function($v){return number_format((float)$v,0,',','.').' €';};
?>
<link href="assets/crm.css?v=<?=h((string)(@filemtime(__DIR__.'/assets/crm.css')?:'1'))?>" rel="stylesheet">
<div class="crm-shell">
<?php if($notice):?><div class="alert alert-success"><?=h($notice)?></div><?php endif;if($error):?><div class="alert alert-danger"><?=h($error)?></div><?php endif;?>
<header class="crm-hero"><div><span class="crm-eyebrow"><i class="bi bi-stars"></i> Centro comercial</span><h2><?=h(str_replace('CRM · ','',$pageTitle))?></h2><p>Relações, vendas e dados reais do ERP num único espaço.</p></div><div class="crm-hero-actions"><button class="btn btn-light" data-bs-toggle="modal" data-bs-target="#activityModal"><i class="bi bi-plus-circle"></i> Atividade</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#leadModal"><i class="bi bi-person-plus"></i> Novo lead</button></div></header>
<?php if($view==='dashboard'): $d=$dashboard;?>
<section class="crm-kpis">
<?php foreach([
 ['Leads ativos',$d['leads']['active'],'bi-person-lines-fill','leads'],['Novos este mês',$d['leads']['new_month'],'bi-sparkles','leads&filter=new'],['Oportunidades abertas',$d['opportunities']['open_count'],'bi-bullseye','pipeline'],['Pipeline total',$money($d['opportunities']['pipeline']),'bi-bar-chart-steps','pipeline'],['Pipeline ponderado',$money($d['opportunities']['weighted']),'bi-graph-up-arrow','pipeline'],['Negócios ganhos',$d['opportunities']['won'],'bi-trophy','pipeline&filter=won'],['Negócios perdidos',$d['opportunities']['lost'],'bi-x-circle','pipeline&filter=lost'],['Taxa conversão',(($d['opportunities']['won']+$d['opportunities']['lost'])?number_format($d['opportunities']['won']*100/($d['opportunities']['won']+$d['opportunities']['lost']),1,',','.'):0).'%','bi-percent','reports'],['Tarefas pendentes',$d['activities']['pending'],'bi-check2-square','tasks'],['Atividades atrasadas',$d['activities']['overdue'],'bi-alarm','day'],['Clientes ativos',$d['customers'],'bi-buildings','customers'],['Leads esquecidos',$d['leads']['stale'],'bi-exclamation-triangle','leads&filter=stale']
 ] as $k):?><a class="crm-kpi" href="crm.php?view=<?=$k[3]?>"><i class="bi <?=$k[2]?>"></i><strong><?=$k[1]?></strong><b><?=h((string)$k[0])?></b><span>Explorar <i class="bi bi-arrow-right"></i></span></a><?php endforeach;?>
</section>
<div class="crm-grid"><section class="crm-panel"><header><div><small>AGENDA COMERCIAL</small><h3>O que precisa da sua atenção</h3></div><a href="crm.php?view=day">Ver Meu Dia</a></header><?php foreach(array_slice($activities,0,6) as $a):?><div class="crm-agenda-row <?=empty($a['completed_at'])&&$a['due_datetime']<date('Y-m-d H:i:s')?'is-overdue':''?>"><time><?=h($a['due_datetime']?date('H:i',strtotime($a['due_datetime'])):'—')?></time><i class="bi bi-<?=($a['type']==='CALL'?'telephone':($a['type']==='MEETING'?'people':'check2-circle'))?>"></i><div><strong><?=h($a['title'])?></strong><small><?=h($a['type'])?> · <?=h((string)$a['due_datetime'])?></small></div></div><?php endforeach;if(!$activities):?><div class="crm-empty">Sem atividades. Crie o primeiro contacto comercial.</div><?php endif;?></section><section class="crm-panel"><header><div><small>FORECAST</small><h3>Previsão ponderada</h3></div></header><div class="crm-forecast"><div><span>Este mês</span><b><?=$money($d['opportunities']['weighted'])?></b></div><div class="crm-donut" style="--value:<?=min(100,(int)($d['opportunities']['pipeline']?($d['opportunities']['weighted']/$d['opportunities']['pipeline']*100):0))?>"><span><?=($d['opportunities']['pipeline']?round($d['opportunities']['weighted']/$d['opportunities']['pipeline']*100):0)?>%</span></div></div><p class="text-muted small">Calculado de forma transparente: valor estimado × probabilidade.</p></section></div>
<?php elseif(in_array($view,['day','activities','agenda','tasks'],true)):?>
<section class="crm-panel"><header><div><small>ATRASADO · HOJE · PRÓXIMOS</small><h3>Meu Dia</h3></div><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#activityModal">Nova atividade</button></header><?php $last='';foreach($activities as $a):$ts=$a['due_datetime']?strtotime($a['due_datetime']):null;$group=$a['completed_at']?'CONCLUÍDO':(!$ts?'SEM DATA':($ts<time()?'ATRASADO':(date('Y-m-d',$ts)===date('Y-m-d')?'HOJE':(date('Y-m-d',$ts)===date('Y-m-d',strtotime('+1 day'))?'AMANHÃ':'ESTA SEMANA'))));if($group!==$last):?><h4 class="crm-group-title"><?=h($group)?></h4><?php $last=$group;endif;?><article class="crm-task"><time><?=h($ts?date('d/m H:i',$ts):'—')?></time><span class="crm-type"><?=h($a['type'])?></span><div><strong><?=h($a['title'])?></strong><p><?=h((string)$a['description'])?></p></div><?php if(!$a['completed_at']):?><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="complete_activity"><input type="hidden" name="id" value="<?=$a['id']?>"><button class="btn btn-sm btn-outline-success"><i class="bi bi-check2"></i> Concluir</button></form><?php endif;?></article><?php endforeach;?></section>
<?php elseif($view==='leads'):?>
<section class="crm-panel"><header><div><small>PROSPEÇÃO</small><h3><?=count($leads)?> leads acessíveis</h3></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#leadModal">Novo lead</button></header><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Empresa / contacto</th><th>Estado</th><th>Prioridade</th><th>Potencial</th><th>Responsável</th><th>Última interação</th></tr></thead><tbody><?php foreach($leads as $l):?><tr><td><strong><?=h($l['company'])?></strong><small class="d-block text-muted"><?=h($l['contact_name'].' · '.$l['email'])?></small></td><td><span class="crm-pill"><?=h($l['status'])?></span></td><td><?=h($l['priority'])?></td><td><?=$money($l['estimated_value'])?> · <?=$l['probability']?>%</td><td><?=h($l['assigned_name'])?></td><td><?=h((string)($l['last_activity_at']?:$l['created_at']))?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php elseif($view==='pipeline'):?>
<div class="crm-kanban" data-crm-kanban><?php foreach(['NEW'=>'Novo','CONTACTED'=>'Contactado','QUALIFIED'=>'Qualificado','PROPOSAL'=>'Proposta','NEGOTIATION'=>'Negociação','WON'=>'Ganho','LOST'=>'Perdido'] as $stage=>$label):?><section class="crm-column" data-stage="<?=$stage?>"><header><span><?=$label?></span><b><?=count(array_filter($opportunities,function($o)use($stage){return $o['stage']===$stage;}))?></b></header><div class="crm-dropzone"><?php foreach($opportunities as $o):if($o['stage']!==$stage)continue;?><article class="crm-deal" draggable="true" data-id="<?=$o['id']?>"><small><?=h($o['company_name'])?></small><h4><?=h($o['title'])?></h4><strong><?=$money($o['estimated_value'])?></strong><div class="progress"><span style="width:<?=$o['probability']?>%"></span></div><footer><span><?=$o['probability']?>%</span><span><i class="bi bi-person"></i> <?=h($o['assigned_name'])?></span></footer></article><?php endforeach;?></div></section><?php endforeach;?></div>
<?php elseif($view==='customers'):?>
<section class="crm-panel"><header><div><small>ERP + CRM</small><h3>Clientes 360º</h3></div></header><div class="crm-customer-grid"><?php foreach($customers as $c):?><a class="crm-customer" href="crm.php?view=customer&id=<?=$c['id']?>"><span class="crm-avatar"><?=h(strtoupper(substr($c['name'],0,2)))?></span><div><h4><?=h($c['name'])?></h4><p><?=h($c['city'].' · '.$c['tax_number'])?></p><div><span><b><?=$money($c['commercial_value'])?></b> volume ERP</span><span><b><?=$c['order_count']?></b> encomendas</span><span><b><?=h($c['last_order']?date('d/m/Y',strtotime($c['last_order'])):'—')?></b> última compra</span></div></div><i class="bi bi-chevron-right"></i></a><?php endforeach;?></div></section>
<?php else:?>
<section class="crm-panel crm-empty-state"><i class="bi bi-cone-striped"></i><h3><?=h(str_replace('CRM · ','',$pageTitle))?></h3><p>Esta área partilha o modelo central do CRM e está pronta para evolução sem duplicar dados do ERP.</p><a class="btn btn-primary" href="crm.php">Voltar ao dashboard</a></section>
<?php endif;?>
</div>
<div class="modal fade" id="leadModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form method="post" class="modal-content"><?=csrf_input()?><input type="hidden" name="action" value="save_lead"><div class="modal-header"><div><small class="text-primary fw-bold">PROSPEÇÃO</small><h2 class="modal-title fs-5">Novo lead</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><?php foreach(['company'=>'Empresa *','contact_name'=>'Contacto','email'=>'Email','phone'=>'Telefone','mobile'=>'Telemóvel','website'=>'Website','tax_number'=>'NIF','country'=>'País','district'=>'Distrito','locality'=>'Localidade','source'=>'Origem','segment'=>'Segmento','potential'=>'Potencial'] as $n=>$l):?><label class="col-md-6 form-label"><?=$l?><input class="form-control mt-1" name="<?=$n?>" <?=$n==='company'?'required':''?>></label><?php endforeach;?><label class="col-md-3 form-label">Prioridade<select class="form-select mt-1" name="priority"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option></select></label><label class="col-md-3 form-label">Valor estimado<input class="form-control mt-1" type="number" step=".01" name="estimated_value"></label><label class="col-md-3 form-label">Probabilidade<input class="form-control mt-1" type="number" min="0" max="100" name="probability" value="10"></label><label class="col-md-3 form-label">Decisão prevista<input class="form-control mt-1" type="date" name="expected_decision_date"></label><label class="col-12 form-label">Notas<textarea class="form-control mt-1" name="notes"></textarea></label></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancelar</button><button class="btn btn-primary">Criar lead</button></div></form></div></div>
<div class="modal fade" id="activityModal" tabindex="-1"><div class="modal-dialog"><form method="post" class="modal-content"><?=csrf_input()?><input type="hidden" name="action" value="save_activity"><div class="modal-header"><h2 class="modal-title fs-5">Nova atividade</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><label class="form-label">Tipo<select class="form-select" name="type"><?php foreach(['CALL','EMAIL','MEETING','TASK','FOLLOW_UP','QUOTE','NOTE','OTHER'] as $t):?><option><?=$t?></option><?php endforeach;?></select></label><label class="form-label">Título<input class="form-control" name="title" required></label><label class="form-label">Descrição<textarea class="form-control" name="description"></textarea></label><label class="form-label">Prazo<input class="form-control" type="datetime-local" name="due_datetime"></label><label class="form-label">Prioridade<select class="form-select" name="priority"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option></select></label></div><div class="modal-footer"><button class="btn btn-primary">Guardar</button></div></form></div></div>
<script src="assets/crm.js?v=<?=h((string)(@filemtime(__DIR__.'/assets/crm.js')?:'1'))?>"></script>
<?php require __DIR__.'/partials/footer.php';?>
