<?php
// Own bootstrap: ensure only the sales schema in development, then read-only consultation.
function db(){return $GLOBALS['pdo'];}
function has_shopfloor_only_navigation(array $user): bool{return (int)($user['is_admin']??0)!==1&&((int)($user['pin_only_login']??0)===1||(string)($user['access_profile']??'')==='Utilizador');}
require_once __DIR__.'/bootstrap/app.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/app/Services/SalesOrderService.php';
$path=app_config('db_path');if(!is_file($path)){http_response_code(503);exit('Base de desenvolvimento indisponível.');}
$pdo=new PDO('sqlite:'.$path);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec('PRAGMA busy_timeout=5000');$pdo->exec('PRAGMA query_only=ON');
require_login();$user=current_user($pdo)?:[];
if(!gt_erp_user_can($pdo,$user,'erp.view')||!gt_erp_user_can($pdo,$user,'erp.sales')){http_response_code(403);exit('Sem permissão para consultar encomendas de clientes.');}
$method=$_SERVER['REQUEST_METHOD']??'GET';if(!in_array($method,['GET','POST'],true)){http_response_code(405);header('Allow: GET, POST');exit('Método não permitido.');}
try {
    if(!SalesOrderSchema::ensure($pdo,app_config('env'),__DIR__,$path)){
        http_response_code(503);exit('A preparação automática de encomendas está disponível apenas na cópia de desenvolvimento.');
    }
} catch(Throwable $e){
    error_log('Sales order schema preparation failed: '.$e->getMessage());
    http_response_code(503);exit('Não foi possível preparar as encomendas. Verifique a permissão de escrita da base SQLite e da respetiva pasta no servidor.');
}
$service=new SalesOrderService($pdo);$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;
if(isset($_GET['id'])&&$id<1){http_response_code(404);exit('Encomenda não encontrada.');}
$order=$id?$service->order($id):null;if($id&&!$order){http_response_code(404);exit('Encomenda não encontrada.');}
$tabs=['overview'=>'Visão geral','articles'=>'Artigos encomendados','ofs'=>'Ordens de fabrico','delivery'=>'Produção e entregas','costs'=>'Histórico / Custeio','documents'=>'Documentos'];
$tab=SalesOrderService::text($_GET,'tab','overview');if(!isset($tabs[$tab]))$tab='overview';
$financial=gt_erp_user_can($pdo,$user,'erp.costs_view');if($tab==='costs'&&!$financial){http_response_code(403);exit('Sem permissão para consultar custos.');}
$mayConfirm=gt_erp_user_can($pdo,$user,'erp.confirm_orders');$mayOF=gt_erp_user_can($pdo,$user,'erp.work_orders_create');$mayDeliver=gt_erp_user_can($pdo,$user,'erp.shipments_confirm');
$editing=SalesOrderService::text($_GET,'edit')==='1'||SalesOrderService::text($_GET,'new')==='1';
$historical=$order&&($order['source_system']!=='GesTISSER'||$order['original_id']!==null);
$writeEnvironment=SalesOrderSchema::developmentAllowed(app_config('env'),__DIR__,$path);
$error='';
function so_url(array $params=[]){return 'erp.php?'.http_build_query(array_merge(['page'=>'sales_orders'],$params));}
function so_number($value,$precision=3){return $value===null?'Sem dados':number_format((float)$value,$precision,',',' ');}
function so_date($value){return $value&&strtotime($value)!==false?date('d/m/Y',strtotime($value)):'—';}
function so_quantities(array $groups){$parts=[];foreach($groups as $g)$parts[]=so_number($g['quantity']).' '.$g['unit'];return $parts?implode(' · ',$parts):'Sem dados';}
if($method==='POST'){
    $token=$_POST['_token']??'';if(!is_string($token)||$token===''||!hash_equals(csrf_token(),$token)){http_response_code(419);exit('Pedido inválido. Atualize a página.');}
    if(!$writeEnvironment){http_response_code(403);exit('Alterações permitidas apenas na cópia de desenvolvimento.');}
    $action=SalesOrderService::text($_POST,'action');
    $postedId=(int)SalesOrderService::text($_POST,'id','0');if($postedId!==$id){http_response_code(400);exit('Encomenda inválida para esta ficha.');}
    if(!in_array($action,['save','link_of','link_delivery'],true)){http_response_code(405);exit('Ação não permitida.');}
    if(($action==='link_of'&&!$mayOF)||($action==='link_delivery'&&!$mayDeliver)){http_response_code(403);exit('Sem permissão para esta associação.');}
    try {
        $pdo->exec('PRAGMA query_only=OFF');$pdo->beginTransaction();
        if($action==='save')$id=$service->save($_POST,(int)$user['id'],$mayConfirm);
        elseif($action==='link_of')$service->linkWorkOrder($id,(int)SalesOrderService::text($_POST,'line_id'),(int)SalesOrderService::text($_POST,'of_id'),(int)$user['id']);
        else $service->linkDelivery($id,(int)SalesOrderService::text($_POST,'line_id'),(int)SalesOrderService::text($_POST,'movement_id'),SalesOrderService::text($_POST,'delivery_reference'),(int)$user['id']);
        $pdo->commit();header('Location: '.so_url(['id'=>$id,'tab'=>$action==='link_of'?'ofs':($action==='link_delivery'?'delivery':'overview'),'saved'=>1]),true,303);exit;
    }catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Sales order database: '.$e->getMessage());$error='Não foi possível guardar. O registo pode já estar associado; verifique e volte a tentar.';http_response_code(422);}
    catch(RuntimeException $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();http_response_code(422);}
    catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Sales order save: '.$e->getMessage());$error='Não foi possível guardar. Verifique se o registo já está associado e volte a tentar.';http_response_code(422);}
    finally{$pdo->exec('PRAGMA query_only=ON');}
    if($action==='save')$editing=true;
}
$lines=$order?$service->lines($id):[];$ofs=$order?$service->workOrders($id):[];
if(SalesOrderService::text($_GET,'action')==='pdf'){
    if(!$order){http_response_code(404);exit('Encomenda não encontrada.');}
    if(!gt_erp_user_can($pdo,$user,'erp.reports_export')){http_response_code(403);exit('Sem permissão para exportar.');}
    require_once __DIR__.'/vendor/autoload.php';
    $html='<h1>Encomenda '.h($order['order_number']).'</h1><p>'.h($order['customer_code'].' — '.$order['customer_name']).'</p><p>Data: '.h(so_date($order['order_date'])).' · Entrega prevista: '.h(so_date($order['expected_date'])).'</p><p>Estado: '.h($order['status']).' · Origem: '.h($order['source_system']).' · Referência: '.h($order['customer_reference']).'</p><table width="100%" border="1" cellpadding="6"><thead><tr><th>Artigo</th><th>Quantidade</th><th>Unidade</th><th>Preço (€)</th><th>Desconto %</th><th>Valor (€)</th></tr></thead><tbody>';
    foreach($lines as $l)$html.='<tr><td>'.h($l['article_code'].' — '.$l['description']).'</td><td>'.h(so_number($l['quantity'])).'</td><td>'.h($l['unit_code']?:'Não registada').'</td><td>'.h(so_number($l['unit_price'],4)).'</td><td>'.h(so_number($l['discount_percent'],2)).'</td><td>'.h(so_number($l['line_total'],2)).'</td></tr>';
    $html.='</tbody></table><p>'.nl2br(h($order['notes'])).'</p><p>Valores comerciais registados na encomenda. Não constitui documento fiscal.</p>';
    $pdf=new \Mpdf\Mpdf(['tempDir'=>app_config('paths.cache')]);$pdf->WriteHTML($html);$pdf->Output('encomenda-'.$id.'.pdf','D');exit;
}
if(SalesOrderService::text($_GET,'action')==='document'){
    $documentId=filter_input(INPUT_GET,'document',FILTER_VALIDATE_INT)?:0;
    $doc=$order?$service->row('SELECT * FROM erp_product_documents WHERE id=? AND entity_type="sales_order" AND entity_id=?',[$documentId,$id]):null;
    if(!$doc){http_response_code(404);exit('Documento não encontrado.');}
    require_once __DIR__.'/app/Services/ArticleDocument.php';
    try{$file=ArticleDocument::absolutePath(__DIR__,(string)$doc['file_url']);}catch(Throwable $e){http_response_code(404);exit('Ficheiro indisponível.');}
    if(!is_file($file)){http_response_code(404);exit('Ficheiro indisponível.');}
    header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="documento-'.$documentId.'.'.preg_replace('/[^a-z0-9]/i','',pathinfo($file,PATHINFO_EXTENSION)).'"');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');readfile($file);exit;
}
$filters=SalesOrderService::filters($_GET);$list=(!$order&&!$editing)?$service->listing($filters):null;
$pageTitle=$order?'Encomenda '.$order['order_number']:'Encomendas de clientes';$navbarClockControl=[];
require __DIR__.'/partials/header.php';
?>
<link rel="stylesheet" href="assets/customer-profile.css"><script defer src="assets/sales-orders.js"></script>
<div class="container-fluid py-4 customer-profile">
<?php if($error):?><div class="alert alert-danger" role="alert"><?=h($error)?></div><?php elseif(SalesOrderService::text($_GET,'saved')==='1'):?><div class="alert alert-success" role="status">Encomenda atualizada com sucesso.</div><?php endif;?>
<header class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a class="btn btn-sm btn-outline-secondary" href="<?=h(so_url())?>"><i class="bi bi-arrow-left me-1"></i>Voltar à lista</a><div class="small text-secondary mt-3"><?=h($order?$order['source_system']:'Gestão comercial')?></div><h1 class="h3 mb-2"><?=h($pageTitle)?></h1><?php if($order):?><a href="erp.php?page=customer_profile&amp;id=<?=(int)$order['customer_id']?>"><?=h($order['customer_code'].' — '.$order['customer_name'])?></a> <span class="badge text-bg-light ms-2"><?=h($order['status'])?></span><?php if(!$order['customer_active']):?> <span class="badge text-bg-secondary">Cliente inativo</span><?php endif;?><?php endif;?></div><div class="d-flex flex-wrap gap-2">
<?php if($order&&!$historical&&$writeEnvironment):?><a class="btn btn-outline-primary" href="<?=h(so_url(['id'=>$id,'edit'=>1]))?>"><i class="bi bi-pencil me-1"></i>Editar encomenda</a><?php endif;?>
<?php if($order&&$mayOF&&$writeEnvironment&&!$historical&&!in_array($order['status'],['Rascunho','Cancelada','Concluída'],true)):?><a class="btn btn-outline-primary" href="<?=h(so_url(['id'=>$id,'tab'=>'ofs']))?>">Criar OF</a><?php endif;?>
<?php if($order&&gt_erp_user_can($pdo,$user,'erp.reports_export')):?><a class="btn btn-outline-secondary" href="<?=h(so_url(['id'=>$id,'action'=>'pdf']))?>"><i class="bi bi-file-earmark-pdf me-1"></i>Exportar PDF</a><?php endif;?>
<?php if(!$order&&$writeEnvironment):?><a class="btn btn-primary" href="<?=h(so_url(['new'=>1]))?>"><i class="bi bi-plus-lg me-1"></i>Nova encomenda</a><?php endif;?>
<a class="btn btn-outline-secondary" href="erp.php?page=sales">Clientes</a><a class="btn btn-outline-secondary" href="erp.php?page=orders">Compras a fornecedores</a></div></header>
<?php if($editing):
$edit=$method==='POST'?$_POST:($order?:['id'=>0,'revision'=>0,'customer_id'=>SalesOrderService::filters($_GET)['customer'],'order_date'=>date('Y-m-d'),'status'=>'Rascunho']);
$editLines=$method==='POST'?(is_array($_POST['lines']??null)?$_POST['lines']:[]):$lines;if(!$editLines)$editLines=[[]];
$customers=$service->all('SELECT id,code,name,is_active FROM erp_customers ORDER BY code');
$articles=$service->all('SELECT id,code,description,customer_id,status FROM erp_finished_products ORDER BY code');
?>
<section class="card mb-4"><div class="card-body"><h2 class="h5 mb-3"><?=$order?'Editar encomenda':'Nova encomenda'?></h2>
<?php if($historical||!$writeEnvironment):?><p class="text-secondary">Esta encomenda é apenas de consulta.</p><?php else:?>
<form method="post" class="row g-3" data-sales-order-form><?=csrf_input()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="revision" value="<?=h(SalesOrderService::text($edit,'revision','0'))?>">
<div class="col-md-4"><label class="form-label" for="so-customer">Cliente *</label><select class="form-select" name="customer_id" id="so-customer" required><option value="">Selecione…</option><?php foreach($customers as $c):if(!$c['is_active']&&$c['id']!=($order['customer_id']??0))continue;?><option value="<?=(int)$c['id']?>" <?=$c['id']==($edit['customer_id']??0)?'selected':''?>><?=h($c['code'].' — '.$c['name'])?></option><?php endforeach;?></select></div>
<?php foreach(['order_date'=>'Data da encomenda *','expected_date'=>'Entrega prevista','customer_reference'=>'Referência do cliente'] as $field=>$label):?><div class="col-md-<?=$field==='customer_reference'?'4':'2'?>"><label class="form-label" for="so-<?=$field?>"><?=h($label)?></label><input class="form-control" id="so-<?=$field?>" name="<?=$field?>" type="<?=$field==='customer_reference'?'text':'date'?>" <?=$field==='order_date'?'required':''?> value="<?=h(SalesOrderService::text($edit,$field))?>"></div><?php endforeach;?>
<div class="col-md-4"><label class="form-label" for="so-status">Estado comercial</label><select class="form-select" name="status" id="so-status"><?php $states=SalesOrderService::statuses();if($order&&!in_array($order['status'],$states,true))$states[]=$order['status'];foreach($states as $s):if(!$mayConfirm&&$s!==($order['status']??'Rascunho'))continue;?><option <?=($edit['status']??'Rascunho')===$s?'selected':''?>><?=h($s)?></option><?php endforeach;?></select></div>
<div class="col-12"><label class="form-label" for="so-notes">Observações</label><textarea class="form-control" name="notes" id="so-notes" rows="2"><?=h(SalesOrderService::text($edit,'notes'))?></textarea></div>
<div class="col-12"><h3 class="h6">Artigos encomendados</h3><p class="small text-secondary">Preços e descontos pertencem à encomenda. As linhas existentes são preservadas.</p><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Artigo *</th><th>Descrição</th><th>Quantidade *</th><th>Preço unitário (€)</th><th>Desconto %</th><th>Entrega prevista</th><th></th></tr></thead><tbody data-sales-lines>
<?php foreach($editLines as $i=>$l):if(!is_array($l))continue;require __DIR__.'/partials/sales_order_edit_line.php';endforeach;?>
</tbody></table></div><button class="btn btn-sm btn-outline-primary" type="button" data-add-sales-line>Adicionar artigo</button><template data-sales-line-template><?php $i='__INDEX__';$l=[];require __DIR__.'/partials/sales_order_edit_line.php';?></template></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-primary">Guardar encomenda</button><a class="btn btn-outline-secondary" href="<?=h(so_url($id?['id'=>$id]:[]))?>">Cancelar</a></div>
</form><?php endif;?></div></section>
<?php elseif($order):?>
<div class="row g-3 mb-4"><?php $cards=[['Linhas',count($lines),'Artigos encomendados'],['Quantidade encomendada',so_quantities(SalesOrderService::totals($lines,'quantity')),'Valores por unidade'],['Quantidade produzida',so_quantities(SalesOrderService::totals($lines,'produced')),'Quantidade realizada nas OF associadas'],['Quantidade entregue',so_quantities(SalesOrderService::totals($lines,'delivered')),'Saídas explicitamente confirmadas'],['Quantidade por entregar',so_quantities(SalesOrderService::totals($lines,'pending')),'Pendente por linha'],['OF associadas',count($ofs),'Ligações por identificador interno']];foreach($cards as $c):?><div class="col-12 col-sm-6 col-xl-4"><div class="card h-100"><div class="card-body"><div class="small text-secondary mb-2"><?=h($c[0])?></div><div class="h4 cp-metric mb-2"><?=h($c[1])?></div><div class="small text-secondary"><?=h($c[2])?></div></div></div></div><?php endforeach;?></div>
<nav class="cp-tabs mb-4" aria-label="Separadores da encomenda"><div class="d-flex flex-wrap gap-2"><?php $icons=['overview'=>'bi-grid','articles'=>'bi-box-seam','ofs'=>'bi-clipboard2-check','delivery'=>'bi-truck','costs'=>'bi-graph-up','documents'=>'bi-folder2-open'];foreach($tabs as $key=>$label):if($key==='costs'&&!$financial)continue;?><a class="btn btn-sm <?=$tab===$key?'btn-primary':'btn-outline-secondary'?>" <?=$tab===$key?'aria-current="page"':''?> href="<?=h(so_url(['id'=>$id,'tab'=>$key]))?>"><i class="bi <?=h($icons[$key])?> me-1" aria-hidden="true"></i><?=h($label)?></a><?php endforeach;?></div></nav>
<section class="card"><div class="card-body"><h2 class="h5 mb-3"><?=h($tabs[$tab])?></h2>
<?php if($tab==='overview'):?>
<dl class="row cp-details"><?php foreach(['order_date'=>'Data da encomenda','expected_date'=>'Entrega prevista','customer_reference'=>'Referência do cliente','status'=>'Estado comercial','source_system'=>'Origem','original_number'=>'Número original'] as $key=>$label):?><dt class="col-sm-3"><?=h($label)?></dt><dd class="col-sm-9"><?=h(in_array($key,['order_date','expected_date'],true)?so_date($order[$key]):($order[$key]?:'—'))?></dd><?php endforeach;?></dl>
<h3 class="h6 mt-4">Produção e logística</h3><?php foreach($lines as $l):?><p class="mb-1"><?=h($l['article_code'])?> · <?=h($l['production_state'])?> · <?=h($l['logistic_state'])?></p><?php endforeach;?>
<h3 class="h6 mt-4">Observações</h3><p><?=nl2br(h($order['notes']?:'Sem observações.'))?></p>
<h3 class="h6 mt-4">Últimas atividades</h3><?php $history=$service->history($id);foreach(array_slice($history,0,5) as $event):?><p class="small mb-1"><?=h(so_date($event['created_at']).' · '.$event['action'])?></p><?php endforeach;if(!$history):?><p class="text-secondary">Sem alterações registadas.</p><?php endif;?>
<a class="btn btn-sm btn-outline-secondary mt-3" href="<?=h(so_url(['id'=>$id,'tab'=>'documents']))?>">Consultar documentos</a>
<?php elseif($tab==='articles'||$tab==='delivery'):?>
<p class="small text-secondary"><?=$tab==='articles'?'Valores comerciais registados na encomenda; sem atualização pelos preços atuais do artigo.':'Produção e entrega são independentes. A ausência de uma entrega associada significa ausência de entrega comprovada no módulo.'?></p>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Artigo</th><th>Encomendada</th><th>Unidade</th><?php if($tab==='articles'):?><th>Preço (€)</th><th>Desconto %</th><th>Valor (€)</th><th>Entrega prevista</th><?php else:?><th>Planeada</th><?php endif;?><th>Produzida</th><th>Entregue</th><th>Pendente</th><th>Estado</th></tr></thead><tbody><?php foreach($lines as $l):?><tr><td><a class="fw-semibold" href="erp.php?page=article_profile&amp;id=<?=(int)$l['finished_product_id']?>"><?=h($l['article_code'])?></a><div class="small text-secondary"><?=h($l['description'])?></div><?php if($l['article_status']!=='Ativo'):?><span class="badge text-bg-secondary">Artigo inativo</span><?php endif;?></td><td><?=h(so_number($l['quantity']))?></td><td><?=h($l['unit_code']?:'Não registada')?></td><?php if($tab==='articles'):foreach(['unit_price'=>4,'discount_percent'=>2,'line_total'=>2] as $key=>$dec):?><td><?=h(so_number($l[$key],$dec))?></td><?php endforeach;?><td><?=h(so_date($l['expected_date']?:$order['expected_date']))?></td><?php else:?><td><?=h(so_number($l['planned']))?></td><?php endif;?><td><?=h(so_number($l['produced']))?></td><td><?=h(so_number($l['delivered']))?></td><td><?=h(so_number($l['pending']))?></td><td><div><?=h($l['production_state'])?></div><div class="small text-secondary"><?=h($l['logistic_state'])?></div></td></tr><?php endforeach;?></tbody></table></div>
<?php if($tab==='delivery'):?>
<h3 class="h6 mt-4">Entregas comprovadas</h3><div class="table-responsive"><table class="table"><thead><tr><th>Documento</th><th>Movimento</th><th>Artigo</th><th>Data</th><th>Quantidade</th><th>Situação</th></tr></thead><tbody><?php $deliveries=$service->deliveries($id);foreach($deliveries as $d):?><tr><td><?=h($d['delivery_reference'])?></td><td><?=h($d['movement_number'])?></td><td><?=h($d['article_code'])?></td><td><?=h(so_date($d['movement_date']))?></td><td><?=h(so_number(abs($d['quantity'])).' '.$d['unit_code'])?></td><td><?=$d['reversed']?'Movimento estornado':'Associada'?></td></tr><?php endforeach;if(!$deliveries):?><tr><td colspan="6" class="text-secondary">Sem entregas comprovadas.</td></tr><?php endif;?></tbody></table></div>
<?php if($mayDeliver&&$writeEnvironment&&!$historical&&!in_array($order['status'],['Rascunho','Cancelada','Concluída'],true)):?>
<details class="mt-3"><summary>Associar entrega a uma saída existente</summary><p class="small text-secondary mt-2">Confirme o destinatário e o documento antes de associar. Esta ação não cria nem altera movimentos de stock.</p><form method="post" class="row g-2"><?=csrf_input()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="link_delivery"><div class="col-md-4"><label class="form-label">Linha<select name="line_id" class="form-select" required><?php foreach($lines as $l):?><option value="<?=(int)$l['id']?>"><?=h($l['line_number'].' · '.$l['article_code'])?></option><?php endforeach;?></select></label></div><div class="col-md-2"><label class="form-label">ID da saída<input class="form-control" type="number" min="1" name="movement_id" required></label></div><div class="col-md-4"><label class="form-label">Documento de entrega<input class="form-control" name="delivery_reference" required></label></div><div class="col-md-2 align-self-end"><button class="btn btn-primary">Associar</button></div></form></details><?php endif;?>
<?php endif;?>
<?php elseif($tab==='ofs'):?>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>OF</th><th>Artigo</th><th>Prevista</th><th>Realizada</th><th>Data prevista</th><th>Estado</th><th>Progresso</th></tr></thead><tbody><?php foreach($ofs as $of):?><tr><td><a href="production_dossier.php?id=<?=(int)$of['id']?>"><?=h($of['order_number'])?></a></td><td><?=h($of['article_code'])?></td><td><?=h(so_number($of['planned_quantity']).' '.$of['unit_code'])?></td><td><?=h(so_number($of['produced_quantity']).' '.$of['unit_code'])?></td><td><?=h(so_date($of['due_date']))?></td><td><?=h($of['status'])?></td><td><?=h($of['planned_quantity']>0?so_number(100*$of['produced_quantity']/$of['planned_quantity'],1).' %':'Sem dados')?></td></tr><?php endforeach;if(!$ofs):?><tr><td colspan="7" class="text-secondary py-4">Sem OF associadas.</td></tr><?php endif;?></tbody></table></div>
<?php if($mayOF&&$writeEnvironment&&!$historical&&!in_array($order['status'],['Rascunho','Cancelada','Concluída'],true)):?>
<div class="d-flex flex-wrap gap-2 mt-3"><?php foreach($lines as $l):if($l['article_status']!=='Ativo'||$l['article_customer_id']!=$order['customer_id']||max(0,$l['quantity']-$l['planned'])<=0)continue;?><a class="btn btn-outline-primary" href="erp.php?page=production&amp;sales_order_line=<?=(int)$l['id']?>#new-work-order-form">Criar OF · <?=h($l['article_code'])?></a><?php endforeach;?></div><p class="small text-secondary mt-2">O formulário atual recebe o artigo, a quantidade por planear e a referência comercial. A OF criada fica ligada à linha, mantendo o processo de routing e ficha técnica existente.</p>
<form method="post" class="row g-2"><?=csrf_input()?><input type="hidden" name="action" value="link_of"><input type="hidden" name="id" value="<?=$id?>"><div class="col-md-5"><label class="form-label">Linha<select class="form-select" name="line_id" required><?php foreach($lines as $l):?><option value="<?=(int)$l['id']?>"><?=h($l['line_number'].' · '.$l['article_code'].' · pendente '.so_number(max(0,$l['quantity']-$l['planned'])).' '.$l['unit_code'])?></option><?php endforeach;?></select></label></div><div class="col-md-5"><label class="form-label">OF existente<select class="form-select" name="of_id" required><option value="">Selecione…</option><?php $candidates=$service->all('SELECT o.id,o.order_number,a.code FROM erp_production_orders o JOIN erp_finished_products a ON a.id=o.finished_product_id WHERE o.customer_id=? AND EXISTS(SELECT 1 FROM erp_sales_order_lines l WHERE l.sales_order_id=? AND l.finished_product_id=o.finished_product_id) AND NOT EXISTS(SELECT 1 FROM erp_sales_order_work_orders w WHERE w.production_order_id=o.id) ORDER BY o.id DESC LIMIT 200',[$order['customer_id'],$id]);foreach($candidates as $of):?><option value="<?=(int)$of['id']?>"><?=h($of['order_number'].' · '.$of['code'])?></option><?php endforeach;?></select></label></div><div class="col-md-2 align-self-end"><button class="btn btn-primary">Associar OF</button></div></form><?php endif;?>
<?php elseif($tab==='costs'):?>
<p class="small text-secondary">Custos previstos e reais apenas quando existe um fecho registado da OF. Preço de venda e valor faturado são conceitos distintos; não existe ligação comprovada a faturação.</p>
<div class="table-responsive"><table class="table"><thead><tr><th>OF</th><th>Custo previsto (€)</th><th>Custo real (€)</th><th>Desvio (€)</th><th>Fecho</th></tr></thead><tbody><?php foreach($service->costs($id) as $cost):?><tr><td><a href="production_dossier.php?id=<?=(int)$cost['id']?>"><?=h($cost['order_number'])?></a></td><td><?=h(so_number($cost['total_planned_cost'],2))?></td><td><?=h(so_number($cost['total_actual_cost'],2))?></td><td><?=h(so_number($cost['total_actual_cost']===null?null:$cost['total_actual_cost']-$cost['total_planned_cost'],2))?></td><td><?=h(so_date($cost['closed_at']))?></td></tr><?php endforeach;?></tbody></table></div>
<h3 class="h6 mt-4">Valores comerciais registados</h3><?php foreach($lines as $l):?><p><?=h($l['article_code'].' · '.so_number($l['line_total'],2).' €')?></p><?php endforeach;?><p class="text-secondary">Valor faturado: sem dados. Margem: sem dados suficientes.</p>
<h3 class="h6 mt-4">Histórico de alterações</h3><ul class="list-unstyled"><?php foreach($service->history($id) as $event):$before=json_decode($event['old_values_json'],true);$after=json_decode($event['new_values_json'],true);?><li class="border-bottom py-2"><?=h($event['created_at'].' · '.$event['action'])?><?php if(isset($after['order']['status'])):?> · <?=h(($before['order']['status']??'Novo').' → '.$after['order']['status'])?><?php endif;?></li><?php endforeach;?></ul>
<?php elseif($tab==='documents'):?>
<p class="small text-secondary">Documentos associados através do catálogo documental existente e documentos das OF relacionadas.</p>
<ul class="list-group"><?php $docs=$service->documents($id);foreach($docs as $doc):?><li class="list-group-item"><strong><?=h($doc['title'])?></strong> · <?=h($doc['document_type'].' · '.$doc['status'])?><?php $url=$doc['file_url']??'';if(preg_match('~^https?://~i',$url)):?> <a href="<?=h($url)?>" target="_blank" rel="noopener">Abrir documento</a><?php elseif($url):?> <a href="<?=h(so_url(['id'=>$id,'action'=>'document','document'=>$doc['id']]))?>">Descarregar documento</a><?php endif;?></li><?php endforeach;foreach($ofs as $of):?><li class="list-group-item"><a href="production_dossier.php?id=<?=(int)$of['id']?>"><?=h('Dossier e documentos · '.$of['order_number'])?></a></li><?php endforeach;if(!$docs&&!$ofs):?><li class="list-group-item text-secondary">Sem documentos associados.</li><?php endif;?></ul>
<?php endif;?>
</div></section>
<?php else:?>
<section class="card mb-4"><div class="card-body"><form method="get" class="row g-3"><input type="hidden" name="page" value="sales_orders"><?php if($filters['customer']):?><input type="hidden" name="customer" value="<?=$filters['customer']?>"><?php endif;if($filters['article']):?><input type="hidden" name="article" value="<?=$filters['article']?>"><?php endif;?>
<div class="col-md-4"><label class="form-label" for="so-q">Pesquisar encomenda, cliente ou artigo</label><input class="form-control" id="so-q" name="q" value="<?=h($filters['q'])?>"></div>
<div class="col-md-2"><label class="form-label" for="filter-status">Estado</label><select class="form-select" id="filter-status" name="status"><option value="">Todos</option><?php $states=$service->all('SELECT DISTINCT status FROM erp_sales_orders ORDER BY status');$states=array_unique(array_merge(SalesOrderService::statuses(),array_column($states,'status')));foreach($states as $s):?><option <?=$filters['status']===$s?'selected':''?>><?=h($s)?></option><?php endforeach;?></select></div>
<?php foreach(['from'=>'Desde','to'=>'Até'] as $key=>$label):?><div class="col-md-2"><label class="form-label" for="so-<?=$key?>"><?=h($label)?></label><input class="form-control" id="so-<?=$key?>" type="date" name="<?=$key?>" value="<?=h($filters[$key])?>"></div><?php endforeach;?>
<div class="col-md-2 align-self-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="so-late" name="late" value="1" <?=$filters['late']==='1'?'checked':''?>><label class="form-check-label" for="so-late">Em atraso</label></div><button class="btn btn-primary w-100">Filtrar</button></div></form></div></section>
<section class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><?php foreach(['number'=>'Encomenda','customer'=>'Cliente','date'=>'Data','expected'=>'Entrega prevista','lines'=>'Artigos'] as $key=>$label):?><th><a href="<?=h(so_url(array_merge($filters,['sort'=>$key,'dir'=>$filters['sort']===$key&&$filters['dir']==='asc'?'desc':'asc','p'=>1])))?>"><?=h($label)?></a></th><?php endforeach;?><th>Quantidade por unidade</th><?php foreach(['status'=>'Estado','source'=>'Origem'] as $key=>$label):?><th><a href="<?=h(so_url(array_merge($filters,['sort'=>$key,'dir'=>$filters['sort']===$key&&$filters['dir']==='asc'?'desc':'asc','p'=>1])))?>"><?=h($label)?></a></th><?php endforeach;?><th>Ações</th></tr></thead><tbody><?php foreach($list['rows'] as $r):?><tr><td><a class="fw-semibold" href="<?=h(so_url(['id'=>$r['id']]))?>"><?=h($r['order_number'])?></a></td><td><a href="erp.php?page=customer_profile&amp;id=<?=(int)$r['customer_id']?>"><?=h($r['customer_code'].' — '.$r['customer_name'])?></a></td><td><?=h(so_date($r['order_date']))?></td><td><?=h(so_date($r['expected_date']))?></td><td><?=(int)$r['article_count']?></td><td><?=h(so_quantities($r['quantities']))?></td><td><span class="badge text-bg-light"><?=h($r['status'])?></span></td><td><?=h($r['source_system'])?></td><td><a class="btn btn-sm btn-outline-primary" href="<?=h(so_url(['id'=>$r['id']]))?>">Consultar</a></td></tr><?php endforeach;if(!$list['rows']):?><tr><td colspan="9" class="text-center text-secondary py-4">Sem encomendas para os filtros selecionados.</td></tr><?php endif;?></tbody></table></div>
<nav aria-label="Paginação" class="d-flex flex-wrap justify-content-between gap-2 mt-3"><span class="small text-secondary"><?=$list['total']?> encomendas · página <?=$list['page']?> / <?=$list['pages']?></span><div class="d-flex gap-2"><?php if($list['page']>1):?><a class="btn btn-sm btn-outline-secondary" href="<?=h(so_url(array_merge($filters,['p'=>$list['page']-1])))?>">Anterior</a><?php endif;if($list['page']<$list['pages']):?><a class="btn btn-sm btn-outline-secondary" href="<?=h(so_url(array_merge($filters,['p'=>$list['page']+1])))?>">Seguinte</a><?php endif;?></div></nav></div></section>
<?php endif;?>
</div><?php require __DIR__.'/partials/footer.php';?>
