<?php
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/erp_migrations.php';
require_login();
erp_run_phase1_migrations($pdo);
$stmt=$pdo->prepare('SELECT * FROM erp_technical_sheets WHERE id=?');
$stmt->execute([(int)($_GET['id']??0)]);
$sheet=$stmt->fetch(PDO::FETCH_ASSOC);
if (!$sheet) { http_response_code(404); exit('Ficha Técnica não encontrada.'); }
$a=json_decode($sheet['snapshot_json'],true) ?: []; $o=$a['_order']??[];
function sheet_value(array $data, string $key): string { return trim((string)($data[$key]??'')); }
$analysis=['analysis_grammage'=>'Gramagem média do saco','analysis_total_weight'=>'Peso total do saco','analysis_apparent_width'=>'Largura média aparente','analysis_gusset_width'=>'Largura média do fole','analysis_bag_height'=>'Altura média do saco','analysis_break_height'=>'Resistência à rotura / alongamento — altura','analysis_break_length'=>'Resistência à rotura / alongamento — comprimento','analysis_seam_strength'=>'Resistência da costura','analysis_static_friction'=>'Coeficiente de fricção — estático','analysis_dynamic_friction'=>'Coeficiente de fricção — dinâmico','analysis_air_permeability'=>'Permeabilidade do ar'];
$filledAnalysis=array_filter($analysis,function($label,$key)use($a){return sheet_value($a,$key)!=='';},ARRAY_FILTER_USE_BOTH);
?><!doctype html><html lang="pt"><head><meta charset="utf-8"><title>Ficha Técnica <?=h((string)($o['order_number']??''))?></title><style>body{font:14px Arial;margin:24px;color:#111}.head{text-align:center;border:2px solid #111;padding:14px}h1{margin:0}.section{margin-top:8px;border:2px solid #111}.section h2{font-size:16px;text-align:center;background:#ddd;margin:0;padding:6px}.grid{display:grid;grid-template-columns:repeat(4,1fr)}.cell{border:1px solid #bbb;padding:8px;min-height:34px}.cell b{display:block;font-size:11px;text-transform:uppercase}.wide{grid-column:span 2}table{width:100%;border-collapse:collapse}th,td{border:1px solid #777;padding:7px;text-align:left}th{background:#eee}.actions{margin-bottom:16px}@media print{.actions{display:none}body{margin:8mm}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Guardar PDF</button></div><header class="head"><h1>FICHA TÉCNICA DO PRODUTO</h1><strong>OF <?=h(sheet_value($o,'order_number'))?></strong></header>
<section class="section"><h2>IDENTIFICAÇÃO</h2><div class="grid"><div class="cell wide"><b>Cliente</b><?=h(sheet_value($a,'customer_name'))?></div><div class="cell"><b>Artigo</b><?=h(sheet_value($a,'code'))?></div><div class="cell"><b>Ref. cliente</b><?=h(sheet_value($a,'customer_product_code'))?></div><div class="cell wide"><b>Descrição</b><?=h(sheet_value($a,'description'))?></div><div class="cell"><b>Encomenda</b><?=h(sheet_value($o,'customer_order'))?></div><div class="cell"><b>Data prevista</b><?=h(sheet_value($o,'due_date'))?></div></div></section>
<section class="section"><h2>ESPECIFICAÇÕES DO MATERIAL E SACO</h2><div class="grid"><?php foreach(['material'=>'Material','composition'=>'Composição','bag_color'=>'Cor','grammage'=>'Gramagem','width'=>'Largura','length'=>'Comprimento','width_tolerance'=>'Tolerância largura','length_tolerance'=>'Tolerância comprimento','theoretical_weight'=>'Peso teórico','proof_reference'=>'N.º prova','front_colors'=>'Impressão frente','back_colors'=>'Impressão verso','thread_color'=>'Cor do fio','perforation_type'=>'Perfuração','seam_type'=>'Costura','gusset_length'=>'Fole'] as $key=>$label): if(sheet_value($a,$key)==='')continue;?><div class="cell"><b><?=h($label)?></b><?=nl2br(h(sheet_value($a,$key)))?></div><?php endforeach;?></div></section>
<section class="section"><h2>CARACTERÍSTICAS E EMPALETIZAÇÃO</h2><div class="grid"><?php foreach(['microperforation'=>'Microperfuração','has_handle'=>'Asa','has_holes'=>'Furo','has_gusset'=>'Fole','centered_gusset'=>'Fole centrado'] as $key=>$label):?><div class="cell"><b><?=h($label)?></b><?=!empty($a[$key])?'Sim':'Não'?></div><?php endforeach;?><?php foreach(['pallet_dimensions'=>'Medidas da palete','pallet_lid'=>'Tampa','pallet_straps'=>'Fitas','pallet_film'=>'Filme'] as $key=>$label):if(sheet_value($a,$key)==='')continue;?><div class="cell"><b><?=h($label)?></b><?=h(sheet_value($a,$key))?></div><?php endforeach;?></div></section>
<?php if($filledAnalysis):?><section class="section"><h2>BOLETIM DE ANÁLISE</h2><table><tr><th>Característica</th><th>Valor / unidade / norma</th></tr><?php foreach($filledAnalysis as $key=>$label):?><tr><td><?=h($label)?></td><td><?=h(sheet_value($a,$key))?></td></tr><?php endforeach;?></table></section><?php endif;?>
<section class="section"><h2>DADOS DA ENCOMENDA</h2><div class="grid"><div class="cell"><b>Quantidade</b><?=h(sheet_value($o,'quantity'))?></div><div class="cell"><b>Lote</b><?=h(sheet_value($o,'lot'))?></div><div class="cell wide"><b>Observações</b><?=h(sheet_value($o,'notes'))?></div></div></section></body></html>
