<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/app/Services/RawMaterialSpreadsheet.php';
require_login();
$headers=RawMaterialSpreadsheet::templateColumns();
$values=['codigo'=>'MP-001','descricao'=>'Polipropileno','categoria'=>'raw_material','tipo'=>'POLIMERO','caracteristica'=>'NATURAL','unidade'=>'KG','largura'=>'','gramagem'=>'','stock_minimo'=>'100','stock_maximo'=>'1000','ponto_reposicao'=>'250','prazo_entrega_dias'=>'5','fornecedor_preferencial'=>'FOR-001','preco_padrao'=>'1,2500','armazem_standard'=>'MP','localizacao_standard'=>'A-01','email_alerta'=>'aprovisionamento@empresa.pt','alertas_ativos'=>'Sim','controlar_lote'=>'Sim','controlar_bobina'=>'Não','permitir_consumo_parcial'=>'Sim','estado'=>'Ativo','observacoes'=>''];
$example=[];foreach($headers as$header){$example[]=$values[$header]??'';}
function raw_material_xlsx_cell(string$value):string{return '<c t="inlineStr"><is><t>'.htmlspecialchars($value,ENT_XML1|ENT_QUOTES,'UTF-8').'</t></is></c>';}
$rows='<row>'.implode('',array_map('raw_material_xlsx_cell',$headers)).'</row><row>'.implode('',array_map('raw_material_xlsx_cell',$example)).'</row>';
$files=['[Content_Types].xml'=>'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml'=>'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Matérias-primas" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels'=>'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml'=>'<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'.$rows.'</sheetData></worksheet>'];
$tmp=tempnam(sys_get_temp_dir(),'raw_materials_');$zip=new ZipArchive();$zip->open($tmp,ZipArchive::CREATE|ZipArchive::OVERWRITE);foreach($files as$name=>$body){$zip->addFromString($name,$body);}$zip->close();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="modelo_importacao_materias_primas.xlsx"');header('Content-Length: '.filesize($tmp));readfile($tmp);unlink($tmp);
