<?php
require_once __DIR__.'/helpers.php'; require_once __DIR__.'/hr_organization_lib.php'; require_once __DIR__.'/erp_migrations.php'; require_once __DIR__.'/app/Services/RoutingService.php'; require_once __DIR__.'/app/Services/UploadService.php';
require_login(); gt_run_org_migrations($pdo); erp_run_phase1_migrations($pdo); $user=current_user($pdo)?:[];$uid=(int)$user['id'];
if(!erp_user_can($pdo,$user,'erp.operations.view')){http_response_code(403);exit('Sem permissão para consultar operações.');}
$service=new RoutingService($pdo);$ok=$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'&&validate_csrf_or_abort(false)){try{
    if(!erp_user_can($pdo,$user,'erp.operations.manage'))throw new RuntimeException('Sem permissão para gerir operações.');
    if(($_POST['action']??'')==='delete_instruction_file'){
        $documentId=(int)($_POST['document_id']??$_GET['document_id']??0);$operationId=(int)($_POST['id']??0);
        $stmt=$pdo->prepare('SELECT * FROM erp_operation_documents WHERE id=? AND operation_id=?');$stmt->execute([$documentId,$operationId]);$document=$stmt->fetch(PDO::FETCH_ASSOC);
        if(!$document)throw new RuntimeException('Anexo inexistente.');
        $pdo->prepare('DELETE FROM erp_operation_documents WHERE id=?')->execute([$documentId]);
        $path=__DIR__.'/'.ltrim((string)$document['file_url'],'/');if(strpos((string)$document['file_url'],'storage/uploads/')===0&&is_file($path))@unlink($path);
        $ok='Anexo removido com sucesso.';
    }else{
        $operationId=$service->saveOperation($_POST,(array)($_POST['machine_ids']??[]),$uid);
        $allowed=['pdf'=>['application/pdf'],'jpg'=>['image/jpeg'],'jpeg'=>['image/jpeg'],'png'=>['image/png'],'webp'=>['image/webp'],'gif'=>['image/gif'],'mp4'=>['video/mp4'],'webm'=>['video/webm'],'ogv'=>['video/ogg']];
        if(!empty($_FILES['instruction_files']['name'])&&is_array($_FILES['instruction_files']['name'])){
            $insert=$pdo->prepare('INSERT INTO erp_operation_documents(operation_id,title,file_url,mime_type,created_by) VALUES (?,?,?,?,?)');
            foreach($_FILES['instruction_files']['name'] as $index=>$originalName){
                if((int)($_FILES['instruction_files']['error'][$index]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;
                $extension=strtolower((string)pathinfo((string)$originalName,PATHINFO_EXTENSION));if(!isset($allowed[$extension]))throw new RuntimeException('O ficheiro "'.basename((string)$originalName).'" não tem um formato permitido.');
                $file=['name'=>$originalName,'type'=>$_FILES['instruction_files']['type'][$index]??'','tmp_name'=>$_FILES['instruction_files']['tmp_name'][$index]??'','error'=>$_FILES['instruction_files']['error'][$index]??UPLOAD_ERR_NO_FILE,'size'=>$_FILES['instruction_files']['size'][$index]??0];
                $url=UploadService::secureUpload($file,$allowed[$extension],52428800);if(!$url)throw new RuntimeException('Não foi possível carregar "'.basename((string)$originalName).'". O limite é 50 MB por ficheiro.');
                $insert->execute([$operationId,basename((string)$originalName),$url,$allowed[$extension][0],$uid]);
            }
        }
        $ok='Operação guardada com sucesso.';
    }
}catch(Throwable$e){$error=$e->getMessage();}}
$q=trim((string)($_GET['q']??''));$sector=(int)($_GET['sector']??0);$machine=(int)($_GET['machine']??0);$state=(string)($_GET['state']??'');$where=['1=1'];$args=[];if($q!==''){$where[]='(o.code LIKE ? OR o.name LIKE ? OR o.description LIKE ?)';array_push($args,"%$q%","%$q%","%$q%");}if($sector){$where[]='o.default_work_center_id=?';$args[]=$sector;}if($machine){$where[]='EXISTS(SELECT 1 FROM erp_operation_machines om WHERE om.operation_id=o.id AND om.machine_id=?)';$args[]=$machine;}if($state!==''){$where[]='o.is_active=?';$args[]=$state==='active'?1:0;}$st=$pdo->prepare('SELECT o.*,w.name work_center_name,(SELECT group_concat(m.code,", ") FROM erp_operation_machines om JOIN erp_machines m ON m.id=om.machine_id WHERE om.operation_id=o.id) machines FROM erp_operations o LEFT JOIN erp_work_centers w ON w.id=o.default_work_center_id WHERE '.implode(' AND ',$where).' ORDER BY o.is_active DESC,o.code');$st->execute($args);$rows=$st->fetchAll(PDO::FETCH_ASSOC);$machines=$pdo->query('SELECT id,code,name FROM erp_machines WHERE is_active=1 AND deleted_at IS NULL ORDER BY code')->fetchAll(PDO::FETCH_ASSOC);$centers=$pdo->query('SELECT id,code,name FROM erp_work_centers WHERE is_active=1 ORDER BY code')->fetchAll(PDO::FETCH_ASSOC);$edit=null;$selected=[];$defaultMachineId=0;if(isset($_GET['id'])){$s=$pdo->prepare('SELECT * FROM erp_operations WHERE id=?');$s->execute([(int)$_GET['id']]);$edit=$s->fetch(PDO::FETCH_ASSOC);$s=$pdo->prepare('SELECT machine_id,is_default FROM erp_operation_machines WHERE operation_id=?');$s->execute([(int)$_GET['id']]);foreach($s->fetchAll(PDO::FETCH_ASSOC) as$operationMachine){$selected[]=(int)$operationMachine['machine_id'];if((int)$operationMachine['is_default']===1)$defaultMachineId=(int)$operationMachine['machine_id'];}}
$documents=[];if($edit&&!empty($edit['id'])){$s=$pdo->prepare('SELECT * FROM erp_operation_documents WHERE operation_id=? ORDER BY created_at,id');$s->execute([(int)$edit['id']]);$documents=$s->fetchAll(PDO::FETCH_ASSOC);}
$operationTypeLabels=['production'=>'Produção','control'=>'Controlo','transport'=>'Transporte','wait'=>'Espera','subcontract'=>'Subcontratação','other'=>'Outro'];
$productionUnitLabels=['unit'=>'Unidades','units'=>'Unidades','unidade'=>'Unidades','unidades'=>'Unidades','piece'=>'Peças','pieces'=>'Peças','kg'=>'Quilogramas','kilogram'=>'Quilogramas','kilograms'=>'Quilogramas','m'=>'Metros','meter'=>'Metros','meters'=>'Metros','l'=>'Litros','liter'=>'Litros','liters'=>'Litros','litro'=>'Litros','litros'=>'Litros','t'=>'Toneladas','ton'=>'Toneladas','tons'=>'Toneladas'];
$currentProductionUnit=(string)($edit['production_unit']??'unit');
if(!isset($productionUnitLabels[$currentProductionUnit]))$productionUnitLabels[$currentProductionUnit]='Outra unidade';
$checklistTemplates=$pdo->query('SELECT ct.id,ct.name,COUNT(cti.id) items_count FROM checklist_templates ct LEFT JOIN checklist_template_items cti ON cti.template_id=ct.id GROUP BY ct.id ORDER BY ct.name COLLATE NOCASE')->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Operações';$bodyClass='bg-light operations-view';require __DIR__.'/partials/header.php';
?>
<div class="container-fluid operations-page py-4">
<div class="operations-page-header"><div><div class="operations-eyebrow"><i class="bi bi-diagram-3"></i> Configuração da produção</div><h1>Operações</h1><p>Crie e mantenha o catálogo de etapas utilizado nos roteiros de fabrico.</p></div><?php if(erp_user_can($pdo,$user,'erp.operations.manage')):?><a class="btn btn-primary" href="erp_operations.php?id=0"><i class="bi bi-plus-lg"></i> Nova operação</a><?php endif;?></div>
<?php if($ok):?><div class="alert alert-success"><?=h($ok)?></div><?php endif;if($error):?><div class="alert alert-danger"><?=h($error)?></div><?php endif;?>
<form class="operations-filter" aria-label="Filtrar operações"><div class="operations-search"><i class="bi bi-search"></i><input class="form-control" name="q" value="<?=h($q)?>" placeholder="Pesquisar por código, nome ou descrição" aria-label="Pesquisar operações"></div><select class="form-select" name="sector" aria-label="Filtrar por setor"><option value="">Todos os setores</option><?php foreach($centers as$c):?><option value="<?=$c['id']?>" <?=$sector===$c['id']?'selected':''?>><?=h($c['code'].' · '.$c['name'])?></option><?php endforeach;?></select><select class="form-select" name="machine" aria-label="Filtrar por máquina"><option value="">Todas as máquinas</option><?php foreach($machines as$m):?><option value="<?=$m['id']?>" <?=$machine===$m['id']?'selected':''?>><?=h($m['code'].' · '.$m['name'])?></option><?php endforeach;?></select><button class="btn btn-outline-primary"><i class="bi bi-funnel"></i> Filtrar</button></form>
<section class="operations-list-card" aria-labelledby="operations-list-title"><div class="operations-card-heading"><div><h2 id="operations-list-title">Catálogo de operações</h2><span><?=count($rows)?> <?=count($rows)===1?'resultado':'resultados'?></span></div></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Código</th><th>Operação</th><th>Tipo</th><th>Setor</th><th>Máquinas</th><th>Estado</th><th><span class="visually-hidden">Ações</span></th></tr></thead><tbody><?php foreach($rows as$r):?><tr><td><span class="operation-code"><?=h($r['code'])?></span></td><td><strong><?=h($r['name'])?></strong></td><td><?=h((string)($operationTypeLabels[$r['operation_type']]??$r['operation_type']))?></td><td><?=h((string)($r['work_center_name']?:'—'))?></td><td class="text-muted"><?=h((string)($r['machines']?:'—'))?></td><td><span class="operation-status <?=$r['is_active']?'is-active':'is-inactive'?>"><i></i><?=$r['is_active']?'Ativa':'Inativa'?></span></td><td class="text-end"><a class="btn btn-sm btn-light" href="?id=<?=$r['id']?>" aria-label="Editar <?=h($r['name'])?>"><i class="bi bi-pencil"></i> Editar</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7" class="operations-empty"><i class="bi bi-inboxes"></i><strong>Nenhuma operação encontrada</strong><span>Altere os filtros ou crie uma nova operação.</span></td></tr><?php endif;?></tbody></table></div></section>
<?php if($edit!==null):?><section class="operation-form-card" aria-labelledby="operation-form-title"><div class="operation-form-heading"><div class="operation-form-icon"><i class="bi bi-sliders"></i></div><div><span><?=empty($edit['id'])?'Novo registo':'Configuração'?></span><h2 id="operation-form-title"><?=empty($edit['id'])?'Nova':'Editar'?> operação</h2></div></div><form method="post" enctype="multipart/form-data" class="operation-form"><?=csrf_input()?><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
<fieldset class="operation-section"><legend><span>1</span><div>Identificação<small>Dados base da operação</small></div></legend><div class="row g-3"><div class="col-lg-2 col-md-4"><label class="form-label">Código <em>*</em></label><input class="form-control" name="code" required value="<?=h((string)($edit['code']??''))?>"></div><div class="col-lg-4 col-md-8"><label class="form-label">Nome <em>*</em></label><input class="form-control" name="name" required value="<?=h((string)($edit['name']??''))?>"></div><div class="col-lg-3 col-md-6"><label class="form-label">Tipo</label><select class="form-select" name="operation_type"><?php foreach($operationTypeLabels as$v=>$l):?><option value="<?=$v?>" <?=($edit['operation_type']??'production')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-lg-3 col-md-6"><label class="form-label">Setor</label><select class="form-select" name="work_center_id"><option value="">— Sem setor —</option><?php foreach($centers as$c):?><option value="<?=$c['id']?>" <?=(int)($edit['default_work_center_id']??0)===$c['id']?'selected':''?>><?=h($c['code'].' · '.$c['name'])?></option><?php endforeach;?></select></div><div class="col-lg-5"><label class="form-label">Descrição</label><textarea class="form-control" name="description" rows="5"><?=h((string)($edit['description']??''))?></textarea></div><div class="col-lg-7"><label class="form-label">Instrução de trabalho</label><div class="operation-editor"><div class="operation-editor-toolbar" role="toolbar" aria-label="Formatação da instrução"><button type="button" data-editor-command="bold" title="Negrito"><strong>B</strong></button><button type="button" data-editor-command="italic" title="Itálico"><em>I</em></button><button type="button" data-editor-command="insertUnorderedList" title="Lista com marcadores"><i class="bi bi-list-ul"></i></button><button type="button" data-editor-command="insertOrderedList" title="Lista numerada"><i class="bi bi-list-ol"></i></button></div><div id="work-instruction-editor" contenteditable="true" role="textbox" aria-multiline="true"><?=$service->sanitizeInstructionHtml((string)($edit['default_instructions']??''))?></div><textarea id="work-instruction-html" name="default_instructions" hidden><?=h((string)($edit['default_instructions']??''))?></textarea></div></div></div></fieldset>
<fieldset class="operation-section"><legend><span>2</span><div>Capacidade<small>Predefinições independentes do artigo</small></div></legend><div class="operation-metric-grid"><label><span>Unidade de produção</span><select class="form-select" name="production_unit"><?php foreach($productionUnitLabels as$v=>$l):?><option value="<?=h($v)?>" <?=$currentProductionUnit===$v?'selected':''?>><?=h($l)?></option><?php endforeach;?></select></label><label><span>Operadores mínimos</span><input class="form-control" type="number" min="1" name="min_operators" value="<?=h((string)($edit['min_operators']??1))?>"></label></div><p class="form-text mb-0 mt-2">Os tempos de preparação e de ciclo são definidos no routing de cada artigo.</p></fieldset>
<fieldset class="operation-section"><legend><span>3</span><div>Recursos e recolha<small>Máquinas autorizadas e dados obrigatórios</small></div></legend><label class="form-label">Máquinas compatíveis</label><div class="operation-options-grid"><?php foreach($machines as$m):?><label class="operation-option"><input class="form-check-input" type="checkbox" name="machine_ids[]" value="<?=$m['id']?>" <?=in_array($m['id'],$selected,true)?'checked':''?>><span><strong><?=h($m['code'])?></strong><small><?=h($m['name'])?></small></span></label><?php endforeach;?><?php if(!$machines):?><span class="text-muted">Não existem máquinas ativas.</span><?php endif;?></div><div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Máquina predefinida</label><select class="form-select" name="default_machine_id"><option value="">— Sem predefinição —</option><?php foreach($machines as$m):?><option value="<?=$m['id']?>" <?=$defaultMachineId===(int)$m['id']?'selected':''?>><?=h($m['code'].' · '.$m['name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label" for="default-confirmation-required">Validação da instrução</label><select class="form-select" id="default-confirmation-required" name="default_confirmation_required"><option value="1" <?=!isset($edit['default_confirmation_required'])||(int)$edit['default_confirmation_required']===1?'selected':''?>>Validação obrigatória</option><option value="0" <?=isset($edit['default_confirmation_required'])&&(int)$edit['default_confirmation_required']===0?'selected':''?>>Sem validação obrigatória</option></select></div></div><div class="operation-switches"><?php foreach(['requires_good_quantity'=>['Quantidade boa','bi-check2-circle'],'requires_waste'=>['Refugo','bi-recycle'],'requires_waste_reason'=>['Motivo de refugo','bi-chat-left-text'],'requires_quality'=>['Controlo de qualidade','bi-patch-check'],'is_active'=>['Operação ativa','bi-toggle-on']]as$f=>$config):?><input type="hidden" name="<?=$f?>" value="0"><label><input class="form-check-input" type="checkbox" name="<?=$f?>" value="1" <?=!isset($edit[$f])||$edit[$f]?'checked':''?>><i class="bi <?=$config[1]?>"></i><span><?=$config[0]?></span></label><?php endforeach;?></div></fieldset>
<fieldset class="operation-section"><legend><span>4</span><div>Checklist e documentos<small>Controlo operacional e apoio visual</small></div></legend><div class="row g-3"><div class="col-md-6"><label class="form-label">Checklist da operação</label><select class="form-select" id="operation-checklist" name="checklist_template_id"><option value="0">Sem checklist</option><?php foreach($checklistTemplates as$template):?><option value="<?=(int)$template['id']?>" <?=(int)($edit['checklist_template_id']??0)===(int)$template['id']?'selected':''?>><?=h($template['name'])?> (<?=(int)$template['items_count']?> campos)</option><?php endforeach;?></select><div class="form-text">Pode gerir os modelos em <a href="checklists.php">Checklists</a>.</div></div><div class="col-md-6" id="checklist-timing-field"><label class="form-label">Momento de preenchimento</label><select class="form-select" name="checklist_timing"><option value="start" <?=($edit['checklist_timing']??'start')==='start'?'selected':''?>>No início da operação</option><option value="end" <?=($edit['checklist_timing']??'')==='end'?'selected':''?>>No fim da operação</option><option value="first" <?=($edit['checklist_timing']??'')==='first'?'selected':''?>>Na primeira vez do colaborador nesta operação da OF</option></select></div><div class="col-12"><label class="operation-upload"><i class="bi bi-cloud-arrow-up"></i><span><strong>Adicionar instruções visuais</strong><small>PDF, imagem ou vídeo · máximo 50 MB por ficheiro</small></span><input type="file" name="instruction_files[]" accept=".pdf,.jpg,.jpeg,.png,.webp,.gif,.mp4,.webm,.ogv" multiple></label></div><?php if($documents):?><div class="col-12"><div class="operation-files"><?php foreach($documents as$document):?><div><i class="bi bi-paperclip"></i><a href="<?=h($document['file_url'])?>" target="_blank" rel="noopener"><?=h($document['title'])?></a><button type="submit" name="action" value="delete_instruction_file" formaction="?id=<?=(int)$edit['id']?>&document_id=<?=(int)$document['id']?>" formnovalidate aria-label="Remover <?=h($document['title'])?>"><i class="bi bi-x-lg"></i></button></div><?php endforeach;?></div></div><?php endif;?><div class="col-12"><label class="form-label">Observações internas</label><textarea class="form-control" name="notes" rows="3" placeholder="Notas adicionais para planeamento ou configuração..."><?=h((string)($edit['notes']??''))?></textarea></div></div></fieldset>
<div class="operation-form-actions"><a class="btn btn-light" href="erp_operations.php">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check2"></i> Guardar operação</button></div></form></section><?php endif;?></div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var editor = document.getElementById('work-instruction-editor');
    var input = document.getElementById('work-instruction-html');
    var checklist = document.getElementById('operation-checklist');
    var timing = document.getElementById('checklist-timing-field');
    if (checklist && timing) {
        var toggleTiming = function () { timing.classList.toggle('d-none', checklist.value === '0'); };
        checklist.addEventListener('change', toggleTiming); toggleTiming();
    }
    if (!editor || !input) return;
    document.querySelectorAll('[data-editor-command]').forEach(function (button) {
        button.addEventListener('click', function () {
            editor.focus();
            document.execCommand(button.dataset.editorCommand, false, null);
            input.value = editor.innerHTML;
        });
    });
    editor.addEventListener('input', function () { input.value = editor.innerHTML; });
    editor.closest('form').addEventListener('submit', function () { input.value = editor.innerHTML; });
});
</script>
<?php require __DIR__.'/partials/footer.php'; ?>
