<?php
require_once __DIR__ . '/hr_organization_lib.php'; require_login(); gt_run_org_migrations($pdo); $userId=(int)$_SESSION['user_id']; if(!gt_is_hr_allowed($pdo,$userId)){http_response_code(403); exit('Acesso reservado a RH.');}
$flashSuccess=$flashError=null; if(isset($_GET['pdf'])){ $id=(int)$_GET['pdf']; $st=$pdo->prepare('SELECT ds.*,d.name department_name,u.name responsible_name,b.name backup_name FROM company_duty_sheets ds LEFT JOIN hr_departments d ON d.id=ds.department_id LEFT JOIN users u ON u.id=ds.responsible_user_id LEFT JOIN users b ON b.id=ds.backup_user_id WHERE ds.id=?');$st->execute([$id]);$d=$st->fetch(PDO::FETCH_ASSOC); if(!$d){http_response_code(404);exit('Não encontrado');} header('Content-Type:text/html; charset=UTF-8'); echo '<!doctype html><title>Caderno</title><style>body{font-family:Arial;margin:40px}h1{color:#2D69A1}.sec{border-top:1px solid #ccc;padding-top:12px;margin-top:12px}@media print{button{display:none}}</style><button onclick="print()">Imprimir / Guardar PDF</button><h1>'.h($d['title']).'</h1><p><strong>Departamento:</strong> '.h($d['department_name']).' · <strong>Responsável:</strong> '.h($d['responsible_name']).' · <strong>Substituto:</strong> '.h($d['backup_name']?:'Sem substituto').'</p>'; foreach(['purpose'=>'Objetivo','responsibilities'=>'Responsabilidades','daily_tasks'=>'Tarefas diárias','weekly_tasks'=>'Tarefas semanais','monthly_tasks'=>'Tarefas mensais','annual_tasks'=>'Tarefas anuais','authority_text'=>'Limites de autoridade','kpis'=>'Indicadores/KPI','systems_text'=>'Sistemas','risks'=>'Riscos','notes'=>'Observações'] as $k=>$l) echo '<div class="sec"><h2>'.h($l).'</h2><p>'.nl2br(h($d[$k]??'')).'</p></div>'; echo '<footer>Gerado em '.date('d/m/Y H:i').' · Página <span class="page"></span></footer>'; exit; }
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!validate_csrf_or_abort(false))$flashError='Pedido inválido.'; else try{ $action=$_POST['action']??'save'; $id=(int)($_POST['id']??0); if($action==='delete'){$pdo->prepare('UPDATE company_duty_sheets SET deleted_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=?')->execute([$userId,$id]);gt_org_audit($pdo,$userId,'hr.job_descriptions.delete','company_duty_sheets',$id,[],[]);$flashSuccess='Caderno eliminado.';} elseif(in_array($action,['validate','archive'],true)){$status=$action==='validate'?'validated':'archived';$pdo->prepare('UPDATE company_duty_sheets SET status=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$status,$userId,$id]);gt_org_audit($pdo,$userId,'hr.job_descriptions.'.$action,'company_duty_sheets',$id,[],['status'=>$status]);$flashSuccess='Estado atualizado.';} else { $data=[trim($_POST['title']??''),trim($_POST['job_role']??''),(int)($_POST['department_id']??0)?:null,(int)($_POST['responsible_user_id']??0)?:null,(int)($_POST['backup_user_id']??0)?:null,(int)($_POST['secondary_backup_user_id']??0)?:null,trim($_POST['status']??'draft'),trim($_POST['review_date']??'')?:null,trim($_POST['purpose']??''),trim($_POST['responsibilities']??''),trim($_POST['daily_tasks']??''),trim($_POST['weekly_tasks']??''),trim($_POST['monthly_tasks']??''),trim($_POST['annual_tasks']??''),trim($_POST['authority_text']??''),trim($_POST['kpis']??''),trim($_POST['systems_text']??''),trim($_POST['risks']??''),trim($_POST['notes']??'')]; if($id){$old=$pdo->prepare('SELECT * FROM company_duty_sheets WHERE id=?');$old->execute([$id]);$pdo->prepare('UPDATE company_duty_sheets SET title=?,job_role=?,department_id=?,responsible_user_id=?,backup_user_id=?,secondary_backup_user_id=?,status=?,review_date=?,purpose=?,responsibilities=?,daily_tasks=?,weekly_tasks=?,monthly_tasks=?,annual_tasks=?,authority_text=?,kpis=?,systems_text=?,risks=?,notes=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute(array_merge($data,array($userId,$id))); gt_org_audit($pdo,$userId,'hr.job_descriptions.update','company_duty_sheets',$id,$old->fetch(PDO::FETCH_ASSOC)?:[],$_POST);} else {$pdo->prepare('INSERT INTO company_duty_sheets(title,job_role,department_id,responsible_user_id,backup_user_id,secondary_backup_user_id,status,review_date,purpose,responsibilities,daily_tasks,weekly_tasks,monthly_tasks,annual_tasks,authority_text,kpis,systems_text,risks,notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute(array_merge($data,array($userId,$userId))); gt_org_audit($pdo,$userId,'hr.job_descriptions.create','company_duty_sheets',(int)$pdo->lastInsertId(),[],$_POST);} $flashSuccess='Caderno guardado.'; }}catch(Throwable $e){$flashError='Erro: '.$e->getMessage();}}
$deps=$pdo->query('SELECT * FROM hr_departments ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$people=$pdo->query('SELECT id,name,is_active FROM users ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$q=trim($_GET['q']??'');$status=trim($_GET['status']??'');$selectedResponsibleId=(int)($_GET['responsible_user_id']??0);$where=['ds.deleted_at IS NULL'];$args=[]; if($q!==''){$where[]='(ds.title LIKE ? OR ds.job_role LIKE ? OR ds.purpose LIKE ? OR ds.responsibilities LIKE ? OR ds.systems_text LIKE ? OR u.name LIKE ?)';for($i=0;$i<6;$i++){$args[]="%$q%";}} if($status!==''){$where[]='ds.status=?';$args[]=$status;} $st=$pdo->prepare('SELECT ds.*,d.name department_name,u.name responsible_name,b.name backup_name FROM company_duty_sheets ds LEFT JOIN hr_departments d ON d.id=ds.department_id LEFT JOIN users u ON u.id=ds.responsible_user_id LEFT JOIN users b ON b.id=ds.backup_user_id WHERE '.implode(' AND ',$where).' ORDER BY ds.updated_at DESC');$st->execute($args);$rows=$st->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Cadernos de encargos'; require __DIR__.'/partials/header.php'; ?>
<?php
$validatedCount=0;$noSubstituteCount=0;$reviewDueCount=0;
foreach($rows as $cardRow){if($cardRow['status']==='validated'){$validatedCount++;}if(empty($cardRow['backup_user_id'])){$noSubstituteCount++;}if(!empty($cardRow['review_date'])&&$cardRow['review_date']<date('Y-m-d')){$reviewDueCount++;}}
$statusLabels=['draft'=>'Rascunho','review'=>'Em revisão','validated'=>'Validado','archived'=>'Arquivado'];
$statusClasses=['draft'=>'secondary','review'=>'warning','validated'=>'success','archived'=>'dark'];
$stats=[['label'=>'Total de cadernos','value'=>count($rows),'icon'=>'bi-journal-text','tone'=>'blue'],['label'=>'Validados','value'=>$validatedCount,'icon'=>'bi-patch-check','tone'=>'green'],['label'=>'Sem substituto','value'=>$noSubstituteCount,'icon'=>'bi-person-exclamation','tone'=>'amber'],['label'=>'Revisão vencida','value'=>$reviewDueCount,'icon'=>'bi-calendar-x','tone'=>'red']];
?>
<div class="container-fluid py-4 duty-sheet-page">
    <?php if($flashSuccess):?><div class="alert alert-success shadow-sm border-0"><i class="bi bi-check-circle me-2"></i><?=h($flashSuccess)?></div><?php endif;?>
    <?php if($flashError):?><div class="alert alert-danger shadow-sm border-0"><i class="bi bi-exclamation-triangle me-2"></i><?=h($flashError)?></div><?php endif;?>

    <section class="duty-hero mb-4">
        <div><span class="duty-eyebrow">Pessoas e responsabilidades</span><h1>Organize funções com clareza</h1><p>Centralize objetivos, tarefas, substituições e indicadores de cada função da organização.</p></div>
        <button class="btn btn-success duty-hero-action" type="button" data-bs-toggle="collapse" data-bs-target="#dutySheetForm" aria-expanded="false"><i class="bi bi-plus-lg me-2"></i>Novo caderno</button>
    </section>

    <form class="card duty-filter-card mb-3" method="get">
        <div class="card-body"><div class="row g-3 align-items-end">
            <div class="col-lg"><label class="form-label" for="duty-search">Pesquisar</label><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input id="duty-search" class="form-control" type="search" name="q" value="<?=h($q)?>" placeholder="Função, responsabilidade, pessoa ou sistema"></div></div>
            <div class="col-lg-3"><label class="form-label" for="duty-status">Estado</label><select id="duty-status" class="form-select" name="status"><option value="">Todos os estados</option><?php foreach($statusLabels as $k=>$v):?><option value="<?=h($k)?>" <?=$status===$k?'selected':''?>><?=h($v)?></option><?php endforeach;?></select></div>
            <div class="col-lg-auto d-flex gap-2"><button class="btn btn-primary px-4"><i class="bi bi-funnel me-2"></i>Filtrar</button><?php if($q!==''||$status!==''):?><a class="btn btn-outline-secondary" href="hr_job_descriptions.php" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif;?></div>
        </div></div>
    </form>

    <div class="row g-3 mb-4"><?php foreach($stats as $stat):?><div class="col-sm-6 col-xl-3"><div class="card duty-stat-card h-100"><div class="card-body"><span class="duty-stat-icon is-<?=h($stat['tone'])?>"><i class="bi <?=h($stat['icon'])?>"></i></span><div><small><?=h($stat['label'])?></small><strong><?=$stat['value']?></strong></div></div></div></div><?php endforeach;?></div>

    <div class="collapse mb-4" id="dutySheetForm"><div class="card duty-form-card"><div class="card-header"><div><span class="duty-eyebrow">Novo registo</span><h2>Criar caderno de encargos</h2><p>Preencha a identificação da função e detalhe as suas responsabilidades.</p></div><button type="button" class="btn-close" data-bs-toggle="collapse" data-bs-target="#dutySheetForm" aria-label="Fechar"></button></div><div class="card-body">
        <form method="post" class="row g-3"><?=csrf_input()?><input type="hidden" name="action" value="save">
            <div class="col-12"><h3 class="duty-form-section"><i class="bi bi-briefcase"></i>Identificação</h3></div>
            <div class="col-lg-4"><label class="form-label">Título / função <span class="text-danger">*</span></label><input required class="form-control" name="title" placeholder="Ex.: Responsável de produção"></div>
            <div class="col-lg-2"><label class="form-label">Função</label><input class="form-control" name="job_role" placeholder="Designação interna"></div>
            <div class="col-lg-3"><label class="form-label">Departamento</label><select class="form-select" name="department_id"><option value="">Selecionar</option><?php foreach($deps as $d):?><option value="<?=$d['id']?>"><?=h($d['name'])?></option><?php endforeach;?></select></div>
            <div class="col-lg-3"><label class="form-label">Estado</label><select class="form-select" name="status"><?php foreach($statusLabels as $k=>$v):?><option value="<?=h($k)?>"><?=h($v)?></option><?php endforeach;?></select></div>
            <div class="col-12"><h3 class="duty-form-section"><i class="bi bi-people"></i>Responsáveis e revisão</h3></div>
            <?php foreach(['responsible_user_id'=>'Responsável','backup_user_id'=>'Substituto principal','secondary_backup_user_id'=>'2.º substituto'] as $n=>$l):?><div class="col-lg-3"><label class="form-label"><?=h($l)?></label><select class="form-select" name="<?=h($n)?>"><option value="">Selecionar</option><?php foreach($people as $p):?><option value="<?=$p['id']?>" <?=$n==='responsible_user_id'&&$selectedResponsibleId===(int)$p['id']?'selected':''?>><?=h($p['name'].((int)$p['is_active']!==1?' (inativo)':''))?></option><?php endforeach;?></select></div><?php endforeach;?><div class="col-lg-3"><label class="form-label">Próxima revisão</label><input class="form-control" type="date" name="review_date"></div>
            <div class="col-12"><h3 class="duty-form-section"><i class="bi bi-card-checklist"></i>Conteúdo da função</h3></div>
            <?php foreach(['purpose'=>'Objetivo','responsibilities'=>'Responsabilidades principais','daily_tasks'=>'Tarefas diárias','weekly_tasks'=>'Tarefas semanais','monthly_tasks'=>'Tarefas mensais','annual_tasks'=>'Tarefas anuais','authority_text'=>'Decisões e limites','kpis'=>'Indicadores / KPI','systems_text'=>'Sistemas utilizados','risks'=>'Riscos','notes'=>'Observações'] as $n=>$l):?><div class="col-lg-6"><label class="form-label"><?=h($l)?></label><textarea class="form-control" rows="3" name="<?=h($n)?>" placeholder="Descreva <?=h(mb_strtolower($l))?>..."></textarea></div><?php endforeach;?><div class="col-12 d-flex justify-content-end gap-2 pt-2"><button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#dutySheetForm">Cancelar</button><button class="btn btn-primary px-4"><i class="bi bi-check2 me-2"></i>Guardar caderno</button></div>
        </form>
    </div></div></div>

    <div class="d-flex justify-content-between align-items-end mb-3"><div><span class="duty-eyebrow">Biblioteca</span><h2 class="h4 fw-bold mb-0">Cadernos de encargos</h2></div><span class="text-muted small"><?=count($rows)?> <?=count($rows)===1?'resultado':'resultados'?></span></div>
    <?php if(!$rows):?><div class="card duty-empty"><div class="card-body"><span><i class="bi bi-journal-plus"></i></span><h3>Ainda não existem cadernos</h3><p><?=($q!==''||$status!=='')?'Não foram encontrados resultados para os filtros selecionados.':'Crie o primeiro caderno para documentar uma função da organização.'?></p><?php if($q!==''||$status!==''):?><a class="btn btn-outline-primary" href="hr_job_descriptions.php">Limpar filtros</a><?php else:?><button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#dutySheetForm">Criar primeiro caderno</button><?php endif;?></div></div><?php else:?><div class="row g-3"><?php foreach($rows as $r): $risks=gt_duty_risks($r);$rowStatus=$r['status']??'draft';?><div class="col-xl-6"><article class="card duty-record-card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-start gap-3"><div><span class="badge text-bg-<?=h($statusClasses[$rowStatus]??'secondary')?>"><?=h($statusLabels[$rowStatus]??$rowStatus)?></span><h3><?=h($r['title'])?></h3><p class="duty-role"><?=h($r['job_role']?:($r['department_name']?:'Sem departamento'))?></p></div><a class="btn btn-light border btn-sm" href="?pdf=<?=$r['id']?>" target="_blank" title="Abrir versão para impressão"><i class="bi bi-file-earmark-pdf me-1"></i>PDF</a></div><p class="duty-purpose"><?=h($r['purpose']?:'Sem objetivo definido.')?></p><div class="duty-people-grid"><div><i class="bi bi-person-check"></i><span>Responsável<strong><?=h($r['responsible_name']?:'Por definir')?></strong></span></div><div><i class="bi bi-person-up"></i><span>Na ausência<strong><?=h($r['backup_name']?:'Sem substituto')?></strong></span></div></div><?php if(!empty($r['responsibilities'])):?><div class="duty-responsibilities"><span>Principais responsabilidades</span><p><?=nl2br(h($r['responsibilities']))?></p></div><?php endif;?><div class="duty-record-footer"><div><span><i class="bi bi-calendar3"></i> Revisão: <?=h($r['review_date']?date('d/m/Y',strtotime($r['review_date'])):'Por definir')?></span><?php if($risks):?><span class="text-danger"><i class="bi bi-exclamation-triangle"></i> <?=h(implode(', ',$risks))?></span><?php endif;?></div><form method="post" class="d-flex gap-1"><?=csrf_input()?><input type="hidden" name="id" value="<?=$r['id']?>"><?php if($rowStatus!=='validated'):?><button name="action" value="validate" class="btn btn-outline-success btn-sm"><i class="bi bi-check2-circle"></i><span> Validar</span></button><?php endif;?><button name="action" value="archive" class="btn btn-outline-warning btn-sm"><i class="bi bi-archive"></i><span> Arquivar</span></button><button name="action" value="delete" class="btn btn-outline-danger btn-sm" onclick="return confirm('Eliminar este caderno?')"><i class="bi bi-trash"></i><span class="visually-hidden"> Eliminar</span></button></form></div></div></article></div><?php endforeach;?></div><?php endif;?>
</div>
<?php require __DIR__.'/partials/footer.php'; ?>
