<?php
require_once __DIR__ . '/hr_organization_lib.php'; require_login(); gt_run_org_migrations($pdo);
$userId=(int)$_SESSION['user_id']; if(!gt_is_hr_allowed($pdo,$userId)){http_response_code(403); exit('Acesso reservado a RH.');}
$flashSuccess=$flashError=null;
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!validate_csrf_or_abort(false)) $flashError='Pedido inválido.'; else { $id=(int)($_POST['user_id']??0); $mgr=(int)($_POST['manager_user_id']??0)?:null; if(!gt_prevents_cycle($pdo,$id,$mgr)) $flashError='Hierarquia circular impedida.'; else { $old=$pdo->prepare('SELECT manager_user_id, job_title, department, schedule_id, capacity_percent FROM users WHERE id=?'); $old->execute([$id]); $before=$old->fetch(PDO::FETCH_ASSOC)?:[]; $stmt=$pdo->prepare('UPDATE users SET manager_user_id=?, job_title=?, department=?, schedule_id=?, capacity_percent=?, professional_phone=?, professional_email=?, hr_notes=? WHERE id=?'); $stmt->execute([$mgr, trim($_POST['job_title']??''), trim($_POST['department']??''), (int)($_POST['schedule_id']??0)?:null, max(0,min(100,(int)($_POST['capacity_percent']??100))), trim($_POST['professional_phone']??''), trim($_POST['professional_email']??''), trim($_POST['hr_notes']??''), $id]); gt_org_audit($pdo,$userId,'hr.organogram.update','users',$id,$before,$_POST); $flashSuccess='Organograma atualizado.'; } } }
$deps=$pdo->query('SELECT * FROM hr_departments ORDER BY name')->fetchAll(PDO::FETCH_ASSOC); $schedules=$pdo->query('SELECT * FROM hr_schedules ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);
$dep=trim($_GET['department']??''); $sch=(int)($_GET['schedule_id']??0); $q=trim($_GET['q']??''); $show=(int)($_GET['inactive']??0);
$where=[];$args=[]; if(!$show)$where[]='COALESCE(is_active,1)=1'; if($dep!==''){$where[]='department=?';$args[]=$dep;} if($sch>0){$where[]='schedule_id=?';$args[]=$sch;} if($q!==''){$where[]='(name LIKE ? OR job_title LIKE ? OR access_profile LIKE ?)';$args[]="%$q%";$args[]="%$q%";$args[]="%$q%";}
$sql='SELECT u.*, s.name schedule_name, s.start_time, s.end_time, s.weekdays_mask FROM users u LEFT JOIN hr_schedules s ON s.id=u.schedule_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY COALESCE(manager_user_id,0), name'; $st=$pdo->prepare($sql);$st->execute($args);$people=$st->fetchAll(PDO::FETCH_ASSOC); $byMgr=[]; foreach($people as $p){$byMgr[(int)($p['manager_user_id']??0)][]=$p;}
$shiftStats=[]; foreach($people as $p){$sid=(int)($p['schedule_id']??0); if(!$sid)continue; if(!isset($shiftStats[$sid]))$shiftStats[$sid]=['schedule'=>$p['schedule_name'],'start'=>$p['start_time'],'end'=>$p['end_time'],'fte'=>0,'people'=>0]; if((int)($p['is_active']??1)===1){$shiftStats[$sid]['people']++; $shiftStats[$sid]['fte']+=(int)($p['capacity_percent']??100)/100;}}
$pageTitle='Organograma'; require __DIR__.'/partials/header.php'; ?>
<div class="container-fluid py-4"><div class="d-flex justify-content-between mb-3"><h2 class="h4">Organograma</h2></div><?php if($flashSuccess):?><div class="alert alert-success"><?=h($flashSuccess)?></div><?php endif;?><?php if($flashError):?><div class="alert alert-danger"><?=h($flashError)?></div><?php endif;?>
<form class="card card-body mb-3"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="q" value="<?=h($q)?>" placeholder="Pesquisar por nome ou função"></div><div class="col-md-3"><select class="form-select" name="department"><option value="">Todos os departamentos</option><?php foreach($deps as $d):?><option <?=$dep===$d['name']?'selected':''?>><?=h($d['name'])?></option><?php endforeach;?></select></div><div class="col-md-3"><select class="form-select" name="schedule_id"><option value="">Todos os turnos</option><?php foreach($schedules as $s):?><option value="<?=$s['id']?>" <?=$sch===(int)$s['id']?'selected':''?>><?=h($s['name'])?></option><?php endforeach;?></select></div><div class="col"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="inactive" value="1" <?=$show?'checked':''?>> Mostrar inativos</label></div><div class="col-auto"><button class="btn btn-primary">Filtrar</button></div></div></form>
<div class="row g-3 mb-3"><?php foreach($shiftStats as $x): $daily=$x['fte']*8;?><div class="col-md-3"><div class="card h-100"><div class="card-body"><span class="text-muted small">Turno</span><h3 class="h6"><?=h($x['schedule'])?></h3><div><?=h($x['start'].' - '.$x['end'])?></div><strong><?=h((string)$x['people'])?></strong> pessoas · <strong><?=number_format($x['fte'],2,',','.')?></strong> FTE<br><strong><?=number_format($daily,1,',','.')?> h</strong> capacidade/dia · <strong><?=number_format($daily*5,1,',','.')?> h</strong> semana</div></div></div><?php endforeach;?></div>
<div class="row g-3"><div class="col-lg-8"><div class="card"><div class="card-body"><h3 class="h5">Estrutura hierárquica</h3><?php $level=0; $render=function($mgr) use (&$render,$byMgr,&$level,$people,$schedules){ if(empty($byMgr[$mgr])) return; $level++; echo '<h4 class="h6 text-primary mt-3">Nível '.(int)$level.'</h4><div class="row g-2">'; foreach($byMgr[$mgr] as $p){ echo '<div class="col-md-4"><button class="card card-body text-start w-100" data-bs-toggle="collapse" data-bs-target="#person'.(int)$p['id'].'"><strong>'.h($p['name']).'</strong><span>'.h($p['job_title'] ?: $p['access_profile']).'</span><small>'.h(($p['department']?:'Sem departamento').' · '.($p['schedule_name']?:'Sem turno').' · '.($p['capacity_percent']??100).'%').'</small></button></div>'; } echo '</div>'; foreach($byMgr[$mgr] as $p){ $render((int)$p['id']); } $level--; }; $render(0); ?></div></div></div><div class="col-lg-4"><?php foreach($people as $p):?><div class="collapse" id="person<?=$p['id']?>"><div class="card card-body mb-2"><h3 class="h5"><?=h($p['name'])?></h3><form method="post" class="vstack gap-2"><?=csrf_input()?><input type="hidden" name="user_id" value="<?=$p['id']?>"><input class="form-control" name="job_title" value="<?=h($p['job_title']??'')?>" placeholder="Função"><input class="form-control" name="department" value="<?=h($p['department']??'')?>" placeholder="Departamento"><select class="form-select" name="manager_user_id"><option value="">Sem superior</option><?php foreach($people as $m): if($m['id']==$p['id'])continue;?><option value="<?=$m['id']?>" <?=(int)($p['manager_user_id']??0)===(int)$m['id']?'selected':''?>><?=h($m['name'])?></option><?php endforeach;?></select><select class="form-select" name="schedule_id"><option value="">Sem turno</option><?php foreach($schedules as $s):?><option value="<?=$s['id']?>" <?=(int)($p['schedule_id']??0)===(int)$s['id']?'selected':''?>><?=h($s['name'])?></option><?php endforeach;?></select><input class="form-control" type="number" min="0" max="100" name="capacity_percent" value="<?=h((string)($p['capacity_percent']??100))?>"><input class="form-control" name="professional_email" value="<?=h($p['professional_email']??'')?>" placeholder="Email profissional"><input class="form-control" name="professional_phone" value="<?=h($p['professional_phone']??'')?>" placeholder="Telefone"><textarea class="form-control" name="hr_notes" placeholder="Notas"><?=h($p['hr_notes']??'')?></textarea><button class="btn btn-primary">Guardar</button><a class="btn btn-outline-secondary" href="hr_job_descriptions.php?responsible_user_id=<?=$p['id']?>">Caderno</a><a class="btn btn-outline-secondary" href="hr_skills.php?user_id=<?=$p['id']?>">Competências</a></form></div></div><?php endforeach;?></div></div></div><?php require __DIR__.'/partials/footer.php'; ?>
