<?php
require_once __DIR__ . '/helpers.php';

function gt_column_exists(PDO $pdo, string $table, string $column): bool { foreach ($pdo->query('PRAGMA table_info(' . $table . ')')->fetchAll(PDO::FETCH_ASSOC) as $r) { if (($r['name'] ?? '') === $column) return true; } return false; }
function gt_table_exists(PDO $pdo, string $table): bool { $s=$pdo->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1"); $s->execute([$table]); return (bool)$s->fetchColumn(); }
function gt_add_column(PDO $pdo, string $table, string $column, string $def) { if (!gt_column_exists($pdo,$table,$column)) $pdo->exec('ALTER TABLE '.$table.' ADD COLUMN '.$column.' '.$def); }
function gt_org_audit(PDO $pdo, int $userId, string $action, string $entity, int $entityId, array $old=[], array $new=[]) { $stmt=$pdo->prepare('INSERT INTO audit_logs(user_id, action, details_json) VALUES (?,?,?)'); $stmt->execute([$userId, $action, json_encode(['entity'=>$entity,'id'=>$entityId,'old'=>$old,'new'=>$new], JSON_UNESCAPED_UNICODE)]); }

function gt_run_org_migrations(PDO $pdo) {
    $pdo->exec('PRAGMA foreign_keys = ON');
    gt_add_column($pdo,'users','manager_user_id','INTEGER NULL'); gt_add_column($pdo,'users','capacity_percent','INTEGER NOT NULL DEFAULT 100'); gt_add_column($pdo,'users','employee_number','TEXT NULL'); gt_add_column($pdo,'users','job_title','TEXT NULL'); gt_add_column($pdo,'users','professional_phone','TEXT NULL'); gt_add_column($pdo,'users','professional_email','TEXT NULL'); gt_add_column($pdo,'users','hr_notes','TEXT NULL');
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_users_manager_user_id ON users(manager_user_id)'); $pdo->exec('CREATE INDEX IF NOT EXISTS idx_users_department_schedule ON users(department, schedule_id)');
    $pdo->exec("CREATE TABLE IF NOT EXISTS erp_machines (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, brand TEXT, model TEXT, serial_number TEXT, manufacturing_year INTEGER, department_id INTEGER, location TEXT, owner_user_id INTEGER, status TEXT NOT NULL DEFAULT 'operational' CHECK(status IN ('operational','maintenance','broken','stopped','inactive','limited')), criticality TEXT NOT NULL DEFAULT 'medium' CHECK(criticality IN ('low','medium','high','critical')), nominal_capacity TEXT, capacity_unit TEXT, cycle_time TEXT, cycle_time_unit TEXT, operators_required INTEGER NOT NULL DEFAULT 0 CHECK(operators_required >= 0), supplier TEXT, service_provider TEXT, purchase_date TEXT, next_maintenance_date TEXT, manual_url TEXT, characteristics TEXT, risks TEXT, limitations TEXT, notes TEXT, is_active INTEGER NOT NULL DEFAULT 1, created_by INTEGER, updated_by INTEGER, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME, FOREIGN KEY(department_id) REFERENCES hr_departments(id) ON DELETE SET NULL, FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL)");
    $machineColumns = array('capacity_unit TEXT','cycle_time_unit TEXT','supplier TEXT','characteristics TEXT','risks TEXT','limitations TEXT','deleted_at DATETIME'); foreach($machineColumns as $d){$parts=explode(' ',$d); $c=$parts[0]; gt_add_column($pdo,'erp_machines',$c,substr($d,strlen($c)+1));}
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_erp_machines_code ON erp_machines(code)'); $pdo->exec('CREATE INDEX IF NOT EXISTS idx_erp_machines_filters ON erp_machines(status, criticality, department_id, is_active)');
    $pdo->exec("CREATE TABLE IF NOT EXISTS erp_machine_attachments (id INTEGER PRIMARY KEY AUTOINCREMENT, machine_id INTEGER NOT NULL, original_name TEXT NOT NULL, file_path TEXT NOT NULL, mime_type TEXT, file_size INTEGER NOT NULL DEFAULT 0, uploaded_by INTEGER, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME, FOREIGN KEY(machine_id) REFERENCES erp_machines(id) ON DELETE CASCADE, FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL)");
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_erp_machine_attachments_machine ON erp_machine_attachments(machine_id, deleted_at)');
    $pdo->exec("CREATE TABLE IF NOT EXISTS hr_machine_competencies (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, machine_id INTEGER NOT NULL, level INTEGER NOT NULL DEFAULT 0 CHECK(level BETWEEN 0 AND 4), assessed_at TEXT, expiry_date TEXT, training TEXT, limitations TEXT, evidence TEXT, notes TEXT, assessed_by_user_id INTEGER, created_by INTEGER, updated_by INTEGER, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME, UNIQUE(user_id, machine_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(machine_id) REFERENCES erp_machines(id) ON DELETE CASCADE)");
    $competencyColumns = array('training TEXT','limitations TEXT','evidence TEXT','deleted_at DATETIME'); foreach($competencyColumns as $d){$parts=explode(' ',$d); $c=$parts[0]; gt_add_column($pdo,'hr_machine_competencies',$c,substr($d,strlen($c)+1));}
    $pdo->exec("CREATE TABLE IF NOT EXISTS company_duty_sheets (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, job_role TEXT, department_id INTEGER, responsible_user_id INTEGER, backup_user_id INTEGER, secondary_backup_user_id INTEGER, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','review','validated','archived','inactive')), review_date TEXT, purpose TEXT, responsibilities TEXT, daily_tasks TEXT, weekly_tasks TEXT, monthly_tasks TEXT, annual_tasks TEXT, authority_text TEXT, kpis TEXT, systems_text TEXT, risks TEXT, notes TEXT, created_by INTEGER, updated_by INTEGER, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME, FOREIGN KEY(department_id) REFERENCES hr_departments(id) ON DELETE SET NULL)");
    $dutyColumns = array('job_role TEXT','weekly_tasks TEXT','monthly_tasks TEXT','annual_tasks TEXT','risks TEXT','deleted_at DATETIME'); foreach($dutyColumns as $d){$parts=explode(' ',$d); $c=$parts[0]; gt_add_column($pdo,'company_duty_sheets',$c,substr($d,strlen($c)+1));}
    $pdo->exec('CREATE TABLE IF NOT EXISTS company_duty_sheet_machines (id INTEGER PRIMARY KEY AUTOINCREMENT, duty_sheet_id INTEGER NOT NULL, machine_id INTEGER NOT NULL, minimum_level INTEGER NOT NULL DEFAULT 3 CHECK(minimum_level BETWEEN 0 AND 4), notes TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(duty_sheet_id,machine_id), FOREIGN KEY(duty_sheet_id) REFERENCES company_duty_sheets(id) ON DELETE CASCADE, FOREIGN KEY(machine_id) REFERENCES erp_machines(id) ON DELETE CASCADE)');
}
function gt_is_hr_allowed(PDO $pdo,int $uid): bool { return can_access_hr_module($pdo,$uid); }
function gt_is_erp_allowed(PDO $pdo,array $u): bool { return (int)($u['is_admin']??0)===1 || in_array((string)($u['access_profile']??''), ['ERP','Admin','Gestão'], true); }
function gt_prevents_cycle(PDO $pdo, int $userId, int $managerId): bool { if (!$managerId) return true; if ($userId===$managerId) return false; $seen=[]; while($managerId){ if ($managerId===$userId || isset($seen[$managerId])) return false; $seen[$managerId]=1; $s=$pdo->prepare('SELECT manager_user_id FROM users WHERE id=?'); $s->execute([$managerId]); $managerId=(int)$s->fetchColumn(); } return true; }
function gt_duty_risks(array $d): array { $r=[]; if (empty($d['backup_user_id'])) $r[]='Sem substituto principal'; if (!empty($d['review_date']) && $d['review_date'] < date('Y-m-d')) $r[]='Revisão vencida'; return $r; }
