<?php
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/payroll_lib.php';
require_login();
$userId=(int)$_SESSION['user_id'];
if(!payroll_user_can($pdo,$userId,'payroll.view')){http_response_code(403);exit('Sem permissão para consultar Payroll.');}
$year=max(2000,min(2100,(int)($_REQUEST['year']??date('Y'))));$month=max(1,min(12,(int)($_REQUEST['month']??date('n'))));
$departmentId=(int)($_REQUEST['department_id']??0);$activeOnly=isset($_REQUEST['active_only'])||!isset($_REQUEST['year']);$selected=array_map('intval',(array)($_REQUEST['user_ids']??[]));
$flashSuccess=null;$flashError=null;
$runStmt=$pdo->prepare('SELECT * FROM payroll_runs WHERE payroll_year=? AND payroll_month=?');$runStmt->execute([$year,$month]);$run=$runStmt->fetch(PDO::FETCH_ASSOC);
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=(string)($_POST['action']??'');
 try{
  if($action==='save_variables'){
   if(!payroll_user_can($pdo,$userId,'payroll.edit'))throw new RuntimeException('Sem permissão para editar Payroll.');
   if($run&&$run['status']==='Fechado')throw new RuntimeException('Reabra o Payroll antes de alterar variáveis.');
   $types=['commission','expenses','km','bonus','extra_subsidy','balance_bonus','other'];$up=$pdo->prepare('INSERT INTO payroll_variables(user_id,payroll_year,payroll_month,variable_type,value,observation,updated_by) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,payroll_year,payroll_month,variable_type) DO UPDATE SET value=excluded.value,observation=excluded.observation,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP');
   foreach((array)($_POST['variables']??[]) as $uid=>$values)foreach($types as $type){$value=str_replace(',','.',trim((string)($values[$type]??'0')));if(!is_numeric($value))throw new RuntimeException('Valor manual inválido.');$up->execute([(int)$uid,$year,$month,$type,(float)$value,trim((string)($values['observation']??'')),$userId]);}$flashSuccess='Variáveis mensais guardadas na base de dados.';
  } elseif(in_array($action,['validate','close','reopen'],true)){
   $permission=['validate'=>'payroll.edit','close'=>'payroll.close','reopen'=>'payroll.reopen'][$action];if(!payroll_user_can($pdo,$userId,$permission))throw new RuntimeException('Sem permissão para esta ação.');
   $data=payroll_build($pdo,$year,$month,$selected,$departmentId,$activeOnly);
   if($action==='validate'){$status='Validado';$fields='validated_by=?,validated_at=CURRENT_TIMESTAMP';}
   elseif($action==='close'){$status='Fechado';$fields='closed_by=?,closed_at=CURRENT_TIMESTAMP,snapshot_json='. $pdo->quote(json_encode($data,JSON_UNESCAPED_UNICODE));}
   else{$status='Rascunho';$fields='reopened_by=?,reopened_at=CURRENT_TIMESTAMP,snapshot_json=NULL';}
   $pdo->prepare('INSERT OR IGNORE INTO payroll_runs(payroll_year,payroll_month,status,filters_json) VALUES(?,?,"Rascunho",?)')->execute([$year,$month,json_encode(['users'=>$selected,'department'=>$departmentId,'active_only'=>$activeOnly])]);$pdo->prepare('UPDATE payroll_runs SET status=?,'.$fields.',updated_at=CURRENT_TIMESTAMP WHERE payroll_year=? AND payroll_month=?')->execute([$status,$userId,$year,$month]);$id=(int)$pdo->query('SELECT id FROM payroll_runs WHERE payroll_year='.(int)$year.' AND payroll_month='.(int)$month)->fetchColumn();$pdo->prepare('INSERT INTO payroll_audit_log(payroll_run_id,action,user_id,details) VALUES(?,?,?,?)')->execute([$id,$action,$userId,'Estado alterado para '.$status]);$flashSuccess='Payroll atualizado para '.$status.'.';
  }
 }catch(Throwable $e){$flashError=$e->getMessage();}
 $runStmt->execute([$year,$month]);$run=$runStmt->fetch(PDO::FETCH_ASSOC);
}
$data=($run&&$run['status']==='Fechado'&&!empty($run['snapshot_json']))?json_decode($run['snapshot_json'],true):payroll_build($pdo,$year,$month,$selected,$departmentId,$activeOnly);
if(($_GET['action']??'')==='export'){
 if(!payroll_user_can($pdo,$userId,'payroll.export')){http_response_code(403);exit('Sem permissão para exportar Payroll.');}
 if($data['warnings']&&!isset($_GET['confirm_warnings'])){$flashError='Confirme conscientemente os alertas antes de exportar.';}else{$tmp=tempnam(sys_get_temp_dir(),'payroll_');payroll_export_xlsx($pdo,$data,$tmp);$name=sprintf('TISSER_Payroll_%04d_%02d.xlsx',$year,$month);header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$name.'"');header('Content-Length: '.filesize($tmp));readfile($tmp);unlink($tmp);log_app_event($pdo,$userId,'payroll.export','Exportação do payroll.',['year'=>$year,'month'=>$month,'warnings'=>count($data['warnings'])]);exit;}
}
$users=$pdo->query('SELECT id,name,user_number FROM users WHERE COALESCE(pin_only_login,0)=0 ORDER BY name COLLATE NOCASE')->fetchAll(PDO::FETCH_ASSOC);$departments=$pdo->query('SELECT id,name FROM hr_departments ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Export Payroll';require __DIR__.'/partials/header.php';
function payroll_num($v){return number_format((float)$v,2,',',' ');}
function payroll_filter_fields($departmentId,$activeOnly,array $selected){echo '<input type="hidden" name="department_id" value="'.(int)$departmentId.'">';if($activeOnly)echo '<input type="hidden" name="active_only" value="1">';foreach($selected as $id)echo '<input type="hidden" name="user_ids[]" value="'.(int)$id.'">';}
?>
<div class="container-fluid py-4">
 <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Export Payroll</h1><p class="text-muted mb-0">Processamento salarial integrado com ponto, horários, férias e ausências.</p></div><span class="badge text-bg-<?= ($run['status']??'Rascunho')==='Fechado'?'dark':(($run['status']??'')==='Validado'?'success':'secondary') ?> fs-6"><?= h((string)($run['status']??'Rascunho')) ?></span></div>
 <?php if($flashSuccess):?><div class="alert alert-success"><?=h($flashSuccess)?></div><?php endif;?><?php if($flashError):?><div class="alert alert-danger"><?=h($flashError)?></div><?php endif;?>
 <form method="get" class="card shadow-sm mb-3"><div class="card-body row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Mês</label><select name="month" class="form-select"><?php for($m=1;$m<=12;$m++):?><option value="<?=$m?>" <?=$m===$month?'selected':''?>><?=h((string)$m)?></option><?php endfor;?></select></div><div class="col-md-2"><label class="form-label">Ano</label><input type="number" name="year" class="form-control" value="<?=$year?>"></div><div class="col-md-3"><label class="form-label">Setor (opcional)</label><select name="department_id" class="form-select"><option value="0">Todos</option><?php foreach($departments as $d):?><option value="<?=$d['id']?>" <?=$departmentId===$d['id']?'selected':''?>><?=h($d['name'])?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Colaboradores (Ctrl para vários)</label><select name="user_ids[]" multiple class="form-select" size="3"><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=in_array((int)$u['id'],$selected,true)?'selected':''?>><?=h(($u['user_number']?$u['user_number'].' · ':'').$u['name'])?></option><?php endforeach;?></select></div><div class="col-md-2"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="active_only" value="1" id="active" <?=$activeOnly?'checked':''?>><label class="form-check-label" for="active">Ativos no período</label></div><button class="btn btn btn-primary w-100">Gerar Payroll</button></div></div></form>
 <?php if($data['warnings']):?><div class="alert alert-warning"><h2 class="h5">Payroll com alertas (<?=count($data['warnings'])?>)</h2><ul class="mb-0"><?php foreach($data['warnings'] as $w):?><li><strong><?=h($w['user'])?></strong><?=!empty($w['date'])?' · '.h($w['date']):''?> — <?=h($w['problem'])?></li><?php endforeach;?></ul></div><?php endif;?>
 <div class="card shadow-sm mb-3"><div class="card-header bg-white"><strong>Resumo para validação</strong></div><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Cód.</th><th>Colaborador</th><th>Dias</th><th>Diurnas</th><th>Noturnas</th><th>Extra 1ª</th><th>Extra 2ª+</th><th>Extra not.</th><th>Sáb./folga</th><th>Subs. alim.</th><th>Férias</th><th>FJ</th><th>FI</th><th>BX</th></tr></thead><tbody><?php foreach($data['rows'] as $s):$c=array_count_values(array_values($s['codes']));?><tr><td><?=h($s['user']['user_number'])?></td><td><?=h($s['user']['name'])?></td><td><?=$s['worked_days']?></td><td><?=payroll_num($s['day_hours'])?></td><td><?=payroll_num($s['night_hours'])?></td><td><?=payroll_num($s['extra_first'])?></td><td><?=payroll_num($s['extra_following'])?></td><td><?=payroll_num($s['extra_night'])?></td><td><?=payroll_num($s['rest_hours'])?></td><td><?=$s['meal_days']?></td><td><?=$c['Fr']??0?></td><td><?=$c['FJ']??0?></td><td><?=$c['FI']??0?></td><td><?=$c['BX']??0?></td></tr><?php endforeach;?></tbody></table></div></div>
 <?php if(($run['status']??'Rascunho')!=='Fechado'&&payroll_user_can($pdo,$userId,'payroll.edit')):?><form method="post" class="card shadow-sm mb-3"><input type="hidden" name="action" value="save_variables"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><?php payroll_filter_fields($departmentId,$activeOnly,$selected);?><div class="card-header bg-white"><strong>Variáveis salariais do mês</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Colaborador</th><th>Comissões €</th><th>Ajudas €</th><th>KM</th><th>Prémio €</th><th>Subs. extra €</th><th>Gratificação €</th><th>Outros €</th><th>Observação</th></tr></thead><tbody><?php foreach($data['rows'] as $s):$uid=(int)$s['user']['id'];$m=$s['manual'];?><tr><td><?=h($s['user']['name'])?></td><?php foreach(['commission','expenses','km','bonus','extra_subsidy','balance_bonus','other'] as $type):?><td><input class="form-control form-control-sm" type="number" step="0.01" name="variables[<?=$uid?>][<?=$type?>]" value="<?=h((string)($m[$type]??0))?>"></td><?php endforeach;?><td><input class="form-control form-control-sm" name="variables[<?=$uid?>][observation]" value="<?=h($s['observations'])?>"></td></tr><?php endforeach;?></tbody></table></div><div class="card-footer"><button class="btn btn-outline-primary">Guardar variáveis</button></div></form><?php endif;?>
 <div class="d-flex gap-2 flex-wrap"><?php if(($run['status']??'Rascunho')!=='Fechado'):?><form method="post"><input type="hidden" name="action" value="validate"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><?php payroll_filter_fields($departmentId,$activeOnly,$selected);?><button class="btn btn-success">Validar</button></form><form method="post"><input type="hidden" name="action" value="close"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><?php payroll_filter_fields($departmentId,$activeOnly,$selected);?><button class="btn btn-dark" onclick="return confirm('Fechar e guardar snapshot imutável deste Payroll?')">Fechar Payroll</button></form><?php else:?><form method="post"><input type="hidden" name="action" value="reopen"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><?php payroll_filter_fields($departmentId,$activeOnly,$selected);?><button class="btn btn-outline-danger" onclick="return confirm('Reabrir este Payroll? A ação ficará em auditoria.')">Reabrir Payroll</button></form><?php endif;?><form method="get"><input type="hidden" name="action" value="export"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><input type="hidden" name="department_id" value="<?=$departmentId?>"><?php if($activeOnly):?><input type="hidden" name="active_only" value="1"><?php endif;?><?php foreach($selected as $selectedId):?><input type="hidden" name="user_ids[]" value="<?=$selectedId?>"><?php endforeach;?><?php if($data['warnings']):?><div class="form-check d-inline-block me-2"><input class="form-check-input" type="checkbox" name="confirm_warnings" value="1" id="confirm" required><label for="confirm" class="form-check-label">Confirmo os alertas</label></div><?php endif;?><button class="btn btn-primary"><i class="bi bi-file-earmark-excel me-1"></i>Exportar Excel</button></form></div>
</div>
<?php require __DIR__.'/partials/footer.php';
