<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/production_dossier_service.php';
require_once __DIR__.'/app/Services/ProductionLabelService.php';
require_login();gt_erp_run_phase1_migrations($pdo);
$user=current_user($pdo)?:[];
$profile=(string)($user['access_profile']??'Utilizador');
$canUseProductionLabels=(int)($user['is_admin']??0)===1||in_array($profile,['Utilizador','Produção','Chefias','RH'],true);
if(!$canUseProductionLabels){http_response_code(403);exit('Sem acesso às etiquetas de produção.');}
$workCenterPrinter=null;$deviceWorkCenterId=(int)($_SESSION['shopfloor_work_center_id']??0);
if($deviceWorkCenterId>0){$printerStmt=$pdo->prepare('SELECT wc.code AS work_center_code,wc.name AS work_center_name,p.name AS printer_name,p.network_uri AS printer_uri FROM erp_work_centers wc LEFT JOIN erp_printers p ON p.id=wc.default_printer_id AND p.is_active=1 WHERE wc.id=? LIMIT 1');$printerStmt->execute([$deviceWorkCenterId]);$workCenterPrinter=$printerStmt->fetch(PDO::FETCH_ASSOC)?:null;}
$orderId=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$type=(string)($_GET['type']??'roll');if(!in_array($type,['roll','ink'],true)){http_response_code(400);exit('Tipo de etiqueta inválido.');}
$dossierService=new ProductionDossierService($pdo);try{$d=$dossierService->dossier($orderId);}catch(Throwable $e){http_response_code(404);exit(h($e->getMessage()));}
$labelService=new ProductionLabelService($pdo);$o=$d['order'];$snapshot=$d['snapshot'];$inks=(array)($snapshot['_colors']??[]);$flashError='';$existingLabels=$labelService->listForOrder($orderId,$type);
function production_label_value($value):string{return is_scalar($value)?trim((string)$value):'';}
function production_label_datetime($value):string{$timestamp=strtotime(production_label_value($value));return $timestamp?date('d/m/Y H:i',$timestamp):'Data não disponível';}
$reference=trim((string)($_GET['reference']??$_POST['reference']??''));if($reference===''&&$type==='roll')$reference='R01';if($reference===''&&$inks)$reference=(string)($inks[0]['ink_code']?:$inks[0]['pantone']?:'TINTA-1');
$saved=$reference!==''?$labelService->find($orderId,$type,$reference):null;
$defaults=$type==='roll'?['roll_number'=>$reference,'lot'=>(string)($snapshot['_order']['lot']??''),'article'=>(string)($o['article_code']??''),'description'=>(string)($o['article_description']??''),'quantity'=>(string)($d['metrics']['good']?:$o['planned_quantity']),'net_weight'=>'','gross_weight'=>'','length'=>'','notes'=>'']:['ink_code'=>$reference,'color'=>'','pantone'=>'','quantity'=>'','lot'=>'','notes'=>''];
if($type==='ink')foreach($inks as$ink){$key=(string)($ink['ink_code']?:$ink['pantone']?:'');if($key===$reference){$defaults=array_merge($defaults,['ink_code'=>$key,'color'=>(string)($ink['color']??$ink['ink_description']??''),'pantone'=>(string)($ink['pantone']??''),'quantity'=>(string)($ink['planned_quantity']??'')]);break;}}
$values=array_merge($defaults,(array)($saved['values']??[]));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validate_csrf_or_abort(false))$flashError='Pedido inválido. Atualize a página.';else try{$posted=(array)($_POST['values']??[]);if($type==='roll')$reference=trim((string)($posted['roll_number']??$reference));$saved=$labelService->save($orderId,$type,$reference,$posted,(int)$user['id']);redirect('production_label.php?id='.$orderId.'&type='.$type.'&reference='.rawurlencode($reference).'&print=1');}catch(Throwable$e){$flashError=$e->getMessage();$values=array_merge($values,(array)($_POST['values']??[]));}
}
$isPrint=($_GET['print']??'')==='1';
if($isPrint&&!$saved){$flashError='Ainda não existem valores validados para esta etiqueta. Valide os dados antes de imprimir.';$isPrint=false;}
if($isPrint):?><!doctype html><html lang="pt"><head><meta charset="utf-8"><title>Etiqueta <?=h($reference)?></title><style>@page{size:100mm 70mm;margin:3mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0}.label{width:94mm;height:64mm;border:2px solid #111;padding:4mm;overflow:hidden}.head{display:flex;justify-content:space-between;border-bottom:2px solid;padding-bottom:2mm}.type{font-size:18pt;font-weight:800}.ref{font-size:17pt;font-weight:800}.of{font-size:10pt}.grid{display:grid;grid-template-columns:1fr 1fr;gap:2mm 5mm;margin-top:3mm}.field{min-width:0}.field span{display:block;text-transform:uppercase;font-size:7pt;color:#555}.field strong{display:block;font-size:12pt;overflow-wrap:anywhere}.foot{border-top:1px solid;margin-top:3mm;padding-top:2mm;font-size:7pt}@media print{.no-print{display:none}}</style></head><body><div class="label"><div class="head"><div><div class="type"><?=$type==='roll'?'ROLO':'TINTA'?></div><div class="of">OF <?=h(production_label_value($o['order_number']??''))?> · <?=h(production_label_value($o['article_code']??''))?></div></div><div class="ref"><?=h($reference)?></div></div><div class="grid"><?php foreach($values as$key=>$value):$value=production_label_value($value);if($value===''||$key==='notes')continue;$labels=['roll_number'=>'Rolo','lot'=>'Lote','article'=>'Artigo','description'=>'Descrição','quantity'=>'Quantidade','net_weight'=>'Peso líquido (kg)','gross_weight'=>'Peso bruto (kg)','length'=>'Metros','ink_code'=>'Código','color'=>'Cor','pantone'=>'Pantone'];?><div class="field"><span><?=h($labels[$key]??(string)$key)?></span><strong><?=h($value)?></strong></div><?php endforeach;?></div><?php $labelNotes=production_label_value($values['notes']??'');if($labelNotes!==''):?><div class="field"><span>Observações</span><strong><?=h($labelNotes)?></strong></div><?php endif;?><div class="foot">Validado por <?=h(production_label_value($saved['validator_name']??''))?> em <?=h(production_label_datetime($saved['validated_at']??''))?></div></div><button type="button" class="no-print" onclick="window.print()">Imprimir etiqueta</button><script>window.addEventListener('load',function(){window.print();});</script></body></html><?php exit;endif;
$pageTitle=($type==='roll'?'Etiqueta de rolo':'Etiqueta de tinta').' · OF '.$o['order_number'];require __DIR__.'/partials/header.php';$fields=$type==='roll'?['roll_number'=>'N.º do rolo','lot'=>'Lote','article'=>'Artigo','description'=>'Descrição','quantity'=>'Quantidade','net_weight'=>'Peso líquido (kg)','gross_weight'=>'Peso bruto (kg)','length'=>'Comprimento (m)','notes'=>'Observações']:['ink_code'=>'Código da tinta','color'=>'Cor / descrição','pantone'=>'Pantone','quantity'=>'Quantidade (kg)','lot'=>'Lote','notes'=>'Observações'];
?><main class="container py-4"><div class="d-flex justify-content-between align-items-start mb-3"><div><a href="production_dossier.php?id=<?=$orderId?>" class="btn btn-link px-0">&larr; Voltar ao dossier</a><h1 class="h3"><?=$type==='roll'?'Etiqueta de rolo':'Etiqueta de tinta'?></h1><p class="text-muted">OF <?=h($o['order_number'])?> · Atualize os valores ou imprima a última versão validada.</p></div></div><?php if($flashError):?><div class="alert alert-danger"><?=h($flashError)?></div><?php endif;?>
<?php if($workCenterPrinter):?><div class="alert alert-light border d-flex gap-2 align-items-center"><i class="bi bi-printer fs-4" aria-hidden="true"></i><div><strong><?=h((string)$workCenterPrinter['work_center_code'].' · '.(string)$workCenterPrinter['work_center_name'])?></strong><div class="small text-secondary"><?php if(!empty($workCenterPrinter['printer_name'])):?>Impressora do centro: <?=h((string)$workCenterPrinter['printer_name'])?> · <?=h((string)$workCenterPrinter['printer_uri'])?><?php else:?>Este centro não tem uma impressora ativa associada.<?php endif;?></div></div></div><?php endif;?>
<?php if($type==='ink'&&$inks):?><form method="get" class="card card-body mb-3"><input type="hidden" name="id" value="<?=$orderId?>"><input type="hidden" name="type" value="ink"><label class="form-label">Tinta da ficha técnica</label><div class="input-group"><select class="form-select" name="reference"><?php foreach($inks as$ink):$key=(string)($ink['ink_code']?:$ink['pantone']?:'TINTA-'.$ink['color_order']);?><option value="<?=h($key)?>" <?=$key===$reference?'selected':''?>><?=h($key.' — '.($ink['color']?:$ink['ink_description']?:'Sem descrição'))?></option><?php endforeach;?></select><button class="btn btn-outline-primary">Carregar valores</button></div></form><?php endif;?>
<?php if($type==='roll'&&$existingLabels):?><div class="card card-body mb-3"><label class="form-label">Rolo existente</label><div class="d-flex gap-2 flex-wrap"><?php foreach($existingLabels as$item):?><a class="btn btn-sm <?=$item['reference_key']===$reference?'btn-primary':'btn-outline-primary'?>" href="production_label.php?id=<?=$orderId?>&type=roll&reference=<?=rawurlencode($item['reference_key'])?>"><?=h($item['reference_key'])?></a><?php endforeach;?><a class="btn btn-sm btn-outline-success" href="production_label.php?id=<?=$orderId?>&type=roll&reference=R<?=count($existingLabels)+1?>"><i class="bi bi-plus-lg"></i> Novo rolo</a></div></div><?php endif;?>
<form method="post" class="card shadow-sm"><?=csrf_input()?><input type="hidden" name="reference" value="<?=h($reference)?>"><div class="card-header bg-white"><strong>Valores validados</strong><?php if($saved):?><span class="text-muted small ms-2">Última validação: <?=h(date('d/m/Y H:i',strtotime((string)$saved['validated_at'])))?></span><?php endif;?></div><div class="card-body row g-3"><?php foreach($fields as$key=>$label):?><div class="<?=$key==='notes'||$key==='description'?'col-12':'col-md-4'?>"><label class="form-label"><?=h($label)?></label><?php if($key==='notes'):?><textarea class="form-control" name="values[<?=$key?>]" rows="2"><?=h((string)($values[$key]??''))?></textarea><?php else:?><input class="form-control" name="values[<?=$key?>]" value="<?=h((string)($values[$key]??''))?>" <?=$key==='roll_number'||$key==='ink_code'?'required':''?>><?php endif;?></div><?php endforeach;?></div><div class="card-footer d-flex gap-2 flex-wrap"><button class="btn btn-primary"><i class="bi bi-check2-circle me-1"></i>Atualizar e imprimir</button><?php if($saved):?><a class="btn btn-outline-secondary" target="_blank" href="production_label.php?id=<?=$orderId?>&type=<?=h($type)?>&reference=<?=rawurlencode($reference)?>&print=1"><i class="bi bi-printer me-1"></i>Imprimir últimos valores validados</a><?php endif;?></div></form></main><?php require __DIR__.'/partials/footer.php';?>
