<?php
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/erp_migrations.php';
require_login();
gt_erp_run_phase1_migrations($pdo);
$user = current_user($pdo) ?: [];
if (!is_admin($pdo, (int) ($_SESSION['user_id'] ?? 0)) && !erp_user_can($pdo, $user, 'erp.view') && !erp_user_can($pdo, $user, 'erp.shopfloor.execute')) {
    http_response_code(403);
    exit('Sem permissão para consultar o planeamento da produção.');
}
$stmt = $pdo->query("SELECT o.*, p.code product_code, fp.code finished_product_code, fp.description finished_product_description, c.name customer_name FROM erp_production_orders o JOIN erp_products p ON p.id=o.product_id LEFT JOIN erp_finished_products fp ON fp.id=o.finished_product_id LEFT JOIN erp_customers c ON c.id=o.customer_id WHERE o.status NOT IN ('Concluída','Fechada','Cancelada') ORDER BY o.planning_priority IS NULL,o.planning_priority,o.due_date IS NULL,o.due_date,o.id DESC");
$orders = $stmt->fetchAll(PDO::FETCH_ASSOC);
$updatedAt = $pdo->query("SELECT MAX(updated_at) FROM erp_production_orders")->fetchColumn();
?>
<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="30"><title>Planeamento da produção · gesTISSER</title><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="assets/production-planning.css?v=<?=h((string)(@filemtime(__DIR__.'/assets/production-planning.css')?:'1'))?>" rel="stylesheet"></head>
<body><header class="planning-screen-header"><div><span class="planning-eyebrow">gesTISSER · Produção</span><h1>Plano de produção</h1></div><div class="planning-screen-meta"><span><i class="bi bi-arrow-repeat"></i> Atualização automática</span><time datetime="<?=h(date(DATE_ATOM))?>"><?=h(date('d/m/Y · H:i'))?></time></div></header>
<main><?php if($orders):?><ol class="planning-screen-list"><?php foreach($orders as $index=>$order):$late=!empty($order['due_date'])&&$order['due_date']<date('Y-m-d');$progress=(float)$order['planned_quantity']>0?min(100,round((float)$order['produced_quantity']/(float)$order['planned_quantity']*100)):0;?><li class="planning-screen-order <?=$late?'is-late':''?>"><div class="planning-rank"><?=$index+1?></div><div class="planning-order-main"><div class="planning-order-title"><strong><?=h($order['order_number'])?></strong><span><?=h((string)($order['finished_product_code']?:$order['product_code']))?></span></div><p><?=h((string)($order['finished_product_description']?:$order['notes']?:'Sem descrição'))?></p><div class="planning-progress"><span style="width:<?=$progress?>%"></span></div></div><div class="planning-customer"><small>Cliente</small><strong><?=h((string)($order['customer_name']?:'—'))?></strong></div><div class="planning-quantity"><small>Produzido / planeado</small><strong><?=h(number_format((float)$order['produced_quantity'],0,',','.'))?> / <?=h(number_format((float)$order['planned_quantity'],0,',','.'))?></strong></div><div class="planning-status"><span><?=h($order['status'])?></span><time class="<?=$late?'late':''?>"><i class="bi bi-calendar3"></i> <?=h($order['due_date']?date('d/m/Y',strtotime($order['due_date'])):'Sem data')?><?=$late?' · atrasada':''?></time></div></li><?php endforeach;?></ol><?php else:?><section class="planning-empty"><i class="bi bi-check2-circle"></i><h2>Produção em dia</h2><p>Não existem ordens de fabrico ativas no planeamento.</p></section><?php endif;?></main>
<footer><span><?=count($orders)?> <?=count($orders)===1?'ordem ativa':'ordens ativas'?></span><span>Prioridades definidas pela administração<?= $updatedAt ? ' · dados alterados em '.h(date('d/m/Y H:i',strtotime((string)$updatedAt))) : '' ?></span></footer></body></html>
