<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__ . '/production_dossier_service.php';
require_once __DIR__ . '/app/Services/ProductionDossierPdf.php';
require_login();gt_erp_run_phase1_migrations($pdo);gt_erp_migrate_production_cost_settings($pdo);
$user=current_user($pdo)?:[];if(!gt_erp_user_can($pdo,$user,'erp.view')){http_response_code(403);exit('Sem acesso à Ordem de Fabrico.');}
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$service=new ProductionDossierService($pdo);
$flashError='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!validate_csrf_or_abort(false))$flashError='Pedido inválido. Atualize a página.';
    elseif(in_array(($_POST['action']??''),['save_close_report','close'],true))try{
        if(!gt_erp_user_can($pdo,$user,'erp.costs_edit'))throw new RuntimeException('Sem permissão para editar o relatório administrativo.');
        $service->saveCloseReport($id,(int)$user['id'],(array)($_POST['report']??[]),trim((string)($_POST['change_reason']??'')));
        if(($_POST['action']??'')==='close'){$override=!empty($_POST['override']);$service->close($id,(int)$user['id'],$override,trim((string)($_POST['override_reason']??'')));redirect('production_dossier.php?id='.$id.'&closed=1');}
        redirect('production_dossier.php?id='.$id.'&saved=1#custos');
    }catch(Throwable $e){$flashError=$e->getMessage();}
}
try{$d=$service->dossier($id);}catch(Throwable $e){http_response_code(404);exit(h($e->getMessage()));}
$o=$d['order'];$s=$d['snapshot'];$m=$d['metrics'];$issues=$service->closureIssues($d);
function pd_num($v,$dec=0){return number_format((float)$v,$dec,',','.');}function pd_money($v){return number_format((float)$v,2,',','.').' €';}function pd_time($v){$v=max(0,(int)round($v));return intdiv($v,60).'h '.str_pad((string)($v%60),2,'0',STR_PAD_LEFT).'m';}
function pd_date($value){$time=strtotime((string)$value);return$time?date('d/m/Y',$time):'—';}
function pd_date_time_part($value,$part){$time=strtotime((string)$value);if(!$time)return'';return$part==='time'?date('H:i',$time):date('d/m/Y',$time);}
function pd_yes_no($enabled,$detail=''){if(!$enabled&&trim((string)$detail)==='')return'Não';return trim((string)$detail)!==''?(string)$detail:'Sim';}
function pd_order_colors($value){$rows=preg_split('/\R/u',trim((string)$value))?:[];return array_values(array_filter(array_map(function($row){$row=trim((string)$row);return preg_replace('/^\s*\S+\s+(?:—|–|-)\s+/u','',$row)?:$row;},$rows),'strlen'));}
function pd_logo_src($path){$path=trim((string)$path);if($path===''||preg_match('#^https?://#i',$path))return$path;$absolute=__DIR__.'/'.ltrim($path,'/');if(!is_file($absolute))return'';$extension=strtolower((string)pathinfo($absolute,PATHINFO_EXTENSION));$mime=['png'=>'image/png','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','webp'=>'image/webp','svg'=>'image/svg+xml'];$contents=file_get_contents($absolute);return$contents===false?'':'data:'.($mime[$extension]??'application/octet-stream').';base64,'.base64_encode($contents);}
$documentNumberStmt=$pdo->prepare('SELECT document_number FROM erp_document_catalog WHERE code = ? AND is_active = 1 LIMIT 1');$documentNumberStmt->execute(['production_dossier']);$productionDossierDocumentNumber=trim((string)$documentNumberStmt->fetchColumn())?:'DOC-PRD-001';
$productionCompanyName=trim((string)app_setting($pdo,'company_name','TISSER'))?:'TISSER';$productionCompanyAddress=trim((string)app_setting($pdo,'company_address',''));$productionCompanyLogo=pd_logo_src((string)app_setting($pdo,'logo_report_dark',''));$productionCompanyContacts=array_filter([trim((string)app_setting($pdo,'company_phone','')),trim((string)app_setting($pdo,'company_email',''))]);
$productionOrderFrontColors=pd_order_colors($s['of_front_colors']??'');$productionOrderBackColors=pd_order_colors($s['of_back_colors']??'');$cr=(array)($d['closeReport']??[]);
$statusClass=['Planeada'=>'primary','Libertada'=>'info','Em produção'=>'warning','Suspensa'=>'secondary','Fechada'=>'success','Cancelada'=>'danger'][$o['status']]??'light';
$mainDocument=ArticleDocument::mainArtwork((array)($s['_documents']??[]));
$mainDocumentThumbnail='';if($mainDocument){$path=ArticleDocument::absolutePath(__DIR__,(string)($mainDocument['file_url']??''));if($path!=='')$mainDocumentThumbnail='data:image/jpeg;base64,'.base64_encode(ArticleDocument::thumbnail($path));}
if(($_GET['format']??'')==='pdf'){
    $filename='OF-'.preg_replace('/[^A-Za-z0-9._-]/','-',(string)$o['order_number']).'.pdf';
    $pdfOutput='';
    if(class_exists('Mpdf\\Mpdf')){
        $pdfBufferLevel=ob_get_level();
        try{ob_start();include __DIR__.'/production_dossier_print.php';$html=(string)ob_get_clean();$pdf=new Mpdf\Mpdf(['format'=>'A4','margin_left'=>0,'margin_right'=>0,'margin_top'=>0,'margin_bottom'=>0]);$pdf->WriteHTML($html);$pdfOutput=$pdf->Output($filename,'S');}
        catch(Throwable $e){while(ob_get_level()>$pdfBufferLevel)ob_end_clean();error_log('Falha ao gerar PDF mPDF da OF '.$id.': '.$e->getMessage());}
    }
    if($pdfOutput==='')$pdfOutput=ProductionDossierPdf::render($d,$mainDocumentThumbnail,$productionDossierDocumentNumber);
    header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="'.$filename.'"');header('Content-Length: '.strlen($pdfOutput));echo $pdfOutput;exit;
}
$pageTitle='Dossier de Produção · OF '.$o['order_number'];require __DIR__.'/partials/header.php';
?>
<link rel="stylesheet" href="assets/production-dossier.css">
<main class="container-fluid py-4 dossier-shell">
<?php if($flashError):?><div class="alert alert-danger white-space-pre"><?=nl2br(h($flashError))?></div><?php endif;?><?php if(isset($_GET['closed'])):?><div class="alert alert-success">OF fechada e custos reais consolidados com sucesso.</div><?php elseif(isset($_GET['saved'])):?><div class="alert alert-success">Relatório administrativo guardado. A alteração ficou registada no histórico.</div><?php endif;?>
<header class="dossier-hero"><div><div class="eyebrow">Dossier de Produção</div><h1>OF <?=h($o['order_number'])?></h1><p><?=h($o['customer_name']?:'Cliente não definido')?> · <?=h($o['article_code']?:'Artigo legado')?> · <?=h($o['article_description']??'')?></p></div><div class="hero-actions"><span class="badge rounded-pill text-bg-<?=$statusClass?>"><?=h($o['status'])?></span><a class="btn btn-warning" href="production_label.php?id=<?=$id?>&type=roll"><i class="bi bi-upc-scan"></i> Etiqueta de rolo</a><a class="btn btn-info" href="production_label.php?id=<?=$id?>&type=ink"><i class="bi bi-droplet-fill"></i> Etiqueta de tinta</a><a class="btn btn-light" href="production_dossier.php?id=<?=$id?>&format=pdf" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i> PDF A4</a></div></header>
<nav class="dossier-tabs" aria-label="Secções do dossier"><?php foreach(['resumo'=>'Resumo','acompanhamento'=>'Folha de Acompanhamento','ficha'=>'Ficha Técnica','operacoes'=>'Operações','consumos'=>'Consumos','qualidade'=>'Qualidade','custos'=>'Custos','documentos'=>'Documentos','historico'=>'Histórico'] as $anchor=>$label):?><a href="#<?=$anchor?>"><?=h($label)?></a><?php endforeach;?></nav>
<section id="resumo" class="metric-grid"><?php foreach([['Quantidade planeada',pd_num($o['planned_quantity']),'bi-boxes',''],['Quantidade boa',pd_num($m['good']),'bi-check-circle',''],['Desperdício',pd_num($m['rejected']).' · '.pd_num($m['waste_percent'],2).' %','bi-recycle',''],['Eficiência',pd_num($m['efficiency'],1).' %','bi-speedometer2',''],['Tempo previsto',pd_time($m['planned_minutes']),'bi-hourglass',''],['Tempo real',pd_time($m['actual_minutes']),'bi-clock-history',''],['Custo previsto',pd_money($m['planned_cost']),'bi-calculator',''],['Custo real',pd_money($m['actual_cost']),'bi-cash-stack','current-cost'],['Custo / 1.000',pd_money($m['thousand_cost']),'bi-graph-up-arrow','thousand-cost']] as $card):?><article class="metric-card"><i class="bi <?=$card[2]?>"></i><span><?=$card[0]?></span><strong<?=$card[3]!==''?' data-cost-summary="'.$card[3].'" aria-live="polite"':''?>><?=$card[1]?></strong></article><?php endforeach;?></section>
<section id="acompanhamento" class="dossier-card"><div class="section-title"><div><span>01</span><h2>Folha de Acompanhamento</h2></div><small>Snapshot imutável · ficha técnica v<?=h($o['technical_version']??$s['_technical_sheet_version']??'—')?></small></div><div class="product-layout"><div class="artwork"><div class="block-label">Desenho / maqueta do artigo</div><?php if($mainDocument&&isset($mainDocument['id'])):?><img src="<?=h(ArticleDocument::thumbnailUrl((int)$mainDocument['id']))?>" alt="Maqueta do artigo"><?php else:?><div class="empty-art"><i class="bi bi-image"></i><span>Defina no artigo a imagem principal de produção.</span></div><?php endif;?></div><div class="spec-grid"><?php foreach(['customer_name'=>'Cliente','customer_product_code'=>'Referência cliente','code'=>'Código artigo','description'=>'Descrição','material'=>'Material','composition'=>'Composição','width'=>'Largura','length'=>'Comprimento','grammage'=>'Gramagem','theoretical_weight'=>'Peso previsto','printer_roll_measure'=>'Rolo impressor','due_date'=>'Entrega'] as$key=>$label):$v=$key==='due_date'?$o['due_date']:($s[$key]??'');if((string)$v==='')continue;?><div><span><?=h($label)?></span><strong><?=h($v)?></strong></div><?php endforeach;?></div></div></section>
<section id="ficha" class="dossier-card"><div class="section-title"><div><span>02</span><h2>Ficha Técnica</h2></div></div><div class="chip-grid"><?php foreach(['microperforation'=>'Microperfuração','has_gusset'=>'Fole','centered_gusset'=>'Fole centrado','has_handle'=>'Asa','has_holes'=>'Furo'] as$key=>$label):?><span class="feature-chip <?=!empty($s[$key])?'on':''?>"><i class="bi <?=!empty($s[$key])?'bi-check-circle-fill':'bi-x-circle'?>"></i><?=h($label)?></span><?php endforeach;?></div><div class="spec-grid compact"><?php foreach(['gusset_length'=>'Medida do fole','seam_type'=>'Tipo de costura','thread_color'=>'Cor do fio','perforation_type'=>'Perfuração','pallet_dimensions'=>'Palete','pallet_lid'=>'Tampa','pallet_film'=>'Filme','pallet_straps'=>'Cintas'] as$key=>$label):if(trim((string)($s[$key]??''))==='')continue;?><div><span><?=h($label)?></span><strong><?=h($s[$key])?></strong></div><?php endforeach;?></div></section>
<section id="operacoes" class="dossier-card"><div class="section-title"><div><span>03</span><h2>Routing e Operações</h2></div><small>Alimentado pelo Shopfloor</small></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Seq.</th><th>Operação</th><th>Máquina</th><th>Início / fim</th><th>Tempo</th><th>Qtd. boa</th><th>Desperdício</th><th>Estado</th></tr></thead><tbody><?php foreach($d['operations'] as$op):?><tr><td><span class="seq"><?=h($op['sequence_no'])?></span></td><td><strong><?=h($op['name'])?></strong><small><?=h($op['instructions']??'')?></small></td><td><?=h($op['machine_name']?:'—')?></td><td><small><?=h($op['started_at']?:'—')?><br><?=h($op['ended_at']?:'—')?></small></td><td><?=pd_time($op['actual_minutes'])?></td><td><?=pd_num($op['quantity_good'])?></td><td><?=pd_num($op['quantity_rejected'])?></td><td><span class="badge text-bg-<?=$op['status']==='Concluída'?'success':'light'?>"><?=h($op['status'])?></span></td></tr><?php endforeach;?><?php if(!$d['operations']):?><tr><td colspan="8" class="text-center text-muted py-4">Esta OF ainda não tem operações no routing.</td></tr><?php endif;?></tbody></table></div></section>
<section id="consumos" class="dossier-card"><div class="section-title"><div><span>04</span><h2>Consumos previstos e reais</h2></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Artigo</th><th>Descrição</th><th>Lote</th><th>Previsto</th><th>Real</th><th>Diferença</th><th>Custo</th></tr></thead><tbody><?php foreach($d['consumptions'] as$c):?><tr><td><?=h($c['code'])?></td><td><?=h($c['description'])?></td><td><?=h($c['lot']?:'—')?></td><td><?=pd_num($c['planned_quantity'],3)?> <?=h($c['unit_code'])?></td><td><?=pd_num($c['quantity'],3)?></td><td class="<?=((float)$c['quantity']>(float)$c['planned_quantity'])?'text-danger':'text-success'?>"><?=pd_num((float)$c['quantity']-(float)$c['planned_quantity'],3)?></td><td><?=pd_money((float)$c['quantity']*(float)$c['unit_cost'])?></td></tr><?php endforeach;?><?php if(!$d['consumptions']):?><tr><td colspan="7" class="text-center text-muted py-4">Sem consumos reais registados.</td></tr><?php endif;?></tbody></table></div></section>
<section id="custos" class="dossier-card"><div class="section-title"><div><span>05</span><h2>Previsto vs. realizado</h2></div></div><div class="table-responsive"><table class="table variance"><thead><tr><th>Categoria</th><th>Previsto</th><th>Real</th><th>Diferença</th><th>Indicador</th></tr></thead><tbody><?php foreach($d['costs']['rows'] as$r):$pct=$r['planned']>0?abs($r['difference'])/$r['planned']*100:($r['actual']>0?100:0);$signal=$pct<=5?'good':($pct<=10?'warn':'bad');?><tr><td><strong><?=h($r['category'])?></strong></td><td><?=pd_money($r['planned'])?></td><td><?=pd_money($r['actual'])?></td><td><?=($r['difference']>0?'+':'').pd_money($r['difference'])?></td><td><span class="signal <?=$signal?>"></span><?=['good'=>'Dentro da tolerância','warn'=>'Atenção','bad'=>'Fora da tolerância'][$signal]?></td></tr><?php endforeach;?></tbody><tfoot><tr><th>Total</th><th><?=pd_money($m['planned_cost'])?></th><th><?=pd_money($m['actual_cost'])?></th><th><?=pd_money($m['actual_cost']-$m['planned_cost'])?></th><th></th></tr></tfoot></table></div></section>
<?php $cr=$d['closeReport'];$costFields=['materia_prima'=>'Matéria-prima','tintas'=>'Tintas','diluente'=>'Diluente','outro'=>'Outro','impressora'=>'Impressora','corte_e_cose'=>'Corte e cose','cliche'=>'Cliché','energia'=>'Energia','embalagem'=>'Embalagem','caixas'=>'Caixas','transporte'=>'Transporte'];$reportTotal=0;foreach($costFields as$costKey=>$costLabel)$reportTotal+=(float)$cr['cost_'.$costKey];$sales=(float)$cr['produced_quantity']*(float)$cr['sale_unit_price'];$grossMargin=$sales-$reportTotal;$canEditReport=gt_erp_user_can($pdo,$user,'erp.costs_edit');$unitCosts=$service->productionUnitCosts();?>
<section class="dossier-card admin-report"><div class="section-title"><div><span>05A</span><h2>Relatório administrativo de custos</h2></div><small>Campos manuais auditados · valores automáticos pré-preenchidos</small></div><form method="post" data-cost-report data-energy-unit-cost="<?=h($unitCosts['energia_saco'])?>" data-pallet-unit-cost="<?=h($unitCosts['palete'])?>"><?=csrf_input()?><input type="hidden" name="action" value="save_close_report"><div class="report-kpis"><?php foreach(['produced_quantity'=>'Quantidade produzida','sale_unit_price'=>'Preço de venda unitário','waste_kg'=>'Desperdício (kg)','waste_percent'=>'Desperdício (%)','pallet_count'=>'N.º de paletes'] as$key=>$label):?><label><span><?=h($label)?></span><input class="form-control" type="number" min="0" step="0.001" name="report[<?=$key?>]" value="<?=h($cr[$key])?>" <?=$canEditReport?'':'disabled'?>></label><?php endforeach;?></div><div class="cost-editor"><?php foreach($costFields as$key=>$label):?><label><span><?=h($label)?></span><div class="input-group"><input class="form-control" type="number" min="0" step="0.01" name="report[cost_<?=$key?>]" value="<?=h($cr['cost_'.$key])?>" <?=$canEditReport?'':'disabled'?>><span class="input-group-text">€</span></div></label><?php endforeach;?></div><div class="report-notes"><label><span>Composição das paletes</span><textarea class="form-control" name="report[pallet_details]" rows="3" <?=$canEditReport?'':'disabled'?>><?=h($cr['pallet_details'])?></textarea></label><label><span>Observações administrativas</span><textarea class="form-control" name="report[notes]" rows="3" <?=$canEditReport?'':'disabled'?>><?=h($cr['notes'])?></textarea></label></div><div class="report-totals" aria-live="polite"><div><span>Custo total</span><strong data-report-total><?=pd_money($reportTotal)?></strong></div><div><span>Custo unitário</span><strong data-report-unit-cost><?=pd_money((float)$cr['produced_quantity']>0?$reportTotal/(float)$cr['produced_quantity']:0)?></strong></div><div><span>Margem bruta</span><strong data-report-margin><?=pd_money($grossMargin)?></strong></div></div><?php if($canEditReport):?><div class="report-actions"><input class="form-control" name="change_reason" placeholder="Nota da alteração (opcional)"><button class="btn btn-primary"><i class="bi bi-save"></i> Guardar relatório</button></div><?php endif;?></form></section>
<section id="qualidade" class="dossier-card closure"><div><div class="section-title"><div><span>06</span><h2>Fecho da Ordem de Fabrico</h2></div></div><?php if($o['status']==='Fechada'):?><div class="closure-ok"><i class="bi bi-patch-check-fill"></i> Ordem fechada. O relatório de produção está consolidado.</div><?php elseif($issues):?><div class="closure-warning"><strong>Não é possível fechar a OF</strong><ul><?php foreach($issues as$i):?><li><?=h($i)?></li><?php endforeach;?></ul></div><?php else:?><div class="closure-ok"><i class="bi bi-check2-circle"></i> Todas as verificações obrigatórias estão concluídas.</div><?php endif;?></div><?php if($o['status']!=='Fechada'&&$canEditReport):?><form method="post" class="close-form"><?=csrf_input()?><input type="hidden" name="action" value="close"><?php foreach($cr as$key=>$value):?><input type="hidden" name="report[<?=h($key)?>]" value="<?=h($value)?>"><?php endforeach;?><?php if($issues):?><label><input type="checkbox" name="override" value="1"> Override autorizado</label><textarea class="form-control" name="override_reason" placeholder="Motivo obrigatório do override"></textarea><?php endif;?><button class="btn btn-success"><i class="bi bi-lock"></i> Fechar Ordem de Fabrico</button></form><?php endif;?></section>
<section id="documentos" class="dossier-card"><div class="section-title"><div><span>07</span><h2>Documentos</h2></div></div><div class="document-grid"><?php foreach((array)($s['_documents']??[]) as$doc):?><a href="<?=h(isset($doc['id'])?ArticleDocument::url((int)$doc['id']):(string)$doc['file_url'])?>" target="_blank" rel="noopener"><i class="bi bi-file-earmark"></i><span><strong><?=h($doc['title'])?></strong><small><?=h($doc['document_type'])?></small></span></a><?php endforeach;?></div></section>
<section id="historico" class="dossier-card"><div class="section-title"><div><span>08</span><h2>Histórico e auditoria</h2></div></div><?php $audit=$pdo->prepare('SELECT a.*,u.name user_name FROM erp_production_order_audit a LEFT JOIN users u ON u.id=a.user_id WHERE a.production_order_id=? ORDER BY a.id DESC');$audit->execute([$id]);foreach($audit as$a):?><div class="audit-row"><i class="bi bi-clock-history"></i><div><strong><?=h($a['action'])?></strong><small><?=h($a['created_at'])?> · <?=h($a['user_name']?:'Sistema')?><?php if(trim((string)($a['reason']??''))!==''):?> · <?=h($a['reason'])?><?php endif;?></small><?php if($a['action']==='update_close_report'):?><small class="text-success">Valores anteriores e novos preservados no registo de auditoria.</small><?php endif;?></div></div><?php endforeach;?></section>
</main><script src="assets/production-dossier.js"></script><?php require __DIR__.'/partials/footer.php';?>
