<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/app/Services/ProductLabelService.php';
require_once __DIR__.'/app/Services/Code128Barcode.php';
require_login();gt_erp_run_phase1_migrations($pdo);
$user=current_user($pdo)?:[];$profile=(string)($user['access_profile']??'Utilizador');
if((int)($user['is_admin']??0)!==1&&!in_array($profile,['Utilizador','Produção','Chefias','RH'],true)){http_response_code(403);exit('Sem acesso às etiquetas de produto.');}
if($_SERVER['REQUEST_METHOD']!=='POST'||!validate_csrf_or_abort(false)){http_response_code(400);exit('Pedido de impressão inválido.');}
$orderId=filter_var($_POST['production_order_id']??null,FILTER_VALIDATE_INT);$operationId=filter_var($_POST['operation_id']??null,FILTER_VALIDATE_INT);
if(!$orderId||!$operationId){http_response_code(422);exit('A OF e a operação são obrigatórias.');}
$service=new ProductLabelService($pdo);
try{$data=$service->data((int)$orderId,(int)$operationId);$values=$service->validatePrint($_POST);$barcode=Code128Barcode::svg((string)$data['lot']);}
catch(InvalidArgumentException $e){http_response_code(422);exit(h($e->getMessage()));}
catch(RuntimeException $e){http_response_code(403);exit(h($e->getMessage()));}
$autoPrint=($_POST['mode']??'preview')==='print';if($autoPrint)$service->audit($data,$values,(int)$user['id']);
$logo=trim((string)app_setting($pdo,'logo_report_dark',''));if($logo==='')$logo=trim((string)app_setting($pdo,'logo_navbar_light',''));
$company=trim((string)app_setting($pdo,'company_name','TISSER'))?:'TISSER';
function product_label_number($number):string{return number_format((float)$number,fmod((float)$number,1.0)===0.0?0:2,',',' ');}
?><!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Etiqueta de produto · <?=h((string)$data['order_number'])?></title><style>
@page{size:A5 landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#edf0ef;color:#101817;font-family:Arial,Helvetica,sans-serif}.print-toolbar{position:sticky;top:0;z-index:2;display:flex;justify-content:center;gap:12px;padding:14px;background:#fff;border-bottom:1px solid #ccd3d0}.print-toolbar button{min-height:48px;padding:0 28px;border:0;border-radius:8px;background:#136b58;color:#fff;font-size:16px;font-weight:700;cursor:pointer}.print-toolbar button.secondary{background:#fff;color:#26332f;border:1px solid #899792}.labels{padding:10mm}.product-label{width:200mm;height:138mm;margin:0 auto 10mm;padding:10mm 11mm 8mm;background:#fff;border:0.45mm solid #15231f;break-inside:avoid;page-break-inside:avoid;display:flex;flex-direction:column}.label-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:5mm;border-bottom:.45mm solid #15231f}.brand img{display:block;max-width:48mm;max-height:15mm}.brand-fallback{font-size:24pt;font-weight:900;letter-spacing:1pt}.date{text-align:right}.eyebrow{display:block;color:#55635f;font-size:8pt;font-weight:700;letter-spacing:1.2pt;text-transform:uppercase}.date strong{font-size:16pt}.customer{padding:5mm 0 4mm;border-bottom:.2mm solid #a8b2af}.customer strong{display:block;margin:1mm 0;font-size:17pt;line-height:1.15}.customer span{font-size:11pt}.product{padding:4mm 0}.product-code{font-size:13pt;font-weight:800;letter-spacing:.3pt;overflow-wrap:anywhere}.description{margin-top:2.5mm;font-size:19pt;font-weight:700;line-height:1.1}.key-grid{display:grid;grid-template-columns:1fr 1fr;gap:6mm;margin-top:auto}.key-box{padding:3mm 4mm;border:.45mm solid #15231f;border-left:2.2mm solid #136b58}.key-box strong{display:block;margin-top:1mm;font-size:25pt;line-height:1}.barcode{margin:5mm auto 0;width:125mm;text-align:center}.barcode svg{display:block;width:100%;height:20mm;shape-rendering:crispEdges}.barcode strong{display:block;margin-top:1mm;font-size:11pt;letter-spacing:2pt}.label-foot{display:flex;justify-content:space-between;margin-top:3mm;padding-top:2mm;border-top:.2mm solid #a8b2af;color:#46534f;font-size:7pt;font-weight:700;letter-spacing:.8pt;text-transform:uppercase}
@media(max-width:850px){.labels{padding:12px;overflow:auto}.product-label{transform-origin:top left}.print-toolbar{padding:10px}.print-toolbar button{flex:1;padding:0 12px}}
@media print{html,body{width:210mm;background:#fff}.print-toolbar{display:none!important}.labels{padding:0}.product-label{margin:0;border:.45mm solid #15231f;break-after:page;page-break-after:always}.product-label:last-child{break-after:auto;page-break-after:auto}a[href]:after{content:none!important}}
</style></head><body><div class="print-toolbar"><button type="button" class="secondary" onclick="window.close()">Fechar</button><button type="button" onclick="window.print()">Imprimir <?=count(range(1,$values['copies']))?> etiqueta<?= $values['copies']===1?'':'s' ?></button></div><main class="labels"><?php for($copy=1;$copy<=$values['copies'];$copy++):?><article class="product-label"><header class="label-head"><div class="brand"><?php if($logo!==''):?><img src="<?=h($logo)?>" alt="<?=h($company)?>"><?php else:?><span class="brand-fallback"><?=h($company)?></span><?php endif;?></div><div class="date"><span class="eyebrow">Data</span><strong><?=$values['date']->format('d/m/Y')?></strong></div></header><section class="customer"><span class="eyebrow">Cliente</span><strong><?=h((string)$data['customer_name'])?></strong><span><?=h((string)$data['locality'])?></span></section><section class="product"><span class="eyebrow">Produto</span><div class="product-code"><?=h((string)$data['product_code'])?></div><div class="description"><?=h((string)$data['product_description'])?></div></section><section class="key-grid"><div class="key-box"><span class="eyebrow">Quantidade</span><strong><?=h(product_label_number($values['quantity']))?></strong></div><div class="key-box"><span class="eyebrow">Lote</span><strong><?=h((string)$data['lot'])?></strong></div></section><div class="barcode"><?=$barcode?><strong><?=h((string)$data['lot'])?></strong></div><footer class="label-foot"><span><?=h($company)?> · Thinking Packaging</span><span>OF <?=h((string)$data['order_number'])?></span></footer></article><?php endfor;?></main><?php if($autoPrint):?><script>window.addEventListener('load',function(){window.print();});</script><?php endif;?></body></html>
