<!doctype html>
<html lang="pt"><head><meta charset="utf-8"><style>
@page{size:A4 portrait;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#fff;color:#111;font-family:Arial,Helvetica,sans-serif;font-size:8.5pt}.page{width:210mm;height:297mm;padding:9mm 10mm 8mm;display:flex;flex-direction:column;gap:2.2mm;overflow:hidden}.report-header{height:29mm;display:grid;grid-template-columns:48mm 1fr 51mm;align-items:center;border-bottom:2px solid #111;padding-bottom:2.5mm}.brand{height:20mm;display:flex;align-items:center}.brand img{display:block;max-width:45mm;max-height:19mm}.brand-fallback{font-size:22px;font-weight:900;letter-spacing:1px}.title{text-align:center}.title h1{font-size:16px;line-height:1.05;margin:0;text-transform:uppercase}.title .order-number{font-size:12px;font-weight:700;margin-top:1.5mm}.company{text-align:right;font-size:8.5px;line-height:1.35}.company strong{display:block;font-size:10px}.company .date{margin-top:1.2mm;font-weight:700}.section{border:1.5px solid #111;break-inside:avoid}.section-title{font-size:10px;text-align:center;text-transform:uppercase;background:#e6e7e8;border-bottom:1px solid #777;margin:0;padding:1.2mm 2mm;line-height:1.1}.grid{width:100%;border-collapse:collapse;table-layout:fixed}.grid th,.grid td{border-right:1px solid #999;border-bottom:1px solid #999;padding:1.25mm 1.7mm;text-align:left;vertical-align:middle;overflow-wrap:anywhere}.grid th:last-child,.grid td:last-child{border-right:0}.grid tr:last-child th,.grid tr:last-child td{border-bottom:0}.label{font-size:7px;text-transform:uppercase;font-weight:700;color:#333}.value{font-size:9px;font-weight:600}.ident td{height:9mm}.notes{height:22mm;vertical-align:top!important}.operation td{height:9mm}.write{height:8mm}.small{font-size:7px;color:#555}.checkbox{font-size:10px}.ink-table td{height:7.5mm}.ink-face{width:15mm;background:#f3f3f3;font-weight:700;text-transform:uppercase}.summary td{height:12mm}.signature{margin-top:auto}.signature td{height:15mm;vertical-align:bottom;text-align:center;color:#555}.document-footer{border-top:1px solid #aaa;padding-top:1mm;display:flex;justify-content:space-between;color:#777;font-size:6px;letter-spacing:.2px}
</style></head><body><main class="page">
<header class="report-header"><div class="brand"><?php if($productionCompanyLogo!==''):?><img src="<?=h($productionCompanyLogo)?>" alt="Logótipo <?=h($productionCompanyName)?>"><?php else:?><span class="brand-fallback"><?=h($productionCompanyName)?></span><?php endif;?></div><div class="title"><h1>Folha de Acompanhamento</h1><div class="order-number">OF <?=h($o['order_number'])?></div></div><div class="company"><strong><?=h($productionCompanyName)?></strong><?php if($productionCompanyAddress!==''):?><div><?=nl2br(h($productionCompanyAddress))?></div><?php endif;?><?php if($productionCompanyContacts):?><div><?=h(implode(' · ',$productionCompanyContacts))?></div><?php endif;?><div class="date">Data: <?=date('d/m/Y')?></div></div></header>

<section class="section"><h2 class="section-title">Identificação da encomenda e do artigo</h2><table class="grid ident"><tr><td><span class="label">N.º cliente</span><br><span class="value"><?=h($o['customer_code']?:'—')?></span></td><td colspan="2"><span class="label">Cliente</span><br><span class="value"><?=h($o['customer_name']?:'—')?></span></td><td><span class="label">Entrega</span><br><span class="value"><?=h(pd_date($o['due_date']??''))?></span></td></tr><tr><td colspan="2"><span class="label">Referência</span><br><span class="value"><?=h($o['article_code']?:($s['code']??'—'))?></span></td><td><span class="label">Ref. cliente</span><br><span class="value"><?=h($s['customer_product_code']??'—')?></span></td><td><span class="label">Encomenda n.º</span><br><span class="value"><?=h($o['customer_order_reference']??$s['_order']['customer_order']??'—')?></span></td></tr><tr><td colspan="2"><span class="label">Composição</span><br><span class="value"><?=h($s['composition']??'—')?></span></td><td colspan="2"><span class="label">Descrição</span><br><span class="value"><?=h($o['article_description']?:($s['description']??'—'))?></span></td></tr><tr><td><span class="label">Microperfuração</span><br><span class="value"><?=h(pd_yes_no($s['microperforation']??false,$s['perforation_type']??''))?></span></td><td><span class="label">Cor do fio</span><br><span class="value"><?=h($s['thread_color']??'—')?></span></td><td><span class="label">Costura</span><br><span class="value"><?=h($s['seam_type']??'—')?></span></td><td><span class="label">N.º prova</span><br><span class="value"><?=h($s['proof_reference']??'—')?></span></td></tr></table></section>

<section class="section"><h2 class="section-title">Registo de produção</h2><table class="grid operation"><tr><th style="width:24%">Operação</th><th>Início / data</th><th>Hora</th><th>Fim / data</th><th>Hora</th><th>Extra</th></tr><?php $printOps=array_slice($d['operations'],0,4);foreach($printOps as$op):?><tr><td><strong><?=h($op['name'])?></strong><?php if(!empty($op['machine_name'])):?><br><span class="small"><?=h($op['machine_name'])?></span><?php endif;?></td><td><?=h(pd_date_time_part($op['started_at']??'','date'))?></td><td><?=h(pd_date_time_part($op['started_at']??'','time'))?></td><td><?=h(pd_date_time_part($op['ended_at']??'','date'))?></td><td><?=h(pd_date_time_part($op['ended_at']??'','time'))?></td><td></td></tr><?php endforeach;?><?php for($i=count($printOps);$i<3;$i++):?><tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td></tr><?php endfor;?></table></section>

<section class="section"><h2 class="section-title">Quantidades e acabamento</h2><table class="grid summary"><tr><td><span class="label">Qtd. encomendada</span><br><span class="value"><?=pd_num($o['planned_quantity'])?></span></td><td><span class="label">Qtd. produzida</span><br><span class="value"><?=($m['good']??0)>0?pd_num($m['good']):''?></span></td><td><span class="label">Desperdício (kg)</span><br><span class="value"><?=($m['rejected']??0)>0?pd_num($m['rejected'],2):''?></span></td><td><span class="label">Fole / largura</span><br><span class="value"><?=!empty($s['has_gusset'])?h($s['gusset_length']??'Sim'):'Sem fole'?></span></td></tr><tr><td><span class="label">N.º paletes</span><br><span class="value"><?=!empty($cr['pallet_count'])?pd_num($cr['pallet_count']):''?></span></td><td><span class="label">Tipo / medida palete</span><br><span class="value"><?=h($s['pallet_dimensions']??'')?></span></td><td><span class="label">Qtd. por palete</span><br><span class="value"><?=h($s['pallet_quantity']??'')?></span></td><td><span class="label">Embalagem</span><br><span class="value"><?=h(implode(' · ',array_filter([$s['pallet_lid']??'',$s['pallet_film']??'',$s['pallet_straps']??''])))?></span></td></tr></table></section>

<section class="section"><h2 class="section-title">Cores a imprimir — Ordem de Fabrico</h2><table class="grid ink-table"><tr><th style="width:15mm">Face</th><th>1</th><th>2</th><th>3</th><th>4</th></tr><?php foreach(['Frente'=>$productionOrderFrontColors,'Verso'=>$productionOrderBackColors] as$face=>$colors):$cells=array_pad(array_slice($colors,0,4),4,'');?><tr><td class="ink-face"><?=h($face)?></td><?php foreach($cells as$color):?><td><?=h($color)?></td><?php endforeach;?></tr><?php endforeach;?></table></section>

<section class="section"><h2 class="section-title">Consumos</h2><table class="grid"><tr><th>Material / tinta</th><th style="width:22mm">Lote</th><th style="width:23mm">Previsto</th><th style="width:23mm">Real</th></tr><?php $printConsumptions=array_slice($d['consumptions'],0,3);foreach($printConsumptions as$c):?><tr class="write"><td><?=h($c['code'].' · '.$c['description'])?></td><td><?=h($c['lot']??'')?></td><td><?=pd_num($c['planned_quantity']??0,3)?> <?=h($c['unit_code']??'')?></td><td><?=($c['quantity']??0)>0?pd_num($c['quantity'],3):''?></td></tr><?php endforeach;?><?php for($i=count($printConsumptions);$i<3;$i++):?><tr class="write"><td>&nbsp;</td><td></td><td></td><td></td></tr><?php endfor;?></table></section>

<section class="section"><h2 class="section-title">Observações</h2><table class="grid"><tr><td class="notes"><span class="label">Observações da encomenda</span><br><?=nl2br(h(trim((string)($o['notes']??''))))?></td><td class="notes"><span class="label">Observações do operador</span></td></tr></table></section>
<section class="section signature"><table class="grid"><tr><td>Operador de impressão</td><td>Operador de acabamento</td><td>Controlo de qualidade</td></tr></table></section>
<footer class="document-footer"><span>Código interno do documento: <?=h($productionDossierDocumentNumber)?></span><span>Gerado pelo GesTisser</span></footer>
</main></body></html>
