<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/app/Services/RawMaterialRollLabelService.php';
require_login();gt_erp_run_phase1_migrations($pdo);
$user=current_user($pdo)?:[];$service=new RawMaterialRollLabelService($pdo);$flashError='';
$materials=$pdo->query('SELECT id,code,description FROM erp_raw_materials WHERE status="Ativo" AND roll_controlled=1 ORDER BY code')->fetchAll(PDO::FETCH_ASSOC);
$materialId=filter_input(INPUT_GET,'raw_material_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'raw_material_id',FILTER_VALIDATE_INT)?:0;
$material=null;if($materialId){try{$material=$service->material($materialId);}catch(Throwable $e){$flashError=$e->getMessage();$materialId=0;}}
$sourceId=filter_input(INPUT_GET,'source_label_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'source_label_id',FILTER_VALIDATE_INT)?:0;
$source=$sourceId?$service->find($sourceId):null;if($source&&$materialId!== (int)$source['raw_material_id']){$source=null;$sourceId=0;$flashError='O rolo selecionado não pertence a esta matéria-prima.';}
$values=$source?:['entry_number'=>'','supplier_lot'=>'','metres'=>'','weight_kg'=>'','barcode'=>'','label_date'=>date('Y-m-d')];$saved=null;if($source){$values['barcode']='';$values['label_date']=date('Y-m-d');}
if($_SERVER['REQUEST_METHOD']==='POST'&&$material){
    if(!validate_csrf_or_abort(false))$flashError='Pedido inválido. Atualize a página.';
    else try{$values=array_merge($values,(array)($_POST['values']??[]));if($source){$saved=$service->relabel($sourceId,(int)($_POST['production_order_id']??0),$values,(int)$user['id']);}else{$saved=$service->save($materialId,$values,(int)$user['id']);}redirect('raw_material_roll_label.php?raw_material_id='.$materialId.'&printed_label_id='.(int)$saved['id'].'&print=1');}catch(Throwable $e){$flashError=$e->getMessage();}
}
$printedId=filter_input(INPUT_GET,'printed_label_id',FILTER_VALIDATE_INT)?:0;if(!$saved&&$printedId)$saved=$service->find($printedId);if($saved&&$materialId!==(int)$saved['raw_material_id']){$saved=null;}
function roll_label_number($value,$decimals=0){return number_format((float)$value,$decimals,',',' ');}
$isPrint=($_GET['print']??'')==='1'&&$saved;$company=trim((string)app_setting($pdo,'company_name','TISSER'))?:'TISSER';$logo=trim((string)app_setting($pdo,'logo_report_dark',''));
if($isPrint):?><!doctype html><html lang="pt"><head><meta charset="utf-8"><title>Rolo <?=h($saved['barcode'])?></title><style>
@page{size:100mm 50mm;margin:0}*{box-sizing:border-box}html,body{width:100mm;height:50mm;margin:0}body{font-family:Arial,sans-serif;color:#111}.label{width:100mm;height:50mm;border:.35mm solid #111;padding:2.4mm 3mm}.head{height:10mm;display:grid;grid-template-columns:25mm 1fr 28mm;align-items:center;border-bottom:.3mm solid #111}.head img{max-width:23mm;max-height:7mm}.brand{font-weight:900}.title{text-align:center;font-size:10pt;font-weight:900}.entry{text-align:right;font-size:6pt;text-transform:uppercase}.entry strong{display:block;font-size:11pt}.content{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1.2mm 3mm;padding-top:1.5mm}.field span{display:block;font-size:5pt;color:#666;text-transform:uppercase;font-weight:700}.field strong{display:block;font-size:8pt}.article{grid-column:span 3}.article strong{font-size:7.5pt}.barcode{grid-column:span 2;border-top:.2mm solid #888;padding-top:1mm;font-family:monospace;font-size:13pt;letter-spacing:2pt;font-weight:900}.date{text-align:right;border-top:.2mm solid #888;padding-top:1mm}.no-print{margin:8px}@media print{.no-print{display:none}}
</style></head><body><div class="label"><div class="head"><div><?php if($logo):?><img src="<?=h($logo)?>" alt="<?=h($company)?>"><?php else:?><span class="brand"><?=h($company)?></span><?php endif;?></div><div class="title">ETIQUETA DE ROLO</div><div class="entry">Entrada<strong><?=h($saved['entry_number'])?></strong></div></div><div class="content"><div class="field"><span>Lote fornecedor</span><strong><?=h($saved['supplier_lot'])?></strong></div><div class="field"><span>Metros</span><strong><?=roll_label_number($saved['metres'])?> m</strong></div><div class="field"><span>Peso</span><strong><?=roll_label_number($saved['weight_kg'],2)?> kg</strong></div><div class="field article"><span>Matéria-prima</span><strong><?=h($saved['article_code'].' — '.$saved['description'])?></strong></div><div class="barcode"><?=h($saved['barcode'])?></div><div class="field date"><span>Data</span><strong><?=h(date('d/m/Y',strtotime($saved['label_date'])))?></strong></div></div></div><button class="no-print" onclick="window.print()">Imprimir etiqueta</button><script>window.addEventListener('load',function(){window.print();});</script></body></html><?php exit;endif;
$search=trim((string)($_GET['roll_search']??''));$rolls=$material?$service->search($materialId,$search):[];$orders=$source?$service->productionOrders():[];
$pageTitle='Etiquetas de rolo';require __DIR__.'/partials/header.php';
?><main class="container py-4"><a href="erp.php?page=raw_materials" class="btn btn-link px-0">&larr; Voltar às matérias-primas</a><h1 class="h3">Etiquetas de rolo</h1><p class="text-muted">Selecione a matéria-prima; a preparação da etiqueta aparece imediatamente abaixo. A etiqueta base permanece sem OF nem produto final; a OF só é registada ao declarar o consumo de um rolo existente.</p><?php if($flashError):?><div class="alert alert-danger"><?=h($flashError)?></div><?php endif;?>
<form method="get" class="card card-body mb-3"><label class="form-label" for="raw-material">Matéria-prima</label><select class="form-select js-searchable-select" id="raw-material" name="raw_material_id" onchange="this.form.submit()" required><option value="">Selecionar…</option><?php foreach($materials as$row):?><option value="<?=(int)$row['id']?>" <?=(int)$row['id']===$materialId?'selected':''?>><?=h($row['code'].' — '.$row['description'])?></option><?php endforeach;?></select><noscript><button class="btn btn-primary mt-2">Abrir</button></noscript></form>
<?php if($material):?><section aria-live="polite"><div class="mb-3"><strong><?=h($material['code'])?></strong> — <?=h($material['description'])?></div>
<?php if($rolls||$search!==''):?><div class="card mb-3"><div class="card-header bg-white"><strong>Pesquisar rolo existente</strong></div><div class="card-body"><form method="get" class="input-group"><input type="hidden" name="raw_material_id" value="<?=$materialId?>"><input class="form-control" name="roll_search" value="<?=h($search)?>" placeholder="Entrada, lote do fornecedor ou código de barras"><button class="btn btn-outline-primary"><i class="bi bi-search"></i> Pesquisar</button></form><?php if($rolls):?><div class="table-responsive mt-3"><table class="table table-sm align-middle mb-0"><thead><tr><th>Entrada</th><th>Lote</th><th>Metros</th><th>Peso</th><th>Código de barras</th><th></th></tr></thead><tbody><?php foreach($rolls as$row):?><tr><td><?=h($row['entry_number'])?></td><td><?=h($row['supplier_lot'])?></td><td><?=roll_label_number($row['metres'])?></td><td><?=roll_label_number($row['weight_kg'],2)?> kg</td><td><code><?=h($row['barcode'])?></code></td><td><a class="btn btn-sm btn-outline-primary" href="?raw_material_id=<?=$materialId?>&source_label_id=<?=(int)$row['id']?>#label-form">Consumir / nova etiqueta</a></td></tr><?php endforeach;?></tbody></table></div><?php elseif($search!==''):?><p class="text-muted mb-0 mt-3">Nenhum rolo encontrado.</p><?php endif;?></div></div><?php else:?><div class="card card-body mb-3"><form method="get" class="input-group"><input type="hidden" name="raw_material_id" value="<?=$materialId?>"><input class="form-control" name="roll_search" placeholder="Pesquisar rolo por entrada, lote ou código de barras"><button class="btn btn-outline-primary"><i class="bi bi-search"></i> Pesquisar rolo</button></form></div><?php endif;?>
<form method="post" class="card shadow-sm" id="label-form"><?=csrf_input()?><input type="hidden" name="raw_material_id" value="<?=$materialId?>"><input type="hidden" name="source_label_id" value="<?=$sourceId?>"><div class="card-header bg-white"><strong><?=$source?'Registar consumo e lançar nova etiqueta':'Nova etiqueta'?></strong><?php if($source):?><div class="small text-muted">Rolo de origem: <?=h($source['barcode'])?>. Indique as quantidades restantes e um novo código de barras.</div><?php endif;?></div><div class="card-body row g-3"><?php foreach(['entry_number'=>'Entrada','supplier_lot'=>'Lote do fornecedor','metres'=>'Metros restantes','weight_kg'=>'Peso restante (kg)','barcode'=>'Novo código de barras','label_date'=>'Data'] as$key=>$title):?><div class="col-md-4"><label class="form-label"><?=h($source||!in_array($key,['metres','weight_kg','barcode'],true)?$title:str_replace(' restantes','',$title))?></label><input class="form-control" name="values[<?=$key?>]" value="<?=h((string)($values[$key]??''))?>" <?=$key==='label_date'?'type="date"':(in_array($key,['metres','weight_kg'],true)?'type="number" min="0.001" step="0.01"':'')?> required></div><?php endforeach;?><?php if($source):?><div class="col-12"><label class="form-label">OF onde a matéria-prima foi consumida</label><select class="form-select js-searchable-select" name="production_order_id" required><option value="">Selecionar OF…</option><?php foreach($orders as$order):?><option value="<?=(int)$order['id']?>"><?=h($order['order_number'].' · '.$order['status'])?></option><?php endforeach;?></select></div><?php endif;?></div><div class="card-footer d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-printer me-1"></i><?=$source?'Registar consumo e imprimir nova etiqueta':'Guardar e imprimir'?></button><?php if($source):?><a class="btn btn-outline-secondary" href="?raw_material_id=<?=$materialId?>">Cancelar</a><?php endif;?></div></form></section><?php endif;?></main><?php require __DIR__.'/partials/footer.php';
