<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/erp_migrations.php';
require_once __DIR__.'/app/Services/RawMaterialInkLabelService.php';
require_login();gt_erp_run_phase1_migrations($pdo);
$user=current_user($pdo)?:[];$service=new RawMaterialInkLabelService($pdo);
$materialId=filter_input(INPUT_GET,'raw_material_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'raw_material_id',FILTER_VALIDATE_INT)?:0;
try{$material=$service->material($materialId);}catch(Throwable $e){http_response_code(404);exit(h($e->getMessage()));}
$labelId=filter_input(INPUT_GET,'label_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'label_id',FILTER_VALIDATE_INT)?:0;
$saved=$labelId?$service->find($labelId):null;if($saved&&(int)$saved['raw_material_id']!==$materialId){http_response_code(404);exit('Etiqueta não encontrada.');}
$values=$saved?:['entry_number'=>'','supplier_lot'=>'','weight_kg'=>'','barcode'=>'','label_date'=>date('Y-m-d')];$flashError='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!validate_csrf_or_abort(false))$flashError='Pedido inválido. Atualize a página.';
    else try{$values=array_merge($values,(array)($_POST['values']??[]));$saved=$service->save($materialId,$values,(int)$user['id'],$labelId);redirect('raw_material_ink_label.php?raw_material_id='.$materialId.'&label_id='.(int)$saved['id'].'&print=1');}catch(Throwable $e){$flashError=$e->getMessage();}
}
function ink_label_number($value,$decimals=0){return number_format((float)$value,$decimals,',',' ');}
$isPrint=($_GET['print']??'')==='1'&&$saved;$company=trim((string)app_setting($pdo,'company_name','TISSER'))?:'TISSER';$logo=trim((string)app_setting($pdo,'logo_report_dark',''));
if($isPrint):?><!doctype html><html lang="pt"><head><meta charset="utf-8"><title>Tinta <?=h($saved['barcode'])?></title><style>
@page{size:100mm 50mm;margin:0}*{box-sizing:border-box}html,body{width:100mm;height:50mm;margin:0}body{font-family:Arial,sans-serif;color:#111}.label{width:100mm;height:50mm;border:.35mm solid #111;padding:2.4mm 3mm}.head{height:10mm;display:grid;grid-template-columns:25mm 1fr 28mm;align-items:center;border-bottom:.3mm solid #111}.head img{max-width:23mm;max-height:7mm}.brand{font-weight:900}.title{text-align:center;font-size:10pt;font-weight:900}.entry{text-align:right;font-size:6pt;text-transform:uppercase}.entry strong{display:block;font-size:11pt}.content{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1.2mm 3mm;padding-top:1.5mm}.field span{display:block;font-size:5pt;color:#666;text-transform:uppercase;font-weight:700}.field strong{display:block;font-size:8pt}.article{grid-column:span 3}.article strong{font-size:7.5pt}.barcode{grid-column:span 2;border-top:.2mm solid #888;padding-top:1mm;font-family:monospace;font-size:13pt;letter-spacing:2pt;font-weight:900}.date{text-align:right;border-top:.2mm solid #888;padding-top:1mm}.no-print{margin:8px}@media print{.no-print{display:none}}
</style></head><body><div class="label"><div class="head"><div><?php if($logo):?><img src="<?=h($logo)?>" alt="<?=h($company)?>"><?php else:?><span class="brand"><?=h($company)?></span><?php endif;?></div><div class="title">ETIQUETA DE TINTA</div><div class="entry">Entrada<strong><?=h($saved['entry_number'])?></strong></div></div><div class="content"><div class="field"><span>Lote fornecedor</span><strong><?=h($saved['supplier_lot'])?></strong></div><div class="field"><span>Peso</span><strong><?=ink_label_number($saved['weight_kg'],2)?> kg</strong></div><div class="field article"><span>Matéria-prima</span><strong><?=h($saved['article_code'].' — '.$saved['description'])?></strong></div><div class="barcode"><?=h($saved['barcode'])?></div><div class="field date"><span>Data</span><strong><?=h(date('d/m/Y',strtotime($saved['label_date'])))?></strong></div></div></div><button class="no-print" onclick="window.print()">Imprimir etiqueta</button><script>window.addEventListener('load',function(){window.print();});</script></body></html><?php exit;endif;
$history=$service->listForMaterial($materialId);$pageTitle='Etiquetas de tinta · '.$material['code'];require __DIR__.'/partials/header.php';
?><main class="container py-4"><a href="erp.php?page=raw_materials" class="btn btn-link px-0">&larr; Voltar às matérias-primas</a><div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h3">Etiqueta de tinta</h1><p class="text-muted mb-0"><strong><?=h($material['code'])?></strong> — <?=h($material['description'])?></p><p class="small text-muted">A etiqueta está associada exclusivamente à tinta enquanto matéria-prima, sem OF nem produto final.</p></div></div><?php if($flashError):?><div class="alert alert-danger"><?=h($flashError)?></div><?php endif;?><form method="post" class="card shadow-sm mb-3"><?=csrf_input()?><input type="hidden" name="raw_material_id" value="<?=$materialId?>"><input type="hidden" name="label_id" value="<?=$labelId?>"><div class="card-header bg-white"><strong><?=$labelId?'Editar etiqueta':'Nova etiqueta'?></strong></div><div class="card-body row g-3"><?php foreach(['entry_number'=>'Entrada','supplier_lot'=>'Lote do fornecedor','weight_kg'=>'Peso (kg)','barcode'=>'Código de barras','label_date'=>'Data'] as$key=>$title):?><div class="col-md-4"><label class="form-label"><?=h($title)?></label><input class="form-control" name="values[<?=$key?>]" value="<?=h((string)($values[$key]??''))?>" <?=$key==='label_date'?'type="date"':($key==='weight_kg'?'type="number" min="0.001" step="0.01"':'')?> required></div><?php endforeach;?></div><div class="card-footer"><button class="btn btn-primary"><i class="bi bi-printer me-1"></i>Guardar e imprimir</button></div></form><?php if($history):?><div class="card"><div class="card-header bg-white"><strong>Etiquetas anteriores</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Entrada</th><th>Lote fornecedor</th><th>Código de barras</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($history as$row):?><tr><td><?=h($row['entry_number'])?></td><td><?=h($row['supplier_lot'])?></td><td><code><?=h($row['barcode'])?></code></td><td><?=h($row['label_date'])?></td><td><a class="btn btn-sm btn-outline-secondary" href="raw_material_ink_label.php?raw_material_id=<?=$materialId?>&label_id=<?=(int)$row['id']?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?></main><?php require __DIR__.'/partials/footer.php';
