<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/app/Installer/CopyActivationService.php';

function ia_assert($condition, $message) { if (!$condition) { throw new RuntimeException($message); } }
function ia_tmp($name) { $path=sys_get_temp_dir().'/gestisser_installer_'.$name.'_'.bin2hex(random_bytes(4)); mkdir($path,0750,true); return $path; }
function ia_db($path, $movements=3) {
    $pdo=new PDO('sqlite:'.$path); $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION); $pdo->exec('PRAGMA foreign_keys=ON');
    $pdo->exec('CREATE TABLE users(id INTEGER PRIMARY KEY,password TEXT NOT NULL,is_admin INTEGER,is_active INTEGER,name TEXT,email TEXT); CREATE TABLE erp_customers(id INTEGER PRIMARY KEY,code TEXT,name TEXT); CREATE TABLE erp_suppliers(id INTEGER PRIMARY KEY,code TEXT,name TEXT); CREATE TABLE erp_finished_products(id INTEGER PRIMARY KEY,code TEXT,description TEXT); CREATE TABLE erp_raw_materials(id INTEGER PRIMARY KEY,code TEXT,description TEXT); CREATE TABLE erp_production_orders(id INTEGER PRIMARY KEY,order_number TEXT); CREATE TABLE erp_stock_movements(id INTEGER PRIMARY KEY,quantity REAL); CREATE TABLE erp_stock_balances(item_type TEXT,item_id INTEGER,physical_qty REAL); CREATE TABLE app_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT); CREATE TABLE integrations(id INTEGER PRIMARY KEY,is_active INTEGER,status TEXT); CREATE TABLE integration_flows(id INTEGER PRIMARY KEY,is_active INTEGER)');
    $hash=password_hash('segredo-teste',PASSWORD_DEFAULT); $s=$pdo->prepare('INSERT INTO users VALUES(1,?,1,1,"Admin","admin@example.invalid")');$s->execute(array($hash));
    $pdo->exec("INSERT INTO erp_customers VALUES(1,'C1','Cliente'); INSERT INTO erp_suppliers VALUES(1,'F1','Fornecedor'); INSERT INTO erp_finished_products VALUES(1,'P1','Produto'); INSERT INTO erp_raw_materials VALUES(1,'M1','Material'); INSERT INTO erp_production_orders VALUES(1,'OF1'); INSERT INTO erp_stock_balances VALUES('raw_material',1,75); INSERT INTO integrations VALUES(1,1,'on'); INSERT INTO integration_flows VALUES(1,1)");
    $insert=$pdo->prepare('INSERT INTO erp_stock_movements(id,quantity) VALUES(?,?)'); for($i=1;$i<=$movements;$i++){$insert->execute(array($i,$i/10));}
    return array($pdo,$hash);
}
function ia_remove($dir) { if(!is_dir($dir))return; $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST); foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());} rmdir($dir); }

$dirs=array();
try {
    // 1/3: no database and an empty SQLite file are both safe new-install states.
    $root=ia_tmp('new');$dirs[]=$root;$s=new CopyActivationService($root);ia_assert($s->diagnose()['state']==='new','Nova instalação não detetada.');touch($root.'/database.sqlite');ia_assert($s->diagnose()['state']==='empty','SQLite vazio não detetado.');
    // 4: malformed SQLite.
    $root=ia_tmp('invalid');$dirs[]=$root;file_put_contents($root.'/database.sqlite','not sqlite');ia_assert((new CopyActivationService($root))->diagnose()['state']==='invalid','SQLite inválido aceite.');
    // 5: another application's valid database.
    $root=ia_tmp('foreign');$dirs[]=$root;$p=new PDO('sqlite:'.$root.'/database.sqlite');$p->exec('CREATE TABLE wordpress(id INTEGER)');unset($p);ia_assert((new CopyActivationService($root))->diagnose()['state']==='invalid','Base de outro sistema aceite.');
    // 2, 9-13 and 20: valid GesTISSER copy, preserving the current 1,917 movements.
    $root=ia_tmp('copy');$dirs[]=$root;mkdir($root.'/storage',0750,true);list($pdo,$passwordHash)=ia_db($root.'/database.sqlite',1917);unset($pdo);$service=new CopyActivationService($root);$readConnection=new PDO('sqlite:'.$root.'/database.sqlite');$hashBeforeDiagnosis=hash_file('sha256',$root.'/database.sqlite');$d=$service->diagnose($root.'/missing-production.sqlite');ia_assert($d['state']==='existing'&&$d['integrity']==='ok'&&!$d['foreign_keys'],'Cópia válida/integridade/FKs falharam.');ia_assert($d['lock_error']===null&&$d['compatible'],'O diagnóstico deve permitir ativação em PHP 7.0 sem erro de transação.');ia_assert(!$d['real_lock'],'Uma ligação normal de leitura foi confundida com lock SQLite real.');ia_assert($d['active_path']===realpath($root.'/database.sqlite')&&$d['production_path']===$root.'/missing-production.sqlite','Os caminhos do diagnóstico não foram normalizados.');ia_assert(!$d['production_exists']&&!$d['same_as_production'],'Base de produção inexistente foi identificada incorretamente.');ia_assert(hash_file('sha256',$root.'/database.sqlite')===$hashBeforeDiagnosis,'O diagnóstico alterou a base.');unset($readConnection);ia_assert($d['users']===1&&$d['administrators']===1,'Utilizadores/admin não detetados.');$before=$service->snapshot();ia_assert($before['counts']['erp_stock_movements']===1917,'Fixture não contém 1.917 movimentos.');$activated=$service->activate('test');$after=$service->snapshot();ia_assert($before['counts']===$after['counts'],'Contagens críticas mudaram.');ia_assert($before['passwords']===$after['passwords']&&$before['stock_movements']===$after['stock_movements']&&$before['stock_balances']===$after['stock_balances'],'Passwords, movimentos ou saldos mudaram.');$check=new PDO('sqlite:'.$root.'/database.sqlite');$stored=$check->query('SELECT password FROM users WHERE id=1')->fetchColumn();ia_assert($stored===$passwordHash&&password_verify('segredo-teste',$stored),'Autenticação/password não foi preservada.');ia_assert((int)$check->query('SELECT is_active FROM integrations')->fetchColumn()===0&&(int)$check->query('SELECT is_active FROM integration_flows')->fetchColumn()===0,'Integrações não foram desativadas.');ia_assert(is_file($activated['backup']['path'])&&hash_file('sha256',$activated['backup']['path'])===$activated['backup']['sha256'],'Backup/hash inválido.');ia_assert(is_file($service->lockPath()),'Bloqueio do instalador não criado.');ia_assert($service->diagnose()['environment']==='test','O ambiente Teste não aparece no diagnóstico após ativação.');
    // 7: a second activation does not rerun an applied migration.
    $again=(new CopyActivationService($root))->activate('test');ia_assert($again['migrations']===array(),'Migração idempotente voltou a executar.');
    // 14-17: persisted test isolation: outbound services, cron, sessions, uploads and logs.
    $cfg=json_decode(file_get_contents($root.'/storage/installation.json'),true);ia_assert($cfg['environment']==='test'&&!$cfg['external_services_enabled']&&!$cfg['cron_enabled'],'Ambiente de teste permite saídas/cron.');ia_assert(strpos($cfg['session_name'],'test')!==false&&strpos($cfg['uploads_path'],'/test')!==false&&strpos($cfg['logs_path'],'/test')!==false,'Sessão/uploads/logs não isolados.');
    // 6: backup directory cannot be created.
    $root=ia_tmp('backupfail');$dirs[]=$root;list($p,$h)=ia_db($root.'/database.sqlite');unset($p);file_put_contents($root.'/blocked','x');$bad=new CopyActivationService($root,$root.'/database.sqlite',$root.'/blocked');$failed=false;try{$bad->createVerifiedBackup();}catch(RuntimeException $e){$failed=true;}ia_assert($failed,'Falha de backup não abortou.');
    // 8: migration failure rolls its transaction back and retains original data.
    $root=ia_tmp('rollback');$dirs[]=$root;mkdir($root.'/storage',0750,true);list($p,$h)=ia_db($root.'/database.sqlite');$p->exec("CREATE TRIGGER stop_integrations BEFORE UPDATE ON integrations BEGIN SELECT RAISE(ABORT,'stop'); END");unset($p);$rollback=new CopyActivationService($root);$snap=$rollback->snapshot();$failed=false;try{$rollback->activate('test');}catch(RuntimeException $e){$failed=true;}ia_assert($failed,'Erro de migração não abortou.');ia_assert($snap===$rollback->snapshot(),'Rollback não preservou dados.');$p=new PDO('sqlite:'.$root.'/database.sqlite');ia_assert((int)$p->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='gestisser_schema_migrations'")->fetchColumn()===0,'DDL da migração não foi revertido.');ia_assert(count(glob($root.'/storage/backups/*.sqlite'))===1,'Backup de falha não foi mantido.');
    // Production path collision is rejected for test environments.
    $root=ia_tmp('collision');$dirs[]=$root;mkdir($root.'/storage',0750,true);list($p,$h)=ia_db($root.'/database.sqlite');unset($p);$collision=new CopyActivationService($root);$failed=false;try{$collision->activate('test',$root.'/database.sqlite');}catch(RuntimeException $e){$failed=true;}ia_assert($failed,'Base de produção foi aceite como teste.');
    // A real concurrent SQLite writer is reported distinctly.
    $root=ia_tmp('locked');$dirs[]=$root;mkdir($root.'/storage',0750,true);list($writer,$h)=ia_db($root.'/database.sqlite');$writer->exec('BEGIN IMMEDIATE');$locked=new CopyActivationService($root);$lockDiagnosis=$locked->diagnose();ia_assert($lockDiagnosis['real_lock'],'Lock SQLite real não foi detetado.');$writer->exec('ROLLBACK');unset($writer);ia_assert(!$locked->diagnose()['real_lock'],'Lock SQLite permaneceu depois de libertado.');
    echo "Installer copy activation: OK (20 safety scenarios)\n";
} finally { foreach($dirs as $dir){ia_remove($dir);} }
