<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/Services/InventoryService.php';
$serviceReflection=new ReflectionClass(InventoryService::class);foreach(['appendWordSearch','registerSearchNormalizer']as$method){if($serviceReflection->getMethod($method)->hasReturnType())throw new RuntimeException('Os métodos internos do inventário devem manter compatibilidade com PHP 7.0.');}
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$pdo->exec('CREATE TABLE erp_suppliers(id INTEGER PRIMARY KEY,code TEXT,name TEXT);CREATE TABLE erp_material_types(id INTEGER PRIMARY KEY,code TEXT,name TEXT);CREATE TABLE erp_product_types(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE erp_colors(id INTEGER PRIMARY KEY,code TEXT,name TEXT,pantone TEXT);CREATE TABLE erp_units(id INTEGER PRIMARY KEY,code TEXT);CREATE TABLE erp_warehouses(id INTEGER PRIMARY KEY,code TEXT,name TEXT);CREATE TABLE erp_locations(id INTEGER PRIMARY KEY,warehouse_id INTEGER,code TEXT);CREATE TABLE erp_raw_materials(id INTEGER PRIMARY KEY,code TEXT,description TEXT,product_category TEXT DEFAULT "raw_material",material_type_id INTEGER,preferred_supplier_id INTEGER,color_id INTEGER,width REAL,grammage REAL,primary_unit_id INTEGER,average_price REAL,standard_price REAL,min_stock REAL);CREATE TABLE erp_finished_products(id INTEGER PRIMARY KEY,code TEXT,description TEXT,product_type_id INTEGER,material_type_id INTEGER,bag_color TEXT,front_colors TEXT,back_colors TEXT,thread_color TEXT,width REAL,grammage REAL,unit_id INTEGER,standard_cost REAL,min_stock REAL);CREATE TABLE erp_stock_balances(item_type TEXT,item_id INTEGER,warehouse_id INTEGER,location_id INTEGER,lot TEXT,physical_qty REAL,reserved_qty REAL,blocked_qty REAL,ordered_qty REAL DEFAULT 0)');
$pdo->exec("INSERT INTO erp_warehouses(code,name) VALUES ('ARM','Principal')");$warehouseId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_locations(warehouse_id,code) VALUES ({$warehouseId},'GERAL')");$locationId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_suppliers(code,name) VALUES ('SUP-A','Fornecedor Alfa')");$supplierId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_material_types(code,name) VALUES ('TEC','Tecido')");$typeId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_colors(code,name) VALUES ('AZ','Azul royal')");$colorId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_raw_materials(code,description,material_type_id,preferred_supplier_id,color_id,width,grammage,min_stock,average_price) VALUES ('MP-AZUL','Tecido azul',{$typeId},{$supplierId},{$colorId},1.5,60,10,2.5)");$itemId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO erp_stock_balances(item_type,item_id,warehouse_id,location_id,lot,physical_qty,reserved_qty,blocked_qty) VALUES ('raw_material',{$itemId},{$warehouseId},{$locationId},'L-001',12,3,1)");
$rows=InventoryService::rows($pdo,InventoryService::filters(['inventory_q'=>'Alfa','inventory_supplier_id'=>$supplierId,'inventory_stock_state'=>'low']));if(count($rows)!==1||(float)$rows[0]['available_qty']!==8.0||(float)$rows[0]['stock_value']!==30.0)throw new RuntimeException('A pesquisa ou os cálculos do inventário estão incorretos.');if(InventoryService::rows($pdo,InventoryService::filters(['inventory_q'=>'inexistente'])))throw new RuntimeException('A pesquisa textual devolveu artigos indevidos.');
$detailRows=InventoryService::rows($pdo,InventoryService::filters(['inventory_color'=>'royal','inventory_width'=>'1,5','inventory_grammage'=>'60']));if(count($detailRows)!==1)throw new RuntimeException('Os filtros de cor, largura e gramagem não devolveram o artigo esperado.');if(InventoryService::rows($pdo,InventoryService::filters(['inventory_color'=>'verde'])))throw new RuntimeException('O filtro de cor devolveu artigos indevidos.');
$pdo->exec("UPDATE erp_colors SET name='Branca Pérola',pantone='Pérola 01' WHERE id={$colorId}");
$versatileRows=InventoryService::rows($pdo,InventoryService::filters(['inventory_q'=>'l 001 alfa tecido','inventory_color'=>'perola branca']));if(count($versatileRows)!==1)throw new RuntimeException('A pesquisa com várias palavras, campos, pontuação e acentos não encontrou o artigo.');
$supplierCodeRows=InventoryService::rows($pdo,InventoryService::filters(['inventory_q'=>'sup mp azul']));if(count($supplierCodeRows)!==1)throw new RuntimeException('A pesquisa combinada por códigos de fornecedor e artigo não encontrou o artigo.');
echo"Pesquisa versátil, filtros de detalhe e valorização de inventário validados.\n";
