<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/Services/OperationConsumptionService.php';
function consumption_assert($condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
$serviceSource=(string)file_get_contents(dirname(__DIR__).'/app/Services/OperationConsumptionService.php');
consumption_assert(preg_match('/^\s*\[[^]]+\]\s*=/m', $serviceSource)!==1,'O serviço usa destructuring incompatível com PHP 7.0.');
consumption_assert(strpos($serviceSource,'private PDO $pdo')===false&&strpos($serviceSource,'): ?array')===false,'O serviço usa tipos incompatíveis com PHP 7.0.');
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$pdo->exec('CREATE TABLE erp_units(id INTEGER PRIMARY KEY,code TEXT);CREATE TABLE erp_suppliers(id INTEGER PRIMARY KEY,code TEXT);CREATE TABLE erp_warehouses(id INTEGER PRIMARY KEY,code TEXT);CREATE TABLE erp_locations(id INTEGER PRIMARY KEY,code TEXT);CREATE TABLE erp_work_centers(id INTEGER PRIMARY KEY);CREATE TABLE erp_raw_materials(id INTEGER PRIMARY KEY,code TEXT,description TEXT,width REAL,grammage REAL,average_price REAL,primary_unit_id INTEGER,preferred_supplier_id INTEGER,status TEXT);CREATE TABLE erp_production_orders(id INTEGER PRIMARY KEY,product_id INTEGER);CREATE TABLE erp_production_order_operations(id INTEGER PRIMARY KEY,production_order_id INTEGER);CREATE TABLE erp_raw_material_roll_labels(id INTEGER PRIMARY KEY,raw_material_id INTEGER,entry_number TEXT,supplier_lot TEXT,metres REAL,weight_kg REAL,barcode TEXT,status TEXT,warehouse_id INTEGER,location_id INTEGER,initial_weight_kg REAL,updated_at TEXT);CREATE TABLE erp_raw_material_ink_labels(id INTEGER PRIMARY KEY,raw_material_id INTEGER,entry_number TEXT,supplier_lot TEXT,weight_kg REAL,barcode TEXT,status TEXT,warehouse_id INTEGER,location_id INTEGER,initial_weight_kg REAL,updated_at TEXT);CREATE TABLE erp_stock_balances(item_type TEXT,item_id INTEGER,warehouse_id INTEGER,location_id INTEGER,lot TEXT,physical_qty REAL,reserved_qty REAL,blocked_qty REAL,updated_at TEXT);CREATE TABLE erp_stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,movement_number TEXT,movement_type TEXT,item_type TEXT,item_id INTEGER,lot TEXT,roll_id INTEGER,quantity REAL,weight REAL,warehouse_from_id INTEGER,location_from_id INTEGER,unit_cost REAL,total_cost REAL,source_type TEXT,source_id INTEGER,order_reference TEXT,reason TEXT,notes TEXT,created_by INTEGER);CREATE TABLE erp_production_consumptions(id INTEGER PRIMARY KEY AUTOINCREMENT,production_order_id INTEGER,production_order_operation_id INTEGER,product_id INTEGER,raw_material_id INTEGER,quantity REAL,unit_cost REAL,created_by INTEGER,consumption_type TEXT,stock_unit_type TEXT,stock_unit_id INTEGER,quantity_before REAL,quantity_after REAL,unit_code TEXT,workstation_id INTEGER,completed_at TEXT,source_movement_id INTEGER,idempotency_key TEXT UNIQUE);');
$pdo->exec('INSERT INTO erp_units VALUES(1,"kg");INSERT INTO erp_warehouses VALUES(1,"ARM");INSERT INTO erp_locations VALUES(1,"A01");INSERT INTO erp_raw_materials VALUES(7,"RF-01","Ráfia",57,55,2.5,1,NULL,"Ativo");INSERT INTO erp_production_orders VALUES(20,99);INSERT INTO erp_production_order_operations VALUES(30,20);INSERT INTO erp_raw_material_roll_labels VALUES(40,7,"ENT-1","LOTE-A",2951,185,"1800174","AVAILABLE",1,1,185,CURRENT_TIMESTAMP);INSERT INTO erp_stock_balances VALUES("raw_material",7,1,1,"LOTE-A",185,100,0,CURRENT_TIMESTAMP);');
$service=new OperationConsumptionService($pdo);
$unit=$service->findUnit('ROLL','1800174');consumption_assert($unit&&$unit['article_code']==='RF-01','A pesquisa não devolveu a unidade física.');
$id=$service->startUnit(30,'ROLL','1800174',5,0,'start-1');consumption_assert($id===$service->startUnit(30,'ROLL','1800174',5,0,'start-1'),'O início repetido não é idempotente.');
consumption_assert($pdo->query('SELECT status FROM erp_raw_material_roll_labels')->fetchColumn()==='IN_USE','O rolo não ficou em utilização.');
$closed=$service->finishUnit($id,120,5,'finish-1');consumption_assert((float)$closed['quantity']===65.0,'O consumo calculado não corresponde a inicial menos restante.');
consumption_assert((float)$pdo->query('SELECT weight_kg FROM erp_raw_material_roll_labels')->fetchColumn()===120.0,'A mesma etiqueta não reteve a quantidade atual.');
consumption_assert((float)$pdo->query('SELECT physical_qty FROM erp_stock_balances')->fetchColumn()===120.0,'O stock oficial não foi abatido.');
consumption_assert((int)$pdo->query('SELECT COUNT(*) FROM erp_stock_movements')->fetchColumn()===1,'O consumo não gerou exatamente um movimento.');
try{$service->startUnit(30,'ROLL','1800174',5,0,'start-2');$service->finishUnit(2,121,5,'finish-invalid');throw new RuntimeException('Foi aceite restante superior ao inicial.');}catch(InvalidArgumentException $expected){}
consumption_assert((float)$pdo->query('SELECT physical_qty FROM erp_stock_balances')->fetchColumn()===120.0,'Uma operação inválida alterou o stock.');
echo "Consumos rastreados, movimentos, idempotência e limites validados.\n";
