-- Migration documental de referência. A aplicação executa as mesmas alterações
-- idempotentes através de gt_erp_run_phase1_migrations(). Não elimina nem renomeia dados.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS erp_article_technical_sheet_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, finished_product_id INTEGER NOT NULL, version_no INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','approved','obsolete')), effective_from TEXT, snapshot_json TEXT NOT NULL, notes TEXT, created_by INTEGER, approved_by INTEGER, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, approved_at DATETIME, UNIQUE(finished_product_id,version_no), FOREIGN KEY(finished_product_id) REFERENCES erp_finished_products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS erp_production_order_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, production_order_id INTEGER NOT NULL UNIQUE, technical_sheet_version_id INTEGER, snapshot_json TEXT NOT NULL, created_by INTEGER, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(production_order_id) REFERENCES erp_production_orders(id) ON DELETE CASCADE, FOREIGN KEY(technical_sheet_version_id) REFERENCES erp_article_technical_sheet_versions(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS erp_production_cost_rates (id INTEGER PRIMARY KEY AUTOINCREMENT, cost_type TEXT NOT NULL, reference_type TEXT, reference_id INTEGER, description TEXT NOT NULL, hourly_rate REAL NOT NULL DEFAULT 0, unit_rate REAL NOT NULL DEFAULT 0, energy_kwh REAL NOT NULL DEFAULT 0, valid_from TEXT NOT NULL, valid_until TEXT, is_active INTEGER NOT NULL DEFAULT 1, created_by INTEGER, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_production_order_costs (id INTEGER PRIMARY KEY AUTOINCREMENT, production_order_id INTEGER NOT NULL, production_order_operation_id INTEGER, category TEXT NOT NULL, description TEXT NOT NULL, planned_amount REAL NOT NULL DEFAULT 0, actual_amount REAL NOT NULL DEFAULT 0, source_type TEXT, source_id INTEGER, calculated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_production_order_closures (id INTEGER PRIMARY KEY AUTOINCREMENT, production_order_id INTEGER NOT NULL UNIQUE, metrics_json TEXT NOT NULL, total_planned_cost REAL NOT NULL DEFAULT 0, total_actual_cost REAL NOT NULL DEFAULT 0, override_reason TEXT, closed_by INTEGER NOT NULL, closed_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_production_order_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, production_order_id INTEGER NOT NULL, user_id INTEGER, action TEXT NOT NULL, old_value_json TEXT, new_value_json TEXT, reason TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS erp_production_order_close_reports (id INTEGER PRIMARY KEY AUTOINCREMENT, production_order_id INTEGER NOT NULL UNIQUE, report_json TEXT NOT NULL, updated_by INTEGER NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
-- As colunas compatíveis são adicionadas condicionalmente por erp_migrations.php,
-- pois SQLite não suporta ADD COLUMN IF NOT EXISTS.
