<?php
// No database access or application bootstrap: safe to use from CLI.
return [
 'encomendas'=>['file'=>'01_encomendas.xlsx','label'=>'Encomendas','columns'=>'legacy_id numero_encomenda cliente_codigo cliente_nome data_encomenda data_entrega estado observacoes referencia_cliente origem gestisser_customer_id importar erro_validacao','required'=>'legacy_id numero_encomenda data_encomenda','natural'=>'numero_encomenda'],
 'encomendas_linhas'=>['file'=>'02_encomendas_linhas.xlsx','label'=>'Linhas de encomendas','columns'=>'legacy_id encomenda_legacy_id numero_encomenda artigo_codigo artigo_designacao quantidade unidade preco data_entrega gestisser_product_id importar erro_validacao','required'=>'legacy_id quantidade','natural'=>''],
 'ofs'=>['file'=>'03_ofs.xlsx','label'=>'OFs','columns'=>'legacy_id numero_of encomenda_legacy_id numero_encomenda cliente_codigo artigo_codigo quantidade_planeada quantidade_produzida data_criacao data_inicio data_fim estado observacoes gestisser_customer_id gestisser_product_id importar erro_validacao','required'=>'legacy_id numero_of quantidade_planeada data_criacao','natural'=>'numero_of'],
 'of_operacoes'=>['file'=>'04_of_operacoes.xlsx','label'=>'Operações das OFs','columns'=>'legacy_id of_legacy_id numero_of operacao sequencia quantidade horas_previstas horas_reais data_inicio data_fim estado importar erro_validacao','required'=>'legacy_id operacao sequencia','natural'=>''],
 'entradas_mp'=>['file'=>'05_entradas_mp.xlsx','label'=>'Entradas de matérias-primas','columns'=>'legacy_id numero_entrada data_entrada fornecedor_codigo fornecedor_nome materia_prima_codigo materia_prima_designacao lote_fornecedor quantidade unidade peso_kg documento observacoes gestisser_supplier_id gestisser_raw_material_id importar erro_validacao','required'=>'legacy_id numero_entrada data_entrada quantidade','natural'=>''],
 'rolos_rafia'=>['file'=>'06_rolos_rafia.xlsx','label'=>'Rolos de ráfia','columns'=>'legacy_id numero_entrada data_entrada materia_prima_codigo materia_prima_designacao fornecedor_codigo lote_fornecedor identificacao_rolo largura gramagem cor peso_inicial_kg peso_atual_kg metros_iniciais metros_atuais estado localizacao warehouse_id location_id barcode gestisser_raw_material_id importar erro_validacao','required'=>'legacy_id numero_entrada data_entrada lote_fornecedor peso_inicial_kg peso_atual_kg metros_iniciais metros_atuais','natural'=>'identificacao_rolo'],
 'lotes_tintas'=>['file'=>'07_lotes_tintas.xlsx','label'=>'Lotes/recipientes de tintas','columns'=>'legacy_id numero_entrada data_entrada materia_prima_codigo materia_prima_designacao fornecedor_codigo lote_fornecedor identificacao_recipiente peso_inicial_kg peso_atual_kg estado localizacao warehouse_id location_id barcode gestisser_raw_material_id importar erro_validacao','required'=>'legacy_id numero_entrada data_entrada lote_fornecedor peso_inicial_kg peso_atual_kg','natural'=>'identificacao_recipiente'],
 'movimentos_historicos'=>['file'=>'08_movimentos_historicos.xlsx','label'=>'Movimentos históricos','columns'=>'legacy_id data_movimento tipo_movimento origem materia_prima_codigo quantidade unidade peso_kg lote rolo of_numero encomenda_numero documento observacoes gestisser_raw_material_id importar afeta_stock_atual erro_validacao','required'=>'legacy_id data_movimento tipo_movimento quantidade','natural'=>''],
];
